import { SentenceRewrites } from "./types";

/**
 * 初級（中学）の例文の書き直し。キーは単語ID、値は [例文, 和訳]。
 * 決まり・使い方は scripts/apply_sentences.ts を参照。
 */
export const junior: SentenceRewrites = {
  j149: ["The concert last night was really [_____]!", "昨夜のコンサートは本当に素晴らしかった！"],
  j157: ["Please wash your hands. They must be [_____] before you eat.", "手を洗ってください。食べる前は手がきれいでなければなりません。"],
  a27: ["We walked [_____] the river.", "私たちは川に沿って歩きました。"],
  a69: ["I hit my [_____] on the door.", "私はドアに頭をぶつけました。"],
  a82: ["I don't like carrots, and my brother doesn't like them [_____].", "私はニンジンが好きではなく、兄も好きではありません。"],
  a97: ["Let's [_____] Mom with a birthday cake.", "誕生日ケーキでお母さんを驚かせよう。"],
  a110: ["My tennis [_____] and I won the doubles match.", "テニスの相方と私はダブルスの試合に勝ちました。"],
  a143: ["Tell me the [_____] why you were late.", "遅れた理由を教えてください。"],
  a164: ["The [_____] grows rice and vegetables on his land.", "その農家は自分の土地で米や野菜を育てています。"],
  a214: ["A hammer is a useful [_____].", "かなづちは便利な道具です。"],
  a232: ["My brother likes to [_____] old coins.", "兄は古い硬貨を集めるのが好きです。"],
  a330: ["Your garden looks [_____] with all those flowers.", "たくさんの花で、あなたの庭は美しく見えます。"],
  a348: ["Who will [_____] the kingdom after the old king dies?", "老いた王が亡くなった後、誰が王国を治めるのでしょうか。"],
  a675: ["She put the roses in a glass [_____].", "彼女はバラをガラスの花瓶に入れました。"],
  a784: ["They got married in a small [_____] in the village.", "二人は村の小さな教会で結婚しました。"],
  a787: ["The king lived in a huge [_____].", "王は巨大な宮殿に住んでいました。"],
  a1000: ["There are sixty [_____]s in an hour.", "1時間は60分です。"],
  a1101: ["Don't leave any answers [_____] on the test.", "テストの答えを白紙のままにしないでください。"],
  a1367: ["Watch your [_____] on the icy road.", "凍った道では足元に気をつけて。"],
  a1423: ["His joke was so [_____] that everyone laughed.", "彼の冗談はとてもおかしくて、みんなが笑いました。"],
  j371: ["[_____] Tanaka is our new English teacher.", "田中さんは私たちの新しい英語の先生です。"],
  j372: ["[_____]'s go to the park after school.", "放課後、公園に行こう。"],
  j373: ["[_____] I use your pen?", "あなたのペンを使ってもいいですか。"],
  j374: ["A triangle has [_____] sides.", "三角形には3つの辺があります。"],
  j375: ["We must solve this [_____] together.", "私たちはこの問題を一緒に解決しなければなりません。"],
  j376: ["Who scored the [_____] goals in the game?", "その試合で最も多くのゴールを決めたのは誰ですか。"],
  j377: ["I usually [_____] to school with my friends.", "私はふだん友だちと歩いて学校へ行きます。"],
  j378: ["Please [_____] my question in English.", "私の質問に英語で答えてください。"],
  j379: ["Could you say that [_____], please?", "もう一度言っていただけますか。"],
  j380: ["We have to [_____] the house at seven tomorrow.", "明日は7時に家を出なければなりません。"],
  j381: ["The children ran [_____] the classroom when the bell rang.", "ベルが鳴ると、子どもたちは教室の中へ走って入りました。"],
  j382: ["I want to [_____] this old photo forever.", "私はこの古い写真をずっと持っていたい。"],
  j383: ["My sister and I go to the [_____] school.", "姉と私は同じ学校に通っています。"],
  j384: ["Let's [_____] the color of the wall to blue.", "壁の色を青に変えよう。"],
  j385: ["[_____] do you live?", "あなたはどこに住んでいますか。"],
  j386: ["Do you have [_____] questions?", "何か質問はありますか。"],
  j387: ["Nice to [_____] you.", "お会いできてうれしいです。"],
  j388: ["Nobody knows what will happen in the [_____].", "未来に何が起こるかは誰にも分かりません。"],
  j389: ["I am [_____] in Japanese history.", "私は日本の歴史に興味があります。"],
  j390: ["\"Can I sit here?\" \"[_____], go ahead.\"", "「ここに座ってもいいですか。」「いいですよ、どうぞ。」"],
  j391: ["\"Is everything [_____]?\" \"Yes, there are no problems.\"", "「すべて大丈夫ですか。」「はい、問題ありません。」"],
  j392: ["Please write your [_____] at the top of the paper.", "紙の一番上に名前を書いてください。"],
  j393: ["The science class was so [_____] that I asked many questions.", "理科の授業がとてもおもしろかったので、たくさん質問しました。"],
  j394: ["She is my [_____] friend.", "彼女は私のいちばんの親友です。"],
  j395: ["Let me show you one more [_____] of this rule.", "この規則の例をもう一つ見せましょう。"],
  j396: ["My [_____] is on the second floor.", "私の部屋は2階にあります。"],
  j397: ["What [_____] do you want to do in the future?", "将来どんな仕事をしたいですか。"],
  j398: ["We will [_____] at a hotel near the beach.", "私たちは浜辺の近くのホテルに滞在します。"],
  j399: ["Please [_____] your bag on the desk.", "かばんを机の上に置いてください。"],
  j400: ["I am [_____] that he will come.", "私は彼が来ると確信しています。"],
  j401: ["This shirt is too small. Can I try [_____] one?", "このシャツは小さすぎます。別のものを試してもいいですか。"],
  j402: ["Please [_____] talking and listen to me.", "おしゃべりをやめて、私の話を聞いてください。"],
  j403: ["I [_____] in the park every morning.", "私は毎朝公園で走ります。"],
  j404: ["My mother will [_____] me how to cook curry.", "母が私にカレーの作り方を教えてくれます。"],
  j405: ["Our soccer [_____] won the game.", "私たちのサッカーチームが試合に勝ちました。"],
  j406: ["Can you help me [_____] this heavy desk?", "この重い机を動かすのを手伝ってくれますか。"],
  j407: ["This math problem is easy. [_____] a child can solve it.", "この数学の問題は簡単です。子どもでさえ解けます。"],
  j408: ["The movie will [_____] at seven o'clock.", "映画は7時に始まります。"],
  j409: ["I [_____] you will get well soon.", "早く元気になることを願っています。"],
  j410: ["Do you want to [_____] our club?", "私たちのクラブに入りませんか。"],
  j411: ["There is a bridge [_____] the river.", "川の上に橋がかかっています。"],
  j412: ["Working abroad was a great [_____] for me.", "海外で働いたことは、私にとって素晴らしい経験でした。"],
  j413: ["She has [_____] sick since Monday.", "彼女は月曜日からずっと具合が悪い。"],
  j414: ["I [_____] my family very much.", "私は家族をとても愛しています。"],
  j415: ["New York is a big city in [_____].", "ニューヨークはアメリカの大都市です。"],
  j416: ["\"[_____], Tom! How are you?\"", "「やあ、トム！元気？」"],
  j417: ["I met him three years [_____].", "私は3年前に彼に会いました。"],
  j418: ["The little [_____] is playing with his dog.", "その小さな男の子は犬と遊んでいます。"],
  j419: ["This [_____] sells fresh bread.", "この店は焼きたてのパンを売っています。"],
  j420: ["The first [_____] of the movie was boring.", "その映画の最初の部分は退屈でした。"],
  j421: ["The weather is [_____] today, so let's go out.", "今日はすてきな天気だから、出かけよう。"],
  j422: ["I am in the tennis [_____] at school.", "私は学校でテニス部に入っています。"],
  j423: ["I have never seen [_____] a big fish.", "そんなに大きな魚は見たことがありません。"],
  j424: ["Every [_____] of the team must come to practice.", "チームの一員はみんな練習に来なければなりません。"],
  j425: ["[_____] in my class likes the new teacher.", "クラスのみんなが新しい先生を好きです。"],
  j426: ["Babies [_____] very quickly.", "赤ちゃんはとても早く成長します。"],
  j427: ["My grandmother told me a funny [_____].", "祖母がおかしな話をしてくれました。"],
  j428: ["I want to make friends from [_____] countries.", "私は外国の友だちを作りたいです。"],
  j429: ["The [_____] of students in our school is five hundred.", "私たちの学校の生徒の数は500人です。"],
  j430: ["It's already noon, but my brother is [_____] in bed.", "もう正午なのに、兄はまだ寝ています。"],
  j431: ["Please [_____] to the teacher carefully.", "先生の話を注意深く聞いてください。"],
  j432: ["This song is very [_____] among young people.", "この歌は若い人たちにとても人気があります。"],
  j433: ["The movie is two [_____]s long.", "その映画の長さは2時間です。"],
  j434: ["I heard a strange [_____] in the night.", "夜中に奇妙な音が聞こえました。"],
  j435: ["I have [_____] friends in this town, so I feel lonely.", "この町には友だちが少ないので、さびしく感じます。"],
  j436: ["The bus will come [_____].", "バスはまもなく来ます。"],
  j437: ["Cats [_____] for about fifteen hours a day.", "猫は1日に約15時間眠ります。"],
  j438: ["The [_____] with long hair is my sister.", "長い髪の女の子は私の妹です。"],
  j439: ["Let's walk [_____] the stairs.", "階段を下りましょう。"],
  j440: ["The ship changed its [_____] because of the storm.", "嵐のため、船は進路を変えました。"],
  j441: ["I am very [_____] for breaking your cup.", "あなたのカップを割ってしまって本当にすみません。"],
  j442: ["Many people visit the summer [_____] every year.", "毎年たくさんの人が夏祭りを訪れます。"],
  j443: ["My brother will enter [_____] next April.", "兄は来年の4月に高校に入学します。"],
  j444: ["I will [_____] you a letter from London.", "ロンドンからあなたに手紙を送ります。"],
  j445: ["I was [_____] to see him at the station.", "駅で彼に会って驚きました。"],
  j446: ["Look at [_____] stars in the sky.", "空のあれらの星を見て。"],
  j447: ["He is the only [_____] who knows the answer.", "彼は答えを知っている唯一の人です。"],
  j449: ["I can't [_____] it's already December!", "もう12月だなんて信じられない！"],
  j450: ["I have to [_____] my homework before dinner.", "夕食の前に宿題を終えなければなりません。"],
  j451: ["Raise your [_____] if you know the answer.", "答えが分かったら手を挙げてください。"],
  j452: ["I can't live [_____] music.", "私は音楽なしでは生きられません。"],
  j453: ["Two plus three makes [_____].", "2たす3は5です。"],
  j454: ["I had a strange [_____] last night.", "昨夜、奇妙な夢を見ました。"],
  j456: ["The [_____] goes around the sun.", "地球は太陽の周りを回っています。"],
  j457: ["Did you get my [_____]? I sent it last week.", "私の手紙は届きましたか。先週送りました。"],
  j458: ["A dog has [_____] legs.", "犬には4本の脚があります。"],
  j459: ["Is there [_____] I can do for you?", "何か私にできることはありますか。"],
  j460: ["Please [_____] here for a moment.", "ここで少し待ってください。"],
  j461: ["Each [_____] must sign this paper.", "親はそれぞれこの書類に署名しなければなりません。"],
  j462: ["February is the [_____] month of the year.", "2月は1年の2番目の月です。"],
  j463: ["He is the best [_____] on our baseball team.", "彼は私たちの野球チームでいちばんの選手です。"],
  j464: ["Will you be [_____] to come to the party?", "パーティーに来ることはできますか。"],
  j465: ["The dog is wagging [_____] tail.", "犬がしっぽを振っています。"],
  j466: ["Please say [_____] to your family for me.", "ご家族によろしく伝えてください。"],
  j467: ["We went to the science [_____] and saw a big dinosaur.", "科学博物館に行って、大きな恐竜を見ました。"],
  j468: ["Taking [_____] of a pet is not easy.", "ペットの世話をするのは簡単ではありません。"],
  j469: ["Birthdays are [_____] days for children.", "誕生日は子どもにとって特別な日です。"],
  j470: ["Kangaroos live in [_____].", "カンガルーはオーストラリアに住んでいます。"],
  j471: ["You can find a lot of [_____] on the Internet.", "インターネットで多くの情報を見つけられます。"],
  j472: ["Our [_____] gave a presentation about the environment.", "私たちのグループは環境について発表しました。"],
  j473: ["Kyoto is [_____] for its old temples.", "京都は古い寺で有名です。"],
  j474: ["My brother plays [_____] every Saturday.", "兄は毎週土曜日にサッカーをします。"],
  j475: ["Can you [_____] my bag for a minute?", "少しの間、私のかばんを持っていてくれますか。"],
  j476: ["Be careful not to [_____] your key.", "鍵をなくさないように気をつけて。"],
  j477: ["[_____] comes after Saturday.", "日曜日は土曜日の次に来ます。"],
  j479: ["She put her books in her [_____].", "彼女は本をかばんに入れました。"],
  j480: ["Let's sit in the [_____] of the bus.", "バスの前の方に座ろう。"],
  j481: ["[_____] is knocking on the door.", "だれかがドアをノックしています。"],
  j482: ["It was hard to [_____] between the two dresses.", "2着のドレスのどちらかを選ぶのは難しかった。"],
  j483: ["There is not enough [_____] for a bed in this room.", "この部屋にはベッドを置く空間が足りません。"],
  j484: ["[_____] the key to open the door.", "鍵を回してドアを開けなさい。"],
  j485: ["The school festival is a big [_____] for us.", "文化祭は私たちにとって大きな行事です。"],
  j486: ["This [_____] can clean the floor by itself.", "このロボットは自分で床を掃除できます。"],
  j487: ["Volunteer [_____] is popular among students.", "ボランティア活動は学生に人気があります。"],
  j488: ["Please [_____] down here.", "どうぞここに座ってください。"],
  j489: ["I [_____] a glass of milk every morning.", "私は毎朝コップ1杯の牛乳を飲みます。"],
  j490: ["My [_____] is eighty years old, and he still plays golf.", "祖父は80歳ですが、今でもゴルフをします。"],
  j491: ["Her [_____] at the contest was very good.", "コンテストでの彼女のスピーチはとてもよかった。"],
  j492: ["She loves to [_____] in the shower.", "彼女はシャワーを浴びながら歌うのが大好きです。"],
  j493: ["The [_____] told me to rest for a few days.", "医者は私に数日休むように言いました。"],
  j494: ["It has been raining [_____] last night.", "昨夜からずっと雨が降っています。"],
  j495: ["The bank is [_____] the post office and the hospital.", "銀行は郵便局と病院の間にあります。"],
  j496: ["I [_____] swim very well.", "私はあまり上手に泳げません。"],
  j497: ["The day after Sunday is [_____].", "日曜日の次の日は月曜日です。"],
  j498: ["[_____] comes between Monday and Wednesday.", "火曜日は月曜日と水曜日の間にあります。"],
  j499: ["[_____] is the middle of the work week.", "水曜日は平日の真ん中です。"],
  j500: ["[_____] comes after Wednesday.", "木曜日は水曜日の次に来ます。"],
  j501: ["[_____] is the last school day of the week.", "金曜日はその週の最後の登校日です。"],
  j502: ["We have no school on [_____] and Sunday.", "土曜日と日曜日は学校がありません。"],
  j503: ["The new year starts in [_____].", "新年は1月に始まります。"],
  j504: ["[_____] is the shortest month of the year.", "2月は1年で最も短い月です。"],
  j505: ["In Japan, the school year ends in [_____].", "日本では学年は3月に終わります。"],
  j506: ["Cherry blossoms bloom in [_____] in Tokyo.", "東京では4月に桜が咲きます。"],
  j507: ["It rains a lot in [_____] in Japan.", "日本では6月に雨がたくさん降ります。"],
  j508: ["Summer vacation starts in late [_____].", "夏休みは7月の終わりに始まります。"],
  j509: ["[_____] is the eighth month of the year.", "8月は1年の8番目の月です。"],
  j510: ["The second school term starts in [_____].", "2学期は9月に始まります。"],
  j511: ["Halloween is on the thirty-first of [_____].", "ハロウィーンは10月31日です。"],
  j512: ["[_____] comes after October.", "11月は10月の次に来ます。"],
  j513: ["Christmas is in [_____].", "クリスマスは12月にあります。"],
  j514: ["This bike costs thirty [_____] yen.", "この自転車は3万円です。"],
  j515: ["Draw a line under the key words with a red [_____].", "大事な語の下に赤いマーカーペンで線を引きなさい。"],
  j516: ["Draw a straight line with your [_____].", "定規でまっすぐな線を引きなさい。"],
  j517: ["I bought a new [_____] with eighty pages.", "80ページの新しいノートを買いました。"],
  j518: ["Please bring your science [_____] to class tomorrow.", "明日は理科の教科書を授業に持ってきてください。"],
  j519: ["She is in the third [_____] of junior high school.", "彼女は中学3年生です。"],
  j520: ["The final [_____] was three to one.", "最終得点は3対1でした。"],
  j521: ["The [_____] was stopped because of the heavy rain.", "大雨のため試合は中止されました。"],
  j522: ["Cows are eating grass in the [_____].", "牛が野原で草を食べています。"],
  j523: ["Fifty thousand fans came to the [_____] to watch the game.", "5万人のファンが試合を見にスタジアムに来ました。"],
  j524: ["The [_____] trains for four hours every day.", "その運動選手は毎日4時間練習します。"],
  j525: ["Our [_____] told us to run ten laps.", "コーチは私たちにグラウンドを10周走るように言いました。"],
  j526: ["Ken was chosen as [_____] of the soccer team.", "ケンはサッカー部の主将に選ばれました。"],
  j527: ["The [_____] blew the whistle to end the game.", "審判は笛を吹いて試合を終えました。"],
  j528: ["Please pour some water into this [_____].", "このコップに水を注いでください。"],
  j529: ["She painted the picture with a small [_____].", "彼女は小さな筆でその絵を描きました。"],
  j530: ["Wash your hands with [_____] and water.", "石鹸と水で手を洗いなさい。"],
  j531: ["Dry your face with this [_____].", "このタオルで顔をふきなさい。"],
  j532: ["I wash my hair with [_____] every night.", "私は毎晩シャンプーで髪を洗います。"],
  j533: ["Please open the [_____] and let the sunlight in.", "カーテンを開けて日光を入れてください。"],
  j534: ["There is a soft red [_____] on the living room floor.", "居間の床には柔らかい赤いじゅうたんが敷いてあります。"],
  j535: ["It's cold tonight, so I need another [_____] on my bed.", "今夜は寒いので、ベッドにもう1枚毛布が要ります。"],
  j536: ["She sat on a soft [_____] on the floor.", "彼女は床の上の柔らかいクッションに座りました。"],
  j537: ["My mother cut the [_____] for the salad.", "母はサラダ用にキャベツを切りました。"],
  j538: ["Put some [_____] and tomato in the sandwich.", "サンドイッチにレタスとトマトを入れてください。"],
  j539: ["We grow tomatoes and [_____]s in our garden.", "私たちは庭でトマトとキュウリを育てています。"],
  j540: ["This soup smells strongly of [_____].", "このスープはニンニクの強いにおいがします。"],
  j541: ["Popeye gets strong when he eats [_____].", "ポパイはホウレンソウを食べると強くなります。"],
  j542: ["Some [_____]s in the forest are poisonous.", "森のキノコの中には毒のあるものもあります。"],
  j543: ["Children carve faces into [_____]s for Halloween.", "子どもたちはハロウィーンのためにカボチャに顔を彫ります。"],
  j544: ["I like [_____] jam on my toast.", "私はトーストにイチゴジャムを塗るのが好きです。"],
  j545: ["This [_____] is soft, sweet, and pink.", "この桃はやわらかくて甘く、ピンク色です。"],
  j546: ["There is a red [_____] on top of the cake.", "ケーキの上に赤いサクランボがのっています。"],
  j547: ["This [_____] is very sour.", "このレモンはとてもすっぱい。"],
  j548: ["This [_____] is round, green, and very sweet inside.", "このメロンは丸くて緑色で、中はとても甘い。"],
  j549: ["We ate cold [_____] on the beach in summer.", "夏に浜辺で冷たいスイカを食べました。"],
  j550: ["This [_____] has a hard skin and sweet yellow fruit inside.", "このパイナップルは皮が硬く、中は甘くて黄色い。"],
  j551: ["We drank juice from a fresh [_____] on the island.", "私たちはその島で新鮮なココナッツのジュースを飲みました。"],
  j552: ["Look up the word in your [_____].", "その単語を辞書で調べなさい。"],
  j553: ["Please [_____] your name out loud, letter by letter.", "名前を1文字ずつ声に出してつづってください。"],
  j554: ["There is a spelling [_____] in this sentence.", "この文にはつづりの誤りがあります。"],
  j555: ["There are twenty-six letters in the English [_____].", "英語のアルファベットには26文字あります。"],
  j556: ["English [_____] is difficult for many students.", "英文法は多くの生徒にとって難しい。"],
  j557: ["Words like 'cat' and 'desk' are [_____]s.", "cat や desk のような語は名詞です。"],
  j558: ["'Run' and 'eat' are [_____]s.", "run や eat は動詞です。"],
  j559: ["Words like 'big' and 'happy' are [_____]s.", "big や happy のような語は形容詞です。"],
  j560: ["Words like 'quickly' and 'slowly' are [_____]s.", "quickly や slowly のような語は副詞です。"],
  j561: ["'He' and 'she' are [_____]s.", "he や she は代名詞です。"],
  j562: ["'In', 'on', and 'under' are [_____]s.", "in、on、under は前置詞です。"],
  j563: ["'And' and 'but' are [_____]s.", "and や but は接続詞です。"],
  j564: ["'Oh!' and 'Wow!' are [_____]s.", "Oh! や Wow! は間投詞です。"],
  j565: ["In a list, put [_____]s between the words, like 'red, blue, green'.", "語を並べるときは、red, blue, green のように語の間にカンマを置きます。"],
  j566: ["Read the first [_____] of the story aloud.", "物語の最初の文を声に出して読みなさい。"],
  j567: ["Draw a straight [_____] from A to B.", "AからBまでまっすぐな線を引きなさい。"],
  j568: ["She wrote a short [_____] about the sea.", "彼女は海についての短い詩を書きました。"],
  j569: ["Practice this [_____] with your partner: one of you is A, and the other is B.", "この対話をペアで練習しなさい。一人がA、もう一人がBです。"],
  j570: ["'Thank you very much' is a useful [_____].", "Thank you very much は便利な言い回しです。"],
  j571: ["'Break a leg' is an English [_____] meaning 'good luck'.", "Break a leg は、幸運を祈るという意味の英語の慣用句です。"],
  j572: ["He speaks English with a French [_____].", "彼はフランス語なまりの英語を話します。"],
  j573: ["She practiced every day to improve her [_____] in English.", "彼女は英語の流暢さを高めるために毎日練習しました。"],
  j574: ["Don't use [_____] in a formal letter.", "改まった手紙では俗語を使ってはいけません。"],
  j575: ["Poets often use [_____]s like 'as white as snow'.", "詩人は as white as snow のような直喩をよく使います。"],
  j576: ["Good [_____] between parents and children is important.", "親と子のよいコミュニケーションは大切です。"],
  j577: ["Our group's [_____] about recycling lasted ten minutes.", "リサイクルについての私たちのグループの発表は10分間でした。"],
  j578: ["I have a job [_____] tomorrow morning.", "私は明日の朝、就職の面接があります。"],
  j579: ["Please hand in your science [_____] by Friday.", "理科のレポートを金曜日までに提出してください。"],
  j580: ["She put the wedding photos in a new [_____].", "彼女は結婚式の写真を新しいアルバムに入れました。"],
  j581: ["The [_____] moved beautifully to the music.", "そのダンサーは音楽に合わせて美しく踊りました。"],
  j582: ["Do you believe in [_____]s?", "あなたは幽霊を信じますか。"],
  j583: ["My brother plays the [_____] in a rock band.", "兄はロックバンドでギターをひいています。"],
  j584: ["In the evening, your [_____] becomes very long.", "夕方になると、影がとても長くなります。"],
  j585: ["This [_____] to clean the river will take three years.", "川をきれいにするこのプロジェクトには3年かかります。"],
  j586: ["Please give him this [_____]: the meeting is at three.", "彼にこの伝言を伝えてください。会議は3時です。"],
  j587: ["This [_____] washes and dries clothes.", "この機械は服を洗って乾かします。"],
  j588: ["I like the [_____] of your new haircut.", "あなたの新しい髪型のスタイルが好きです。"],
  j589: ["Please don't use [_____] bags; bring your own bag.", "ビニール袋を使わず、自分のバッグを持ってきてください。"],
  j590: ["I found a hundred-yen [_____] on the street.", "道で100円玉を見つけました。"],
  j591: ["Her dress has a flower [_____].", "彼女のドレスには花の模様があります。"],
  j592: ["Wait for the green [_____] before you cross the street.", "道を渡る前に青信号を待ちなさい。"],
  j593: ["I have read every book in the Harry Potter [_____].", "ハリー・ポッターのシリーズの本はすべて読みました。"],
  j594: ["The [_____] went out during the storm, and the house became dark.", "嵐の間に停電して、家の中が暗くなりました。"],
  j595: ["It is hard to keep your [_____] on ice.", "氷の上でバランスを保つのは難しい。"],
  j596: ["A big [_____] knocked the surfer off his board.", "大きな波がサーファーをボードから落としました。"],
  j597: ["You need to learn the [_____] rules before you play the game.", "試合をする前に基本的なルールを学ぶ必要があります。"],
  j598: ["I love the [_____] of this new car.", "この新しい車のデザインが大好きです。"],
  j599: ["We buy vegetables from [_____] farmers.", "私たちは地元の農家から野菜を買います。"],
  j600: ["In [_____], boys are taller than girls at this age.", "一般的に、この年ごろでは男子のほうが女子より背が高い。"],
  j601: ["The music was so [_____] that I couldn't hear you.", "音楽がとても大きくて、あなたの声が聞こえませんでした。"],
  j602: ["I forgot my umbrella, so my clothes got [_____].", "傘を忘れたので、服がぬれてしまいました。"],
  j603: ["The boys and girls sleep in [_____] rooms on the school trip.", "修学旅行では、男子と女子は別々の部屋で寝ます。"],
  j604: ["My father loves [_____] rock music from the 1970s.", "父は1970年代の名作ロックが大好きです。"],
  j605: ["It is important to get [_____] exercise.", "定期的に運動することは大切です。"],
  j607: ["Many people now read [_____] books on their phones.", "今では多くの人がスマートフォンでデジタルの本を読みます。"],
  j608: ["Please don't ask me [_____] questions.", "私的な質問はしないでください。"],
  j609: ["Our team reached the [_____] round of the tournament.", "私たちのチームはトーナメントの決勝戦に進みました。"],
  j610: ["Nobody is [_____]; everyone makes mistakes.", "完ぺきな人はいません。誰でも間違いをします。"],
  j611: ["The [_____] cost of the trip was fifty thousand yen.", "旅行の費用の総計は5万円でした。"],
  j612: ["The river is very [_____] here, so we need a boat.", "ここは川幅がとても広いので、ボートが必要です。"],
  j613: ["Don't swim here. The water is too [_____].", "ここで泳いではいけません。水が深すぎます。"],
  j614: ["Small children can play safely in the [_____] end of the pool.", "小さな子どもはプールの浅い方で安全に遊べます。"],
  j615: ["I sat in the [_____] seat between my parents.", "私は両親の間の真ん中の席に座りました。"],
  j616: ["She played as an amateur for years before turning [_____].", "彼女は何年もアマチュアとしてプレーした後、プロになりました。"],
  j617: ["The two countries have many [_____] differences in food and customs.", "その2か国には、食べ物や習慣に多くの文化的な違いがあります。"],
  j618: ["The weather here is [_____] even in winter.", "ここの気候は冬でも穏やかです。"],
  j619: ["Lions and zebras are [_____] animals in Africa.", "ライオンやシマウマはアフリカの野生動物です。"],
  j620: ["The [_____] firefighter saved the child from the burning house.", "その勇敢な消防士は燃える家から子どもを助けました。"],
  j621: ["These shoes are not pretty, but they are very [_____].", "この靴はきれいではないけれど、とても実用的です。"],
  j622: ["His idea was very [_____]; nobody had thought of it before.", "彼の考えはとても独創的で、それまで誰も思いつかなかった。"],
  j623: ["My body temperature is [_____] now, so I can go to school.", "体温が平熱に戻ったので、学校へ行けます。"],
  a1_engineer: ["The [_____] designed this bridge.", "その技師がこの橋を設計しました。"],
  a1_super: ["The view from the top of the mountain was [_____]!", "山頂からの眺めはすばらしかった！"]
};
