import { SentenceRewrites } from "./types";

/**
 * 高校基礎の例文の書き直し。キーは単語ID、値は [例文, 和訳]。
 * 決まり・使い方は scripts/apply_sentences.ts を参照。
 */
export const senior: SentenceRewrites = {
  s2: ["You [_____] be hungry after such a long walk.", "あんなに長く歩いたのだから、お腹がすいているに違いない。"],
  s3: ["I wanted to go out. [_____], it was raining hard.", "出かけたかった。しかし、雨が激しく降っていた。"],
  s4: ["The cat came in [_____] the open window.", "猫は開いた窓を通って入ってきた。"],
  s5: ["There is a tall tree [_____] our school.", "学校の前に高い木があります。"],
  s6: ["What does this word [_____]?", "この単語はどういう意味ですか。"],
  s7: ["We use [_____] to show where something is, as in \"The bank is between the station and the park.\"", "「銀行は駅と公園の間にある」のように、ものの位置を表すときに使います。"],
  s8: ["How many [_____]s can you speak?", "あなたは何か国語を話せますか。"],
  s9: ["In [_____], he was the one who broke the window.", "実は、窓を割ったのは彼だった。"],
  s10: ["[_____] it was cold, we went swimming.", "寒かったけれど、私たちは泳ぎに行った。"],
  s11: ["Please wait here [_____] I come back.", "私が戻るまでここで待っていてください。"],
  s12: ["The Olympics are a big [_____] event with athletes from over 200 countries.", "オリンピックは200を超える国から選手が集まる大きな国際的行事だ。"],
  s14: ["The cat is hiding [_____] the sofa.", "猫はソファの後ろに隠れている。"],
  s15: ["About fourteen [_____] people live in Tokyo.", "東京には約1,400万人が住んでいる。"],
  s16: ["The test [_____]s will be posted on Friday.", "テストの結果は金曜日に掲示されます。"],
  s17: ["We don't have [_____] time to finish the work today.", "今日その仕事を終えるのに十分な時間がない。"],
  s18: ["At that [_____], the lights went out.", "その瞬間、明かりが消えた。"],
  s19: ["What is the [_____] from here to the station?", "ここから駅までの距離はどのくらいですか。"],
  s20: ["Is it [_____] to finish this by tomorrow?", "明日までにこれを終えることは可能ですか。"],
  s21: ["Have you [_____] eaten lunch? It's only eleven!", "もう昼食を食べたの？まだ11時だよ！"],
  s22: ["[_____] he was tired, he kept working.", "疲れていたけれど、彼は働き続けた。"],
  s23: ["Can you [_____] a good book for me to read?", "私が読むのによい本を薦めてもらえますか。"],
  s24: ["If you [_____] the two pictures, you will find five differences.", "2枚の絵を比べると、違いが5つ見つかります。"],
  s25: ["Prices keep rising. [_____], wages have stayed the same.", "物価は上がり続けている。一方で、賃金は変わっていない。"],
  s26: ["The baby is sleeping, so try not to [_____] her.", "赤ちゃんが寝ているので、邪魔をしないようにしてね。"],
  s27: ["I have called her [_____] times, but she never answers.", "彼女に何度も電話したが、一度も出ない。"],
  s28: ["Please explain your plan [_____] so that everyone understands it.", "みんなが理解できるように、計画を詳しく説明してください。"],
  s29: ["I'd love to come to your party, but [_____] I have to work that day.", "あなたのパーティーにぜひ行きたいのですが、残念ながらその日は仕事なんです。"],
  s30: ["Cars, buses, and trucks are all [_____]s.", "車、バス、トラックはすべて乗り物だ。"],
  s31: ["Washing your hands helps prevent [_____].", "手を洗うことは病気の予防に役立つ。"],
  s32: ["A smartphone is a small [_____] that can do many things.", "スマートフォンはいろいろなことができる小さな装置だ。"],
  s33: ["Please [_____] seated until the plane stops.", "飛行機が止まるまで座ったままでいてください。"],
  s34: ["Plastic bags are bad for the [_____] because they pollute the sea.", "ビニール袋は海を汚すので環境に悪い。"],
  s35: ["Have you seen any good movies [_____]?", "最近、何かいい映画を見ましたか。"],
  s36: ["[_____] cats, dogs love to go for walks.", "猫と違って、犬は散歩が大好きだ。"],
  s37: ["There is no easy [_____] to this problem.", "この問題に簡単な解決法はない。"],
  s38: ["Please [_____] me to buy milk on the way home.", "帰りに牛乳を買うのを忘れないよう、私に声をかけてください。"],
  s39: ["The police [_____]ed the man for stealing a car.", "警察は車を盗んだ罪でその男を逮捕した。"],
  s40: ["This machine can [_____] even a small amount of smoke.", "この機械はわずかな煙でも感知できる。"],
  s41: ["[_____] of the heavy rain, the game was canceled.", "大雨の結果、試合は中止になった。"],
  s42: ["This box [_____]s old letters from my grandfather.", "この箱には祖父からの古い手紙が入っている。"],
  s43: ["Large cars [_____] a lot of gas.", "大きな車はたくさんのガソリンを消費する。"],
  s44: ["Driving too fast can [_____] a serious accident.", "スピードの出しすぎは重大な事故につながりかねない。"],
  s45: ["My father can [_____] almost anything that breaks.", "父は壊れたものならほとんど何でも直せる。"],
  s46: ["The house was made [_____] of wood.", "その家は全部木でできていた。"],
  s47: ["We must [_____] the amount of garbage we throw away.", "私たちは捨てるごみの量を減らさなければならない。"],
  s48: ["Regular exercise has many health [_____]s.", "定期的な運動には健康上の利点がたくさんある。"],
  s49: ["Eating too much sugar can [_____] health problems.", "砂糖の取りすぎは健康上の問題につながりかねない。"],
  s50: ["Is there anything [_____] you would like to eat tonight?", "今夜特に食べたいものはありますか。"],
  s51: ["Tokyo is full of [_____] buildings made of glass and steel.", "東京はガラスと鋼鉄でできた近代的な建物でいっぱいだ。"],
  s52: ["The store gives a free gift to every [_____] who spends over 5,000 yen.", "その店は5,000円以上買い物をしたすべての客に景品を渡す。"],
  s53: ["It will snow tomorrow, [_____] the weather report.", "天気予報によると、明日は雪が降る。"],
  s54: ["Only [_____]s of this building can use the parking lot.", "この建物の住人だけが駐車場を使える。"],
  s55: ["Please [_____] your shoes before entering the room.", "部屋に入る前に靴を脱いでください。"],
  s56: ["The test was very hard. [_____], she got a perfect score.", "テストはとても難しかった。それにもかかわらず、彼女は満点を取った。"],
  s57: ["Beautiful beaches and warm weather make the island [_____] to tourists from all over the world.", "美しい浜辺と温暖な気候が、その島を世界中の観光客にとって魅力的なものにしている。"],
  s58: ["The yen is the [_____] of Japan.", "円は日本の通貨だ。"],
  s59: ["How should we [_____] this problem?", "この問題にどう対処すべきだろうか。"],
  s60: ["She is a student at Kyoto [_____].", "彼女は京都大学の学生だ。"],
  s61: ["[_____] to English, she speaks French and Chinese.", "英語に加えて、彼女はフランス語と中国語を話す。"],
  s62: ["Scientists have [_____]ed a new kind of fish in the deep sea.", "科学者たちは深海で新種の魚を発見した。"],
  s63: ["He [_____] lives here; he moved to Osaka last year.", "彼はもうここには住んでいない。去年大阪に引っ越した。"],
  s64: ["She got up early [_____] catch the first train.", "彼女は始発電車に乗るために早起きした。"],
  s65: ["You need your parents' [_____] to join the trip.", "その旅行に参加するには親の許可が必要です。"],
  s66: ["The new bridge is still under [_____].", "新しい橋はまだ建設中だ。"],
  s67: ["Let's [_____] a party for her birthday.", "彼女の誕生日にパーティーを企画しよう。"],
  s68: ["May I [_____] you to the station?", "駅までご一緒してもいいですか。"],
  s69: ["The [_____] of a house must be strong.", "家の土台は頑丈でなければならない。"],
  s70: ["My bag is [_____] to yours, but mine is a little bigger.", "私のかばんはあなたのに似ているが、私のほうが少し大きい。"],
  s71: ["The hotel will [_____] towels and soap for guests.", "ホテルは宿泊客にタオルと石けんを用意します。"],
  s72: ["Scientists did [_____]s on mice to test the new medicine.", "科学者たちは新薬を試すためにネズミで実験を行った。"],
  s73: ["This shop sells clothes of high [_____].", "この店は品質の高い服を売っている。"],
  s74: ["Clean up this [_____] before Mom gets home!", "お母さんが帰る前に、この散らかったのを片付けなさい！"],
  s75: ["I didn't plan it; I met her [_____].", "計画していたわけではなく、偶然彼女に会ったのです。"],
  s76: ["The teacher [_____]d the importance of reading every day.", "先生は毎日読書することの大切さを強調した。"],
  s77: ["[_____]s in the lab are testing a new kind of battery.", "研究室の科学者たちが新しい種類の電池を試験している。"],
  s78: ["The [_____] decided to raise taxes.", "政府は増税を決めた。"],
  s79: ["All birds have wings. A penguin is a bird. [_____], a penguin has wings.", "すべての鳥には翼がある。ペンギンは鳥である。それゆえ、ペンギンには翼がある。"],
  s80: ["Everyone in the [_____] helped clean the park.", "地域の皆が公園の掃除を手伝った。"],
  s81: ["This [_____] speaker is small enough to carry in your bag.", "この携帯用スピーカーはかばんに入れて持ち運べるほど小さい。"],
  s82: ["Experts [_____] that the project will cost ten million yen.", "専門家はその事業に1,000万円かかると見積もっている。"],
  s83: ["The rules of this game are too [_____] for small children.", "このゲームのルールは小さな子どもには複雑すぎる。"],
  s84: ["Okinawa has a warm [_____] all year round.", "沖縄は一年中温暖な気候だ。"],
  s85: ["Lack of sleep can [_____] your health.", "睡眠不足は健康に影響を与えることがある。"],
  s86: ["It is hard to [_____] when the next earthquake will happen.", "次の地震がいつ起こるかを予測するのは難しい。"],
  s87: ["My parents don't [_____] me to stay out late.", "両親は私が夜遅くまで出歩くのを許さない。"],
  s88: ["Please [_____] us of any changes to your address.", "住所に変更があればお知らせください。"],
  s89: ["The team needs a new [_____] to win the game.", "その試合に勝つために、チームには新しい作戦が必要だ。"],
  s90: ["Do you have any [_____] place in mind for our trip, or should I choose?", "旅行先に特に考えている場所はある？それとも私が決めようか？"],
  s91: ["Call an ambulance [_____]!", "すぐに救急車を呼んで！"],
  s92: ["My brothers always [_____] about which TV show to watch.", "兄弟はいつもどのテレビ番組を見るかで言い争う。"],
  s93: ["She has the [_____] to speak five languages.", "彼女は5か国語を話す能力を持っている。"],
  s94: ["We need to [_____] the old batteries with new ones.", "古い電池を新しいものと取り換える必要がある。"],
  s95: ["There was no coffee, so I drank tea [_____].", "コーヒーがなかったので、代わりに紅茶を飲んだ。"],
  s96: ["The company plans to [_____] a new kind of electric car.", "その会社は新しい種類の電気自動車を開発する予定だ。"],
  s97: ["The hotel was clean and comfortable. [_____], it was close to the station.", "そのホテルは清潔で快適だった。さらに、駅にも近かった。"],
  s98: ["We use [_____] to add a second, stronger point, as in \"She speaks not only English but also French.\"", "「彼女は英語だけでなくフランス語も話す」のように、2つ目のことを付け加えて強調するときに使います。"],
  s99: ["[_____] people are using smartphones to pay.", "スマートフォンで支払いをする人がますます増えている。"],
  s100: ["Please [_____] my idea before you decide.", "決める前に私の考えを検討してください。"],
  s101: ["Many young people are looking for full-time [_____].", "多くの若者が正規の雇用を探している。"],
  s102: ["Rent is our biggest monthly [_____].", "家賃は我が家の毎月最大の出費だ。"],
  s103: ["Smoking is bad for your health. [_____], it is expensive.", "喫煙は健康に悪い。さらに、お金もかかる。"],
  s104: ["Solar panels [_____] sunlight into electricity.", "太陽光パネルは日光を電気に変える。"],
  s105: ["Air [_____] is a serious problem in big cities.", "大気汚染は大都市の深刻な問題だ。"],
  s106: ["The [_____] of the internet changed our lives.", "インターネットの発達は私たちの生活を変えた。"],
  s107: ["If you don't sleep enough, you will [_____] catch a cold.", "十分に眠らないと、風邪をひきやすくなる。"],
  s108: ["Reading every day will [_____] your English.", "毎日読書をすれば英語が上達する。"],
  s109: ["The police found no [_____] that he was at the scene.", "警察は彼が現場にいたという証拠を見つけられなかった。"],
  s110: ["Tanaka is a very [_____] name in Japan.", "田中は日本ではとてもよくある名前だ。"],
  s111: ["Her first novel was [_____]ed when she was only nineteen.", "彼女の最初の小説は、彼女がわずか19歳のときに出版された。"],
  s112: ["She stayed home from school because she was [_____].", "彼女は具合が悪かったので学校を休んだ。"],
  s113: ["The company made a big [_____] this year.", "その会社は今年大きな利益を上げた。"],
  s114: ["It was [_____] hot yesterday, almost 40 degrees.", "昨日はものすごく暑く、40度近くあった。"],
  s115: ["City life is convenient. [_____], it can be noisy and crowded.", "都会の生活は便利だ。一方で、騒がしく混雑していることもある。"],
  s116: ["Many people [_____] hay fever in spring.", "春には多くの人が花粉症に悩まされる。"],
  s117: ["I would [_____] stay home than go out in this rain.", "こんな雨の中出かけるくらいなら、むしろ家にいたい。"],
  s118: ["He used all his savings to [_____] his friend's new company.", "彼は貯金をすべて使って友人の新しい会社に投資した。"],
  s119: ["If you work hard, you can [_____] your goals.", "一生懸命に努力すれば、目標を達成できる。"],
  s120: ["He walks so fast that I can't [_____] him.", "彼は歩くのがとても速いので、私はついていけない。"],
  s121: ["I tried to [_____] and catch the ball, but it was too far.", "手を伸ばしてボールを取ろうとしたが、遠すぎた。"],
  s122: ["Do you [_____] with your new classmates?", "新しいクラスメートとはうまくやっていますか。"],
  s123: ["The [_____] controls everything the body does.", "脳は体が行うすべてのことを制御している。"],
  s124: ["Many fruits are rich in vitamin C. Oranges, [_____], have a lot of it.", "多くの果物はビタミンCが豊富だ。たとえばオレンジにはたくさん含まれている。"],
  s125: ["Farmers should not use too many [_____]s on vegetables.", "農家は野菜に化学薬品を使いすぎるべきではない。"],
  s126: ["If you [_____] me, I will make school lunch better!", "私に投票してくれたら、給食をもっとおいしくします！"],
  s127: ["Summers here are hot. [_____], winters are very cold.", "ここの夏は暑い。対照的に、冬はとても寒い。"],
  s128: ["Can you [_____] Brazil on this map?", "この地図でブラジルの位置を見つけられますか。"],
  s129: ["I can't sleep because of the [_____] noise from the road.", "道路から絶え間なく聞こえる騒音のせいで眠れない。"],
  s130: ["This bird is very [_____]; only a few hundred are left in the world.", "この鳥はとても珍しく、世界に数百羽しか残っていない。"],
  s131: ["You should [_____] eating too much fast food.", "ファストフードの食べすぎは避けたほうがいい。"],
  s132: ["I can't [_____] people who are rude to waiters.", "店員に失礼な人には我慢ならない。"],
  s133: ["If you keep spending like that, you'll [_____] with no money.", "そんなにお金を使い続けると、最後には一文無しになるよ。"],
  s134: ["Prices went up [_____] last month, by only one percent.", "先月、物価はわずかに上がった。たった1パーセントだ。"],
  s135: ["No one can [_____] the ability to read; everyone has to learn it.", "読む力を生まれつき持っている人はいない。誰もが学ばなければならない。"],
  s136: ["The government took strong [_____]s to stop the virus from spreading.", "政府はウイルスの拡大を止めるために強力な措置を取った。"],
  s137: ["I'd like to walk [_____] take the bus.", "バスに乗るよりむしろ歩きたい。"],
  s138: ["Ms. Kato is [_____] the school library.", "加藤先生が学校図書館の担当だ。"],
  s139: ["Please pay [_____] to the teacher.", "先生の話に注意を払ってください。"],
  s140: ["I moved to Osaka five years ago and have lived there [_____].", "5年前に大阪に引っ越し、それ以来ずっとそこに住んでいる。"],
  s141: ["A strange man [_____]ed me on the street and asked for money.", "見知らぬ男が通りで私に近づいてきて、お金をせがんだ。"],
  s142: ["First, fill out this form. [_____], please attach a photo.", "まずこの用紙に記入してください。加えて、写真を貼ってください。"],
  s143: ["You must [_____] a visa before you travel to that country.", "その国に旅行する前にビザを取得しなければならない。"],
  s144: ["It took ten years to [_____] the old castle to its original beauty.", "その古い城を元の美しさに修復するのに10年かかった。"],
  s145: ["The country's goal is to end [_____] so that no child goes hungry.", "その国の目標は、子どもが誰も飢えることのないよう貧困をなくすことだ。"],
  s146: ["The French [_____] began in 1789.", "フランス革命は1789年に始まった。"],
  s147: ["If you know the answer, [_____] your hand.", "答えがわかったら手を挙げなさい。"],
  s148: ["The rules do not [_____] students to use phones in class.", "規則では授業中に生徒が電話を使うことは許可されていない。"],
  s149: ["You can [_____] tickets online.", "チケットはオンラインで購入できます。"],
  s150: ["Stretching every day will improve your [_____] so you can touch your toes.", "毎日ストレッチをすれば体の柔軟性が高まり、つま先に手が届くようになる。"],
  s151: ["The game was put off [_____] the rain.", "試合は雨のため延期された。"],
  s152: ["Rice [_____] in Japan has fallen in recent years.", "日本の米の生産量は近年減っている。"],
  s153: ["She didn't [_____] to my email.", "彼女は私のメールに返事をくれなかった。"],
  s154: ["I felt deep [_____] for the people who lost their homes in the flood.", "洪水で家を失った人々に深い同情を感じた。"],
  s155: ["She felt a lot of [_____] before the big exam.", "彼女は大事な試験の前にとても不安を感じた。"],
  s156: ["This old coin is very [_____]; it's worth a million yen.", "この古い硬貨はとても価値がある。100万円の値打ちがあるのだ。"],
  s157: ["I have a sharp [_____] in my back.", "背中に鋭い痛みがある。"],
  s158: ["The main [_____] of this phone is its camera.", "この電話の主な特徴はカメラだ。"],
  s159: ["You can always [_____] me when you're in trouble.", "困ったときはいつでも私を頼っていいよ。"],
  s160: ["Please don't [_____] me in front of my friends.", "友だちの前で恥ずかしい思いをさせないで。"],
  s161: ["That's [_____]! How did you think of that idea?", "すごい！どうやってそのアイデアを思いついたの？"],
  s162: ["This new heater is very [_____]; it uses little power but warms the whole room.", "この新しい暖房器具はとても効率がよく、わずかな電力で部屋全体を暖める。"],
  s163: ["We use [_____] to say that one thing stops another, as in \"The rain prevented us from going out.\"", "「雨のせいで私たちは外出できなかった」のように、何かが別のことを妨げることを表すときに使います。"],
  s164: ["Farmers put [_____] on their fields to help crops grow.", "農家は作物の成長を助けるために畑に肥料をまく。"],
  s165: ["Please [_____] a photo to your application form.", "申込書に写真を貼ってください。"],
  s166: ["She [_____]s a small hotel by the sea.", "彼女は海辺の小さなホテルを経営している。"],
  s167: ["Einstein's [_____] of relativity changed physics.", "アインシュタインの相対性理論は物理学を変えた。"],
  s168: ["Some animals, [_____] bears, sleep through the winter.", "動物の中には、たとえばクマのように、冬の間ずっと眠るものがいる。"],
  s169: ["We use [_____] to describe a change, as in \"Heat turns ice into water.\"", "「熱は氷を水に変える」のように、何かが別のものに変わることを表すときに使います。"],
  s170: ["This rule does not [_____] children under six.", "この規則は6歳未満の子どもには適用されない。"],
  s171: ["The two runners crossed the finish line [_____], so it was a tie.", "2人の走者が同時にゴールしたので、引き分けだった。"],
  s172: ["I'd like to thank you [_____] all the students.", "生徒全員を代表してお礼を申し上げます。"],
  s173: ["How much money do you [_____] on clothes each month?", "毎月服にいくらお金を使いますか。"],
  s174: ["She is doing [_____] on how sleep affects memory.", "彼女は睡眠が記憶にどう影響するかを研究している。"],
  s175: ["I like sweets [_____] cake and ice cream.", "私はケーキやアイスクリームのような甘いものが好きだ。"],
  s176: ["I can't [_____] which cake to choose.", "どのケーキにするか決められない。"],
  s177: ["This drink has no [_____] sweeteners; it only has natural sugar.", "この飲み物には人工甘味料は入っていない。入っているのは天然の砂糖だけだ。"],
  s178: ["I am writing [_____] your job advertisement in yesterday's newspaper.", "昨日の新聞の求人広告に応じて、お便りしています。"],
  s179: ["Please speak [_____] to the customers.", "お客様には丁寧に話してください。"],
  s180: ["The job will [_____] a lot of traveling.", "その仕事には出張がたくさん伴う。"],
  s181: ["Scientists [_____]d the water to find out what was in it.", "科学者たちは水に何が含まれているかを調べるため、その水を分析した。"],
  s182: ["I'm [_____] that I locked the door.", "ドアの鍵を閉めたのは確かだ。"],
  s183: ["You need climbing [_____], such as ropes and helmets, to go up that mountain.", "その山に登るには、ロープやヘルメットなどの登山用具が必要だ。"],
  s184: ["If you feel stressed all the time, talk to the school [_____].", "いつもストレスを感じているなら、学校の心理士に話してみなさい。"],
  s185: ["He always makes [_____]s for not doing his homework.", "彼はいつも宿題をしないことの言い訳をする。"],
  s186: ["She didn't say anything [_____] making him angry.", "彼を怒らせるのを恐れて、彼女は何も言わなかった。"],
  s187: ["Flour, eggs, and milk are the main [_____]s of pancakes.", "小麦粉、卵、牛乳がパンケーキの主な材料だ。"],
  s188: ["The town festival takes place [_____], so you'll have to wait until next year to see it again.", "町の祭りは年に一度なので、また見るには来年まで待たなければならない。"],
  s189: ["This table is [_____] wood.", "このテーブルは木でできている。"],
  s190: ["I bought this book on my teacher's [_____].", "先生の薦めでこの本を買った。"],
  s191: ["Can you [_____] this letter into Japanese?", "この手紙を日本語に翻訳してもらえますか。"],
  s192: ["Because of [_____], things fall to the ground.", "重力のせいで、物は地面に落ちる。"],
  s193: ["This shop sells [_____] fruits from all over the world.", "この店は世界中のさまざまな果物を売っている。"],
  s194: ["This street came to [_____] \"Book Town\" because of its many bookstores.", "この通りは書店が多いため、「本の町」として知られるようになった。"],
  s195: ["It was a long [_____] from Tokyo to London.", "東京からロンドンまでは長い旅だった。"],
  s196: ["There is a growing [_____] for electric cars.", "電気自動車の需要が高まっている。"],
  s197: ["Freedom of [_____] means you can believe in any god you like.", "信教の自由とは、どんな神を信じてもよいということだ。"],
  s198: ["It will [_____] rain tomorrow, so take an umbrella.", "明日はたぶん雨が降るので、傘を持っていきなさい。"],
  s199: ["The [_____] of time you spend on your phone each day is too much.", "あなたが毎日スマホに使う時間の量は多すぎる。"],
  s200: ["The old temple is well [_____].", "その古い寺はよく保存されている。"],
  s201: ["The heavy snow [_____]ed us from going out.", "大雪のせいで私たちは外出できなかった。"],
  s202: ["She is [_____]; she speaks both English and Japanese perfectly.", "彼女はバイリンガルで、英語と日本語の両方を完璧に話す。"],
  s203: ["The [_____] cost of the trip was 200,000 yen, including hotels and flights.", "旅行の費用は、ホテルと飛行機を含めて全部で20万円だった。"],
  s204: ["Don't just [_____] the screen without blinking; your eyes will get tired.", "まばたきもせずに画面をじっと見つめないで。目が疲れるよ。"],
  s205: ["Our school decided to [_____] a new teaching method.", "私たちの学校は新しい教授法を取り入れることにした。"],
  s206: ["The number of children in Japan continues to [_____].", "日本の子どもの数は減り続けている。"],
  s207: ["The police asked every [_____] what they saw.", "警察は目撃者一人ひとりに何を見たかを尋ねた。"],
  s208: ["Please [_____] the door is locked before you leave.", "出かける前にドアに鍵がかかっているか確かめてください。"],
  s209: ["Trains are [_____] on this line, so you never wait more than five minutes.", "この路線は電車の本数が多いので、5分以上待つことはない。"],
  s210: ["Nothing can [_____] her; she always complains.", "何をしても彼女は満足しない。いつも文句を言っている。"],
  s211: ["I have the [_____] set of Harry Potter books, all seven of them.", "私は『ハリー・ポッター』の本を全7巻そろえて持っている。"],
  s212: ["Anyone can [_____] the city marathon; just sign up online.", "誰でも市民マラソンに参加できる。オンラインで申し込むだけだ。"],
  s213: ["As I [_____] mentioned, the meeting will start at three.", "先ほど述べたとおり、会議は3時に始まります。"],
  s214: ["Don't [_____] your time playing video games all day.", "一日中テレビゲームをして時間を無駄にしてはいけない。"],
  s215: ["The weather forecast was [_____]; it rained exactly when they said it would.", "天気予報は正確で、予報どおりの時間に雨が降った。"],
  s216: ["Your salary will be paid into your [_____].", "給料はあなたの銀行口座に振り込まれます。"],
  s217: ["Can you [_____] this photo so I can see the faces better?", "顔がもっとよく見えるように、この写真を引き伸ばしてもらえますか。"],
  s218: ["This book is [_____] at any bookstore.", "この本はどこの書店でも手に入る。"],
  s219: ["I didn't do it on purpose; I deleted the file [_____].", "わざとではなく、うっかりファイルを消してしまったのです。"],
  s220: ["The town plans to [_____] the number of buses.", "町はバスの本数を増やす予定だ。"],
  s221: ["I have a dentist [_____] at three o'clock.", "3時に歯医者の予約がある。"],
  s222: ["Both of my sisters [_____] our mother; they have the same eyes.", "私の姉妹は2人とも母に似ていて、同じ目をしている。"],
  s223: ["I hope to [_____] you soon.", "近いうちにお便りをいただけるのを楽しみにしています。"],
  s224: ["According to government [_____], the population is falling.", "政府の統計によると、人口は減っている。"],
  s225: ["Nurses are always [_____], so it's easy for them to find jobs.", "看護師は常に需要があるので、仕事を見つけやすい。"],
  s226: ["We must win this game [_____].", "何がなんでもこの試合に勝たなければならない。"],
  s227: ["My grandfather has poor [_____], so he reads with a magnifying glass.", "祖父は視力が弱いので、虫眼鏡で本を読む。"],
  s228: ["They live in [_____] in a huge house with a pool.", "彼らはプール付きの巨大な家で贅沢に暮らしている。"],
  s229: ["She has a positive [_____] toward life.", "彼女は人生に対して前向きな態度を持っている。"],
  s230: ["Many health problems are [_____] stress.", "多くの健康問題はストレスと関係がある。"],
  s231: ["After the [_____], they didn't speak to each other for a week.", "口論のあと、2人は1週間口をきかなかった。"],
  s232: ["This new medicine may [_____] your ability to drive.", "この新しい薬は運転する能力に影響を与えることがある。"],
  s233: ["This sofa is so [_____] that I fell asleep on it.", "このソファはとても座り心地がよく、その上で寝てしまった。"],
  s234: ["\"Can you help me?\" \"[_____]! What do you need?\"", "「手伝ってもらえる？」「もちろん！何が必要？」"],
  s235: ["Beethoven was a German [_____].", "ベートーベンはドイツの作曲家だった。"],
  s236: ["My best friend and I have a lot [_____].", "親友と私には共通点がたくさんある。"],
  s237: ["Many people [_____] the words desert and dessert.", "多くの人が desert と dessert という単語を混同する。"],
  s238: ["My sister will [_____] from high school next spring.", "姉は来年の春に高校を卒業する。"],
  s239: ["The store gave me a free [_____] for the broken toaster.", "店は壊れたトースターの代わりの品を無料でくれた。"],
  s240: ["Don't let his kind words [_____] you; he only wants your money.", "彼の優しい言葉にだまされてはいけない。彼が欲しいのはあなたのお金だけだ。"],
  s241: ["Dinner will be ready in an hour. [_____], why don't you take a bath?", "夕食は1時間後にできるよ。それまでの間にお風呂に入ったら？"],
  s242: ["I trusted him completely, but he [_____]ed me and told everyone my secret.", "私は彼を信頼しきっていたが、彼は私を裏切って秘密をみんなに話した。"],
  s243: ["Kyoto has many [_____] temples and shrines.", "京都には由緒ある寺や神社がたくさんある。"],
  s244: ["We gave him a watch on the [_____] of his retirement.", "私たちは彼の退職に際して腕時計を贈った。"],
  s245: ["I saw my [_____] in the window.", "窓に映った自分の姿が見えた。"],
  s246: ["My grandfather was born in 1950. Most homes didn't have a TV [_____].", "祖父は1950年に生まれた。当時はほとんどの家にテレビがなかった。"],
  s247: ["The children [_____]d very well at the party.", "子どもたちはパーティーでとても行儀よくしていた。"],
  s248: ["[_____], I hope to visit Egypt and see the pyramids.", "いつかエジプトを訪れてピラミッドを見たい。"],
  s249: ["My job at the shop is [_____]; it ends in August.", "店での仕事は臨時のもので、8月に終わる。"],
  s250: ["I twisted my [_____] while playing soccer.", "サッカーをしていて足首をひねった。"],
  s251: ["My grandmother is still very [_____]; she walks five kilometers every day.", "祖母は今でもとても活動的で、毎日5キロ歩いている。"],
  s252: ["Read the [_____] on page 20 and answer the questions.", "20ページの一節を読んで質問に答えなさい。"],
  s253: ["The news quickly [_____] around the school.", "その知らせはあっという間に学校中に広まった。"],
  s254: ["She [_____]d the flowers in a vase.", "彼女は花を花瓶に生けた。"],
  s255: ["The population has doubled over the past [_____].", "人口はこの10年で2倍になった。"],
  s256: ["The [_____] of ice on the roads makes driving dangerous.", "道路に氷ができると運転が危険になる。"],
  s257: ["Japan's [_____] grew rapidly in the 1960s.", "日本の経済は1960年代に急速に成長した。"],
  s258: ["This is [_____]! Please call me back right away.", "緊急なんです！すぐに折り返し電話をください。"],
  s259: ["The court found him [_____] stealing the money.", "裁判所は彼がその金を盗んだ罪で有罪だと判断した。"],
  s260: ["It's 35 [_____]s outside today.", "今日は外の気温が35度ある。"],
  s261: ["More people are buying [_____] cars these days.", "最近は電気自動車を買う人が増えている。"],
  s262: ["Write the address on the [_____] and put a stamp on it.", "封筒に住所を書いて切手を貼りなさい。"],
  s263: ["I [_____]ed 10,000 yen in my bank account.", "私は銀行口座に1万円を預けた。"],
  s264: ["Garbage [_____] is a big problem in large cities.", "ごみの処分は大都市の大きな問題だ。"],
  s265: ["Choose the [_____] of two evils.", "2つの悪のうち、小さいほうを選べ。"],
  s266: ["I'll lend you my bike on one [_____]: bring it back by Sunday.", "1つ条件付きで自転車を貸してあげる。日曜日までに返すこと。"],
  s267: ["Solar panels make [_____] from sunlight.", "太陽光パネルは日光から電気を作る。"],
  s268: ["Swimming is good for both your [_____] and mental health.", "水泳は体と心の両方の健康によい。"],
  s269: ["According to a recent [_____], most students sleep less than seven hours.", "最近の調査によると、ほとんどの生徒は睡眠時間が7時間未満だ。"],
  s270: ["Chew your food [_____] before you swallow it.", "飲み込む前に食べ物をよくかみなさい。"],
  s271: ["Can you play any musical [_____]s?", "何か楽器を演奏できますか。"],
  s272: ["Doctors said his cancer was [_____], so he spent his last months at home.", "医師たちは彼のがんは末期だと言ったので、彼は最後の数か月を自宅で過ごした。"],
  s273: ["The singer went on a tour to [_____] her new album.", "その歌手は新しいアルバムを売り込むためにツアーに出た。"],
  s274: ["She has a lot of stress at work and finds it hard to [_____] it.", "彼女は仕事でストレスが多く、それにうまく対処するのが難しい。"],
  s275: ["\"Have you finished your homework?\" \"[_____]. I'll do it after dinner.\"", "「宿題は終わった？」「まだだよ。夕食のあとでやる。」"],
  s276: ["I was so tired that I could [_____] keep my eyes open.", "とても疲れていて、目を開けているのがやっとだった。"],
  s277: ["Parrots can [_____] human voices.", "オウムは人間の声をまねることができる。"],
  s278: ["Sight, hearing, taste, smell, and touch are the [_____].", "視覚・聴覚・味覚・嗅覚・触覚が五感だ。"],
  s279: ["Expensive things are [_____] good.", "高いものが必ずしもよいとは限らない。"],
  s280: ["Many strange [_____]s live at the bottom of the sea.", "海の底には奇妙な生き物がたくさんすんでいる。"],
  s281: ["Japanese citizens can [_____] at the age of 18.", "日本国民は18歳で投票できる。"],
  s282: ["Her bright red dress made her [_____] in the crowd.", "明るい赤のドレスのおかげで、彼女は人混みの中で目立った。"],
  s283: ["This factory [_____]s 500 cars a day.", "この工場は1日に500台の車を生産している。"],
  s284: ["This museum is [_____] visiting.", "この博物館は訪れる価値がある。"],
  s285: ["Mom will [_____] driving you to the station, even if you say no.", "お母さんは、あなたが断っても、駅まで車で送ると言い張るでしょう。"],
  s287: ["Many people [_____] going to the dentist.", "多くの人が歯医者に行くのを恐れる。"],
  s288: ["The people of this town had to [_____] a long, hard winter without electricity.", "この町の人々は、電気のない長く厳しい冬に耐えなければならなかった。"],
  s289: ["It was very [_____] of you to pay for everyone's lunch.", "みんなの昼食代を払ってくれるなんて、とても気前がいいですね。"],
  s290: ["She sent a letter of complaint, and [_____], the company gave her a full refund.", "彼女が苦情の手紙を送ると、それに応じて会社は全額を返金した。"],
  s291: ["Don't be [_____] to animals.", "動物に残酷なことをしてはいけない。"],
  s292: ["This bottle contains a dangerous [_____], so don't touch it.", "この瓶には危険な物質が入っているので、触ってはいけない。"],
  s293: ["I studied hard, so I feel [_____] about tomorrow's test.", "一生懸命勉強したので、明日のテストには自信がある。"],
  s295: ["This car is [_____] going 200 kilometers an hour.", "この車は時速200キロで走ることができる。"],
  s296: ["I like all fruit, but I [_____] like peaches.", "果物は何でも好きだが、特に桃が好きだ。"],
  s297: ["I don't like the [_____] of this medicine.", "この薬の味は好きではない。"],
  s298: ["In some cultures, people don't want to [_____] by making mistakes in public.", "人前で間違えて面子を失うことを嫌う文化もある。"],
  s299: ["Someday you will have to [_____] what you have done.", "いつかあなたは自分のしたことの責任を取らなければならない。"],
  s300: ["This school was [_____]ed in 1900.", "この学校は1900年に設立された。"],
  s301: ["\"You must be tired.\" \"[_____], I feel great!\"", "「疲れているでしょう」「それどころか、絶好調だよ！」"],
  s302: ["Did you [_____] my email?", "私のメールを受け取りましたか。"],
  s303: ["This medicine has no side [_____]s.", "この薬には副作用がない。"],
  s304: ["It's raining. Don't forget your [_____].", "雨が降っているよ。傘を忘れないでね。"],
  s305: ["Please [_____] these glasses with care.", "このグラスは丁寧に扱ってください。"],
  s306: ["We bought new [_____] for the living room, including a sofa and a table.", "私たちは居間用にソファとテーブルを含む新しい家具を買った。"],
  s307: ["Use sunscreen to protect your [_____] from the sun.", "日焼け止めを使って肌を日光から守りなさい。"],
  s309: ["It is difficult for small children to understand the [_____] of money.", "幼い子どもにはお金という概念を理解するのが難しい。"],
  s310: ["I agree with you [_____], but not completely.", "ある程度はあなたに賛成だが、完全にではない。"],
  s311: ["Smoking is a major [_____] of cancer.", "喫煙はがんの主な原因だ。"],
  s312: ["We [_____]d our parents' 20th wedding anniversary.", "私たちは両親の結婚20周年を祝った。"],
  s313: ["Leaves were floating on the [_____] of the pond.", "池の水面に葉が浮かんでいた。"],
  s314: ["We have [_____] food for three days.", "3日分の十分な食料がある。"],
  s315: ["Crops can [_____] bad weather, so prices may rise.", "作物は悪天候の影響を受けることがあるので、値段が上がるかもしれない。"],
  s316: ["Let's keep [_____] after you move to Canada.", "カナダに引っ越しても連絡を取り合おうね。"],
  s317: ["The snow will [_____] when the sun comes out.", "日が出れば雪は溶けるだろう。"],
  s318: ["You need to buy tickets a week [_____].", "チケットは1週間前に買う必要がある。"],
  s319: ["The teacher [_____]ed the boys for fighting.", "先生はけんかをした少年たちを罰した。"],
  s320: ["The teacher gave us a reading [_____] for the weekend.", "先生は週末の課題として読書を出した。"],
  s321: ["He [_____]s from headaches every morning.", "彼は毎朝頭痛に苦しんでいる。"],
  s322: ["I [_____] at the gym three times a week.", "私は週に3回ジムで運動する。"],
  s323: ["[_____] the rain, the game continued.", "雨にもかかわらず、試合は続けられた。"],
  s324: ["I missed the bus, but [_____], my friend gave me a ride.", "バスに乗り遅れたが、幸いにも友人が車で送ってくれた。"],
  s325: ["Please accept my [_____] for being late.", "遅れたことをお詫びします。"],
  s326: ["Hawaii is a popular [_____] for Japanese tourists.", "ハワイは日本人観光客に人気の行き先だ。"],
  s327: ["There are three [_____]s in the election for mayor.", "市長選挙には3人の候補者がいる。"],
  s328: ["After waiting for two hours, the bus came [_____].", "2時間待って、やっとバスが来た。"],
  s329: ["His rude joke was very [_____] to many people in the audience.", "彼の失礼な冗談は、観客の多くにとってとても不快なものだった。"],
  s330: ["There was a big [_____] after our team won the championship.", "私たちのチームが優勝したあと、盛大なお祝いがあった。"],
  s331: ["She [_____]ed something in my ear.", "彼女は私の耳元で何かをささやいた。"],
  s332: ["I don't eat fast food often, but I have a hamburger [_____].", "ファストフードはあまり食べないが、時々ハンバーガーを食べる。"],
  s333: ["If neither of you will give in, there can be no [_____].", "どちらも譲らないなら、妥協はありえない。"],
  s334: ["I accidentally [_____]d all my photos.", "うっかり写真を全部消してしまった。"],
  s335: ["The blue whale is [_____]; it can be 30 meters long.", "シロナガスクジラは巨大で、体長30メートルになることもある。"],
  s336: ["This train goes [_____] to the airport without stopping.", "この電車は途中で止まらずに空港まで直行する。"],
  s337: ["Is this dress [_____] to wear at a funeral?", "このドレスはお葬式に着ていくのにふさわしいですか。"],
  s338: ["Take a deep [_____] and relax.", "深呼吸してリラックスして。"],
  s339: ["Our [_____] next door has a big dog.", "隣の家の人は大きな犬を飼っている。"],
  s340: ["Did he [_____] where he was going?", "彼はどこへ行くか言っていましたか。"],
  s341: ["Someone called [_____] you were out.", "あなたが外出している間に、誰かから電話があった。"],
  s342: ["I love summer, [_____] the long holidays.", "私は夏が大好きで、特に長い休みが好きだ。"],
  s343: ["Can you [_____] how old I am?", "私が何歳か当ててみて。"],
  s344: ["We were walking in the park when it [_____] started to rain.", "公園を歩いていると、突然雨が降り始めた。"],
  s345: ["I [_____]ed three kilograms during the holidays.", "休みの間に3キロ太った。"],
  s346: ["I have been to Kyoto [_____] times.", "私は京都に何度か行ったことがある。"],
  s347: ["Once you've had measles, you are [_____] to it for life.", "一度はしかにかかると、一生免疫ができる。"],
  s348: ["After the party, the room was in complete [_____].", "パーティーのあと、部屋はひどく散らかっていた。"],
  s349: ["Stress can affect your [_____] health.", "ストレスは心の健康に影響を与えることがある。"],
  s350: ["I [_____] study abroad after high school.", "私は高校卒業後に留学するつもりだ。"],
  s351: ["[_____], we have no plans to open a new store.", "現在のところ、新しい店を開く予定はありません。"],
  s352: ["Even small actions can [_____] in the fight against climate change.", "小さな行動でも、気候変動との闘いには違いを生む。"],
  s353: ["Studying abroad is a great [_____] to learn about other cultures.", "留学は他の文化について学ぶ絶好の機会だ。"],
  s354: ["He broke the window [_____]; it wasn't an accident.", "彼はわざと窓を割った。事故ではなかったのだ。"],
  s355: ["No food is allowed in the library, but [_____], water is permitted.", "図書館では飲食禁止だが、例外的に水は許されている。"],
  s357: ["This sweet smell is [_____] of the flower.", "この甘い香りはその花に特有のものだ。"],
  s358: ["Your idea is [_____] mine.", "あなたの考えは私のと似ている。"],
  s359: ["There was some doubt [_____] whether he would come.", "彼が来るかどうかについては、いくらか疑問があった。"],
  s360: ["Ancient Egypt was one of the first great [_____]s.", "古代エジプトは最初の偉大な文明の一つだった。"],
  s361: ["The red lines on the map [_____] railways.", "地図の赤い線は鉄道を表している。"],
  s362: ["Many buildings [_____]d in the earthquake.", "地震で多くの建物が倒壊した。"],
  s363: ["He [_____]ed me by calling me stupid.", "彼は私をばかと呼んで侮辱した。"],
  s364: ["Make the cake by pouring the [_____] of flour, eggs, and sugar into a pan.", "小麦粉と卵と砂糖を混ぜたものを型に流し込んでケーキを作りなさい。"],
  s365: ["The village is [_____]; the nearest town is 50 kilometers away.", "その村は孤立していて、最寄りの町まで50キロある。"],
  s366: ["Please be [_____]; the bus will leave at exactly eight.", "時間を守ってください。バスはちょうど8時に出発します。"],
  s367: ["Who is [_____] for cleaning the classroom today?", "今日教室の掃除の責任者は誰ですか。"],
  s368: ["The little boy was [_____] of the big dog.", "その小さな男の子は大きな犬を怖がっていた。"],
  s369: ["This watch is [_____]d for two years.", "この腕時計には2年間の保証がついている。"],
  s370: ["Don't [_____] me for your mistake!", "あなたの失敗を私のせいにしないで！"],
  s371: ["Today is our tenth wedding [_____].", "今日は私たちの結婚10周年記念日だ。"],
  s372: ["Anyone who [_____]s the rules will be asked to leave.", "規則に違反した人には退場してもらいます。"],
  s373: ["The heavy snow [_____]ed the trains.", "大雪で電車が遅れた。"],
  s374: ["The house is [_____]ed by tall trees.", "その家は高い木々に囲まれている。"],
  s375: ["Her family [_____]d to the United States from Mexico.", "彼女の家族はメキシコからアメリカに移住した。"],
  s376: ["Is this the [_____] answer?", "これが正しい答えですか。"],
  s377: ["The mountain [_____] here is beautiful in autumn.", "ここの山の風景は秋になると美しい。"],
  s378: ["My [_____] told me not to trust him.", "直感が、彼を信用するなと私に告げた。"],
  s379: ["The government changed its energy [_____].", "政府はエネルギー政策を変えた。"],
  s380: ["He kept yawning all day; [_____] he hadn't slept well.", "彼は一日中あくびをしていた。明らかによく眠れていなかったのだ。"],
  s381: ["[_____], nobody heard the alarm.", "不思議なことに、誰も警報を聞いていなかった。"],
  s382: ["The dog [_____]d the cat up a tree.", "犬は猫を木の上まで追いかけた。"],
  s383: ["Could you [_____] me a glass of water?", "水を1杯ついでもらえますか。"],
  s384: ["Don't put too much food in your mouth [_____].", "一度にたくさんの食べ物を口に入れてはいけない。"],
  s385: ["My grandparents came [_____] from Hokkaido to see my play.", "祖父母は私の劇を見るためにはるばる北海道から来てくれた。"],
  s386: ["I waited for an hour, but he didn't [_____].", "1時間待ったが、彼は現れなかった。"],
  s387: ["The train began to [_____] from the station.", "電車は駅から離れ始めた。"],
  s388: ["Can I [_____] this new bike before I buy it?", "買う前にこの新しい自転車を試してもいいですか。"],
  s389: ["A thief tried to [_____] our house last night.", "昨夜、泥棒が私たちの家に押し入ろうとした。"],
  s390: ["We've done enough work. Let's [_____].", "もう十分働いた。今日はここまでにしよう。"],
  s391: ["I'll try to [_____] when you get home tonight.", "今夜あなたが帰ってくるときは起きているようにするね。"],
  s392: ["Climate change is a serious global [_____].", "気候変動は深刻な地球規模の問題だ。"],
  s393: ["Please give your seat to [_____] people on the train.", "電車では年配の人に席を譲ってください。"],
  s394: ["You can change the [_____] of your phone screen.", "スマホの画面の明るさは変えられる。"],
  s395: ["Music can [_____] your mood.", "音楽は気分に影響を及ぼすことがある。"],
  s396: ["When it rains, we play in the [_____] pool.", "雨の日は屋内プールで遊ぶ。"],
  s397: ["My sister is three years [_____] to me.", "姉は私より3歳年上だ。"],
  s398: ["It's [_____] to feel nervous before a test.", "テストの前に緊張するのは当然のことだ。"],
  s399: ["The height of this chair can [_____] fit any child.", "このいすの高さはどの子どもにも合うように調節できる。"],
  s400: ["Do you have any [_____] questions, or just general ones?", "具体的な質問はありますか、それとも一般的な質問だけですか。"],
  s401: ["Running makes your [_____] go up.", "走ると心拍数が上がる。"],
  s402: ["Getting enough sleep will [_____] both your body and mind.", "十分な睡眠は体と心の両方に有益だ。"],
  s403: ["He is [_____] a walking dictionary.", "彼はいわゆる生き字引だ。"],
  s404: ["A butterfly's wings show perfect [_____]: the left side matches the right.", "チョウの羽は完全な左右対称で、左側と右側が一致している。"],
  s405: ["The two girls looked at [_____] and laughed.", "2人の少女は顔を見合わせて笑った。"],
  s406: ["Being tall is a big [_____] in basketball.", "背が高いことはバスケットボールで大きな利点だ。"],
  s407: ["I fell and hurt my [_____].", "転んで膝をけがした。"],
  s408: ["Please [_____] mistakes before you hand in your test.", "テストを提出する前に間違いがないか確認してください。"],
  s409: ["I thought I would fail, but I passed [_____].", "落ちると思っていたが、結局合格した。"],
  s410: ["Don't worry. Your English will improve [_____].", "心配しないで。英語の力は時間とともに伸びていくよ。"],
  s411: ["The room was small and dirty. [_____], it was very expensive.", "その部屋は狭くて汚かった。そのうえ、とても高かった。"],
  s412: ["I haven't seen him [_____].", "しばらく彼に会っていない。"],
  s413: ["Please come in one [_____].", "1人ずつ入ってください。"],
  s414: ["I left my car in the [_____] behind the store.", "店の裏の駐車場に車を置いてきた。"],
  s415: ["This song is popular [_____].", "この歌は世界中で人気がある。"],
  s416: ["The writer owns the [_____] to her books, so you can't copy them without permission.", "その作家は自分の本の著作権を持っているので、許可なく複製することはできない。"],
  s417: ["There is no [_____] for children under six.", "6歳未満の子どもは料金がかからない。"],
  s418: ["The film [_____] chose the actors and told them how to act.", "映画監督が俳優を選び、演技の仕方を指示した。"],
  s419: ["He looks young, but [_____] he is over sixty.", "彼は若く見えるが、実際は60歳を超えている。"],
  s420: ["She looks strict, but she is [_____] very kind.", "彼女は厳しそうに見えるが、実際はとても優しい。"],
  s421: ["Mozart began to [_____] music when he was five.", "モーツァルトは5歳で作曲を始めた。"],
  s422: ["Our dog runs to the door to [_____] us when we come home.", "家に帰ると、犬が玄関まで走って出迎えてくれる。"],
  s423: ["Children [_____] their parents for food and clothes.", "子どもは食べ物や服を親に頼っている。"],
  s424: ["In \"She claims to speak five languages,\" the pattern [_____] shows that she says so, but it may not be true.", "「彼女は5か国語を話せると言っている」の文では、この形が「本人はそう言っているが本当かはわからない」ことを表す。"],
  s425: ["I [_____] you; it's a great idea.", "あなたに賛成です。素晴らしい考えだ。"],
  s426: ["In Tokyo, [_____] many different languages on the trains.", "東京では、電車の中でさまざまな言語を耳にするのはよくあることだ。"],
  s428: ["Mount Fuji is a World [_____] Site.", "富士山は世界遺産だ。"],
  s429: ["I want to study [_____] when I go to college.", "大学生になったら留学したい。"],
  s430: ["The [_____] of Japan is about 120 million.", "日本の人口は約1億2,000万人だ。"],
  s431: ["Please [_____] your lunch to the picnic tomorrow.", "明日のピクニックにはお弁当を持ってきてください。"],
  s432: ["Global warming is a serious [_____] problem.", "地球温暖化は深刻な環境問題だ。"],
  s433: ["Don't [_____] food just because it looks a little ugly.", "少し見た目が悪いからといって食べ物を捨ててはいけない。"],
  s434: ["Please take out the [_____] on Monday morning.", "月曜日の朝にごみを出してください。"],
  s435: ["We need to [_____] a new plan by Friday.", "金曜日までに新しい計画を考え出す必要がある。"],
  s436: ["These bags are [_____] friendly because they can be used again and again.", "これらの袋は何度も使えるので環境に優しい。"],
  s437: ["The city [_____] decided to build a new library.", "市議会は新しい図書館を建てることを決めた。"],
  s438: ["The scientists will [_____] an experiment next week.", "科学者たちは来週実験を行う予定だ。"],
  s439: ["The car ran out of [_____] on the highway.", "車は高速道路で燃料切れになった。"],
  s440: ["Learning a language is a slow [_____].", "言語を学ぶのはゆっくりとした過程だ。"],
  s441: ["This car can carry [_____] seven people.", "この車は7人まで乗れる。"],
  s442: ["Caterpillars [_____] butterflies.", "イモムシはチョウに変わる。"],
  s443: ["My doctor told me to [_____] salt.", "医者に塩分を控えるように言われた。"],
  s444: ["Coal and oil are [_____]s.", "石炭と石油は化石燃料だ。"],
  s445: ["Many cities [_____] smoking on the street.", "多くの都市が路上での喫煙を禁止している。"],
  s446: ["She was [_____] about her son, who hadn't come home yet.", "彼女はまだ帰宅していない息子のことを心配していた。"],
  s447: ["Please [_____] the animals kindly.", "動物を優しく扱ってください。"],
  s448: ["The [_____] for the report is next Friday.", "レポートの締め切りは来週の金曜日だ。"],
  s449: ["The stadium will [_____] fans on Saturday.", "土曜日、スタジアムはファンでいっぱいになるだろう。"],
  s450: ["Everyone came to the party with the [_____] of Ken.", "健を除いて全員がパーティーに来た。"],
  s451: ["The reasons for the accident were many and [_____].", "その事故の原因は多く、さまざまだった。"],
  s452: ["Turn off the TV and [_____] your homework.", "テレビを消して宿題に集中しなさい。"],
  s453: ["The school [_____]s the use of phones to lunchtime.", "その学校は電話を使えるのを昼休みに限っている。"],
  s454: ["[_____] people came to see the fireworks.", "何百人もの人が花火を見に来た。"],
  s455: ["He's so [_____] that he thinks he is always right.", "彼はとても傲慢で、自分がいつも正しいと思っている。"],
  s456: ["It takes the earth one year to complete its [_____] around the sun.", "地球が太陽の周りを1周するのに1年かかる。"],
  s457: ["A right [_____] is 90 degrees.", "直角は90度だ。"],
  s458: ["In sports, men and women should be treated as [_____]s.", "スポーツでは男女は対等に扱われるべきだ。"],
  s459: ["The red car tried to [_____] the bus on the narrow road.", "赤い車が狭い道でバスを追い越そうとした。"],
  s460: ["I [_____] seeing you next week.", "来週お会いできるのを楽しみにしています。"],
  s461: ["In [_____], people choose their leaders by voting.", "民主主義では、人々は投票で指導者を選ぶ。"],
  s462: ["Ginza is a famous shopping [_____] in Tokyo.", "銀座は東京の有名な買い物地区だ。"],
  s463: ["She [_____]ed her goal of running a marathon.", "彼女はマラソンを走るという目標を成し遂げた。"],
  s464: ["Money is only one [_____] of a job; you should also think about how much you enjoy it.", "お金は仕事の一側面にすぎない。どれだけ楽しめるかも考えるべきだ。"],
  s465: ["The train arrived [_____] at 10:30.", "電車は予定どおり10時30分に到着した。"],
  s466: ["Can you [_____] these books at the library on your way to work?", "仕事に行く途中で、この本を図書館に置いてきてもらえますか。"],
  s467: ["Buying good shoes saves money [_____].", "よい靴を買うと、長い目で見ればお金の節約になる。"],
  s468: ["The [_____] found the thief by following his footprints.", "刑事は足跡をたどって泥棒を見つけた。"],
  s469: ["Stores now charge money for [_____]s, so bring your own shopping bag.", "店はレジ袋を有料にしているので、自分の買い物袋を持参しよう。"],
  s470: ["After the long, sad movie, I felt [_____] tired.", "長くて悲しい映画のあと、私は精神的に疲れた。"],
  s471: ["The plan sounds good, but will it work [_____]?", "その計画はよさそうに聞こえるが、実際にうまくいくだろうか。"],
  s472: ["The flight was late [_____] bad weather.", "悪天候のため、飛行機が遅れた。"],
  s473: ["What is the [_____] of your visit?", "訪問の目的は何ですか。"],
  s474: ["A little sugar won't do you any [_____].", "少しの砂糖なら体に害はない。"],
  s475: ["When my father retires, my brother will [_____] the family business.", "父が引退したら、兄が家業を継ぐ。"],
  s476: ["I love the flower [_____] on the table.", "テーブルの上の生け花がとても素敵だ。"],
  s477: ["Her first novel was rejected by ten [_____]s.", "彼女の最初の小説は10の出版社に断られた。"],
  s478: ["The pyramids were built in [_____] times.", "ピラミッドは古代に建てられた。"],
  s479: ["The rain [_____]ed our picnic.", "雨でピクニックが台無しになった。"],
  s480: ["The trip will cost 5,000 yen [_____].", "旅行の費用はせいぜい5,000円だろう。"],
  s481: ["This year's rice [_____] was very good.", "今年の米の収穫はとてもよかった。"],
  s482: ["Our main [_____] has lowered its prices.", "最大の競合相手が値段を下げた。"],
  s483: ["Sorry, that size is out of [_____].", "申し訳ありませんが、そのサイズは在庫切れです。"],
  s484: ["Can you [_____] the man in this photo?", "この写真の男性が誰かわかりますか。"],
  s485: ["Columbus was a famous [_____].", "コロンブスは有名な探検家だった。"],
  s486: ["He ran 100 meters in nine seconds! That's [_____]!", "彼は100メートルを9秒で走った！信じられない！"],
  s487: ["Can you [_____] this math problem?", "この数学の問題を解けますか。"],
  s488: ["Don't [_____] any important details in your report.", "報告書で大事な細部を省いてはいけない。"],
  s489: ["We could see a small boat [_____] in the sea.", "はるか遠くの海に小さな船が見えた。"],
  s490: ["Read the [_____]s carefully before you use the machine.", "機械を使う前に説明書をよく読みなさい。"],
  s491: ["The shop is [_____] closed for repairs.", "その店は改装のため一時的に閉まっている。"],
  s492: ["The [_____]s of the box fell on the floor.", "箱の中身が床に落ちた。"],
  s493: ["The ship slowly became a small dot on the [_____] horizon.", "船はゆっくりと遠くの水平線上の小さな点になった。"],
  s494: ["We had [_____]s from last night's dinner for lunch.", "昼食に昨夜の夕食の残り物を食べた。"],
  s495: ["His family is [_____]; they have a big house and two cars.", "彼の家は裕福で、大きな家と車2台を持っている。"],
  s496: ["Biting your nails is a bad [_____].", "爪をかむのは悪い癖だ。"],
  s497: ["I need to [_____] some money from the bank.", "銀行からお金を少し引き出す必要がある。"],
  s498: ["The company will [_____] its new phone next month.", "その会社は来月新しい電話を発売する。"],
  s499: ["He was found [_____] and set free.", "彼は無罪となり、釈放された。"],
  s500: ["Weather [_____]s send pictures of clouds from space.", "気象衛星は宇宙から雲の写真を送ってくる。"],
  s501: ["His answer was so [_____] that nobody understood what he meant.", "彼の答えはとてもあいまいで、誰も何を言いたいのかわからなかった。"],
  s502: ["If you need any [_____], please ask the staff.", "何かお手伝いが必要でしたら、スタッフにお声がけください。"],
  s503: ["Mars is the fourth [_____] from the sun.", "火星は太陽から4番目の惑星だ。"],
  s504: ["Take this [_____] to the pharmacy to get your medicine.", "この処方箋を薬局に持っていって薬をもらってください。"],
  s505: ["The new machine improved the [_____] of the factory.", "新しい機械で工場の効率が上がった。"],
  s506: ["This movie was made in [_____] with a Korean company.", "この映画は韓国の会社と共同で制作された。"],
  s507: ["Teachers [_____] students on their homework and tests.", "教師は宿題とテストで生徒を評価する。"],
  s508: ["She studies English [_____] at university.", "彼女は大学で英文学を学んでいる。"],
  s509: ["The dog likes to [_____] holes in the garden.", "その犬は庭に穴を掘るのが好きだ。"],
  s510: ["We use [_____] with a person and a memory, as in \"This song reminds me of summer.\"", "「この歌を聞くと夏を思い出す」のように、人に何かを思い出させるときに使います。"],
  s512: ["We had to [_____] our plans because of the rain.", "雨のため計画を変更しなければならなかった。"],
  s513: ["The ball [_____]ed down the hill.", "ボールは丘を転がり落ちた。"],
  s514: ["This chapter will [_____] the causes of the war.", "この章では戦争の原因を扱う。"],
  s515: ["Soldiers [_____] their country.", "兵士は国を守る。"],
  s516: ["Many fishing boats were tied up in the [_____].", "たくさんの漁船が港に係留されていた。"],
  s517: ["The picnic was canceled [_____] the rain.", "雨のためピクニックは中止になった。", ["instead of", "in front of", "a number of"]],
  s518: ["He has a bad [_____] and often shouts at people.", "彼は短気で、よく人に怒鳴る。"],
  s519: ["Lifting weights builds [_____].", "ウエイトを持ち上げると筋肉がつく。"],
  s520: ["I spent my [_____] in a small village by the sea.", "私は子ども時代を海辺の小さな村で過ごした。"],
  s521: ["Don't [_____] people when they make mistakes.", "人が間違えたときに笑ってはいけない。"],
  s522: ["The [_____]s of the flood received food and blankets.", "洪水の被災者たちは食料と毛布を受け取った。"],
  s523: ["On a clear day, Mount Fuji is [_____] from here.", "晴れた日には、ここから富士山が見える。"],
  s524: ["Add sugar to your coffee and [_____] it with a spoon.", "コーヒーに砂糖を入れて、スプーンでかき混ぜなさい。"],
  s525: ["The two meetings [_____], so I can only go to one of them.", "2つの会議の時間が重なっているので、どちらか一方にしか行けない。"],
  s526: ["The [_____] between the two countries lasted for years.", "2国間の対立は何年も続いた。"],
  s527: ["The police will [_____] the cause of the accident.", "警察が事故の原因を調べる。"],
  s528: ["We'll go to the beach tomorrow [_____] it rains.", "雨が降らない限り、明日は海に行きます。"],
  s529: ["The school is raising [_____]s to build a new gym.", "学校は新しい体育館を建てるための資金を集めている。"],
  s530: ["I don't hate math. [_____], it's my favorite subject.", "数学は嫌いじゃないよ。実際、一番好きな教科なんだ。"],
  s531: ["We use [_____] when someone gives another person what they need, as in \"The school provides students with lunch.\"", "「学校は生徒に昼食を提供している」のように、人に必要なものを与えるときに使います。"],
  s532: ["The test was [_____] easy, so most students passed.", "テストはかなり簡単だったので、ほとんどの生徒が合格した。"],
  s533: ["The people in the church bowed their heads in [_____].", "教会の人々は頭を垂れて祈った。"],
  s534: ["I have two brothers. One lives in Tokyo, and [_____] lives in Osaka.", "私には兄弟が2人いる。1人は東京に、もう1人は大阪に住んでいる。"],
  s535: ["I hope you [_____] on your exam tomorrow.", "明日の試験がうまくいくといいね。"],
  s536: ["Please [_____] my house anytime you are in the area.", "近くに来たらいつでも家に寄ってね。"],
  s537: ["Buses run [_____] in the city center, every five minutes.", "市の中心部ではバスが頻繁に走っていて、5分おきに来る。"],
  s538: ["Thank you for giving so [_____] to our charity.", "私たちの慈善団体に惜しみなくご寄付いただき、ありがとうございます。"],
  s539: ["The mother [_____]d her son when he came home from the war.", "母親は戦争から帰った息子を抱きしめた。"],
  s540: ["We need [_____] energy, such as solar and wind power, that will not run out.", "太陽光や風力のような、なくならない持続可能なエネルギーが必要だ。"],
  s541: ["Thousands of [_____]s watched the game from the stands.", "何千人もの観客がスタンドから試合を見た。"],
  s542: ["We accept [_____] by credit card.", "クレジットカードでのお支払いを受け付けています。"],
  s543: ["Let me [_____] myself. My name is Ken.", "自己紹介させてください。私の名前は健です。"],
  s544: ["Could you [_____] this as a gift?", "これを贈り物用に包んでいただけますか。"],
  s545: ["According to [_____], a dragon once lived in this lake.", "伝説によれば、かつてこの湖には竜がすんでいた。"],
  s546: ["There is little [_____] of rain this week.", "今週は雨の見込みはほとんどない。"],
  s547: ["He [_____]d to answer my question.", "彼は私の質問に答えるのを拒んだ。"],
  s548: ["Go [_____] until you reach the station.", "駅に着くまでまっすぐ進んでください。"],
  s549: ["We had to [_____] the meeting until next week.", "会議を来週まで延期しなければならなかった。"],
  s550: ["Large ships are used to [_____] cars across the ocean.", "大型船は海を越えて車を輸送するのに使われる。"],
  s551: ["[_____], I didn't like natto, but now I love it.", "最初は納豆が好きではなかったが、今は大好きだ。"],
  s552: ["She looked at her friend's new bike with [_____].", "彼女は友だちの新しい自転車をうらやましそうに見た。"],
  s553: ["I stood up too quickly and felt [_____].", "急に立ち上がったらめまいがした。"],
  s554: ["You should get more [_____]; try walking for 30 minutes a day.", "もっと運動したほうがいい。1日30分歩いてみたら？"],
  s555: ["The total cost will [_____] about 50,000 yen.", "費用の総額は約5万円になるだろう。"],
  s556: ["The ship's first [_____] across the Atlantic took two weeks.", "その船の最初の大西洋横断の航海は2週間かかった。"],
  s557: ["My father had a big [_____] on my choice of job.", "父は私の職業選びに大きな影響を与えた。"],
  s558: ["Children under six can ride the bus [_____].", "6歳未満の子どもは無料でバスに乗れる。"],
  s559: ["Getting a flu [_____] every year helps protect you.", "毎年インフルエンザのワクチンを打つと、身を守るのに役立つ。"],
  s560: ["Give me a few days to [_____] your offer.", "あなたの申し出をよく考えるために数日ください。"],
  s561: ["The [_____] change in the weather surprised everyone.", "天気が急に変わって、みんな驚いた。"],
  s562: ["Please [_____] your phone during the test.", "試験中は携帯電話をしまってください。"],
  s563: ["After a long [_____], the brothers were happy to see each other again.", "長く離れ離れになっていたあと、兄弟は再会を喜んだ。"],
  s564: ["You may [_____] your dictionary during the test.", "試験中に辞書を参照してもよい。"],
  s565: ["The stadium was filled to [_____] with fans.", "スタジアムはファンで満員だった。"],
  s566: ["We use [_____] when we forget to be thankful for something, as in \"Don't take your health for granted.\"", "「健康を当たり前だと思ってはいけない」のように、ありがたさを忘れているときに使います。"],
  s567: ["The [_____] of 2, 4, and 6 is 4.", "2、4、6の平均は4だ。"],
  s568: ["The movie got a lot of [_____] before it came out.", "その映画は公開前に大いに宣伝された。"],
  s569: ["There's a gas station two kilometers [_____].", "2キロ先にガソリンスタンドがある。"],
  s570: ["I always get [_____] before I speak in front of people.", "人前で話す前はいつも緊張する。"],
  s571: ["Ten countries will [_____] the meeting.", "その会議には10か国が参加する。"],
  s572: ["He likes to [_____]; he said the fish was two meters long, but it was only 50 centimeters.", "彼は大げさに言うのが好きだ。魚は2メートルあったと言ったが、実際は50センチしかなかった。"],
  s573: ["The game is losing [_____]; fewer people play it every year.", "そのゲームは人気が落ちていて、遊ぶ人は年々減っている。"],
  s574: ["My [_____] at college was economics.", "大学での私の専攻は経済学だった。"],
  s575: ["You don't need to come tomorrow; it isn't [_____].", "明日は来なくていいよ。その必要はないから。"],
  s576: ["Thousands of people [_____]ed against the new tax.", "何千人もの人が新しい税に抗議した。"],
  s577: ["Early in the morning, the lake is quiet and [_____].", "早朝の湖は静かで穏やかだ。"],
  s578: ["Our team will finish third [_____].", "私たちのチームはせいぜい3位だろう。"],
  s579: ["This temple was built in the 8th [_____].", "この寺は8世紀に建てられた。"],
  s580: ["Caring for his sick father was a heavy [_____] for him.", "病気の父親の世話は彼にとって重い負担だった。"],
  s581: ["Doctors who [_____] children's health are called pediatricians.", "子どもの健康を専門とする医師は小児科医と呼ばれる。"],
  s582: ["The village is just [_____] that mountain.", "その村はあの山のすぐ向こうにある。"],
  s583: ["The [_____] dropped below zero last night.", "昨夜、気温が氷点下まで下がった。"],
  s584: ["Nobody told him to do it; he cleaned the park [_____].", "誰に言われたわけでもなく、彼は自ら進んで公園を掃除した。"],
  s585: ["Without [_____], going to the hospital can be very expensive.", "健康保険がないと、病院に行くのはとても高くつくことがある。"],
  s586: ["Each [_____] in the race will get a T-shirt.", "レースの参加者には一人一枚Tシャツがもらえる。"],
  s587: ["It was [_____] warm for December.", "12月にしては異常に暖かかった。", ["politely", "directly", "previously"]],
  s588: ["I didn't do it [_____]; it just happened.", "意識してやったわけではなく、たまたまそうなったのです。"],
  s589: ["Africa is the second largest [_____].", "アフリカは2番目に大きい大陸だ。"],
  s590: ["After hitting his head, he suffered [_____] and couldn't remember his own name.", "頭を打ったあと、彼は記憶喪失になり、自分の名前も思い出せなかった。"],
  s591: ["[_____], let me thank everyone for coming.", "まず第一に、お越しいただいた皆さんにお礼を申し上げます。"],
  s592: ["He is my mother's brother; [_____], he is my uncle.", "彼は母の兄弟だ。言い換えれば、私のおじだ。"],
  s593: ["The sun [_____]ed behind the clouds.", "太陽が雲の後ろに隠れた。"],
  s594: ["The teacher used a map to [_____] how the river moves.", "先生は川の流れ方を説明するために地図を使った。"],
  s595: ["My teeth are [_____] to cold drinks.", "私の歯は冷たい飲み物にしみる。"],
  s596: ["If we leave now, [_____] we'll catch the last train.", "今出れば、運がよければ終電に間に合うだろう。"],
  s597: ["My old car is still [_____]; it has never broken down.", "私の古い車は今でも信頼でき、一度も故障したことがない。"],
  s598: ["[_____] and tell me what happened.", "落ち着いて、何があったのか話して。"],
  s599: ["The shop has closed [_____]; it will never open again.", "その店は永久に閉店した。二度と開くことはない。"],
  s600: ["It looks [_____] it's going to rain.", "まるで雨が降りそうな空模様だ。"],
  s601: ["She worked hard to [_____] her dream of becoming a doctor.", "彼女は医者になるという夢をかなえるために一生懸命努力した。"],
  s602: ["Tests will [_____] which class you are in.", "どのクラスに入るかはテストで決まる。"],
  s603: ["It started to rain, and [_____], I had no umbrella.", "雨が降り出し、さらに悪いことに傘を持っていなかった。", ["for example", "in contrast", "at first"]],
  s604: ["If you keep trying, you will [_____].", "努力し続ければ、きっと成功する。"],
  s606: ["[_____] summer vacation, where are you going this year?", "夏休みと言えば、今年はどこへ行くの？"],
  s607: ["He looked [_____] at his brother's new bike.", "彼は兄の新しい自転車をねたましそうに見た。"],
  s608: ["Humans are [_____] animals; we like to live in groups.", "人間は社会的な動物で、集団で暮らすことを好む。"],
  s609: ["Can you [_____] how this machine works?", "この機械の仕組みを説明してもらえますか。"],
  s610: ["Let's [_____] the rain to stop.", "雨がやむのを待とう。"],
  s611: ["The runners had to jump over [_____]s on the track.", "走者たちはトラックの障害物を跳び越えなければならなかった。"],
  s612: ["Eating too many sweets can cause [_____]s in your teeth.", "甘いものを食べすぎると虫歯になることがある。"],
  s613: ["We use [_____] to praise someone for something good, as in \"I congratulated her on winning the prize.\"", "「私は彼女の受賞を祝った」のように、人のよい出来事を祝うときに使います。"],
  s614: ["Call me if you are [_____].", "困ったときは電話してね。"],
  s615: ["Red is often [_____] danger.", "赤はしばしば危険と結びつけられる。"],
  s616: ["Nothing can [_____] hitting a child.", "子どもをたたくことはどんな理由があっても正当化できない。"],
  s617: ["He seems to [_____] the robbery.", "彼はその強盗事件に関わっているようだ。"],
  s618: ["A healthy [_____] includes plenty of vegetables.", "健康的な食事には野菜がたっぷり含まれる。"],
  s619: ["Do you [_____] ghosts?", "幽霊の存在を信じますか。"],
  s620: ["If you don't drink water in this heat, you might [_____].", "この暑さで水を飲まないと、気を失うかもしれないよ。"],
  s621: ["Your face looks [_____]. Have we met before?", "あなたの顔には見覚えがあります。以前お会いしましたか。"],
  s622: ["Eye color is [_____] passed down from parents to children.", "目の色は遺伝によって親から子へ受け継がれる。"],
  s623: ["We apologize for any [_____] caused by the delay.", "遅延によりご不便をおかけしたことをお詫びします。"],
  s624: ["Don't be so [_____]; things will get better.", "そんなに否定的にならないで。状況はよくなるよ。"],
  s625: ["My teacher [_____]d me to enter the speech contest.", "先生は私にスピーチコンテストに出るよう励ましてくれた。"],
  s626: ["You can [_____] this bottle many times.", "この瓶は何度も再利用できる。"],
  s627: ["She looked at me [_____], as if she didn't believe my story.", "彼女は私の話を信じていないかのように、疑わしそうに私を見た。"],
  s628: ["Cheese can [_____] goat's milk.", "チーズはヤギの乳から作ることもできる。"],
  s629: ["Clean water is [_____] in the desert.", "砂漠ではきれいな水は貴重だ。"],
  s630: ["He won't [_____] that he was wrong.", "彼は自分が間違っていたことを認めようとしない。"],
  s631: ["The car [_____] is very important to Japan's economy.", "自動車産業は日本の経済にとってとても重要だ。"],
  s632: ["At low [_____], you can walk to the island.", "干潮のときは島まで歩いて渡れる。"],
  s633: ["At the auction, the highest [_____] was one million yen.", "競売での最高入札額は100万円だった。"],
  s634: ["Your computer must [_____] the internet to use this app.", "このアプリを使うには、コンピュータがインターネットに接続されていなければならない。"],
  s635: ["She wants to go to [_____] school and become a doctor.", "彼女は医学部に進んで医者になりたいと思っている。"],
  s636: ["Make sure the ladder is [_____] before you climb it.", "はしごに登る前に、ぐらつかないか確かめなさい。"],
  s637: ["Something [_____] happened last night: all the lights went on by themselves.", "昨夜、奇妙なことが起こった。明かりがひとりでに全部ついたのだ。"],
  s638: ["The baby is sleeping [_____].", "赤ちゃんがすやすや眠っている。"],
  s639: ["You should get a medical [_____] once a year.", "年に一度は健康診断を受けたほうがいい。"],
  s640: ["There were [_____] 200 people at the concert, but I didn't count them exactly.", "コンサートには約200人いたが、正確には数えていない。"],
  s641: ["How did your parents [_____] when you told them the news?", "その知らせを伝えたとき、ご両親はどんな反応でしたか。"],
  s642: ["I'm sure your parents will [_____] your test results; you got all A's.", "きっとご両親はあなたの成績を喜ぶよ。全部Aだったんだから。"],
  s643: ["This town used to [_____] its silk.", "この町はかつて絹で知られていた。"],
  s644: ["Let's walk [_____] taking the bus.", "バスに乗る代わりに歩こう。"],
  s645: ["Taxi drivers must [_____] every street in the city.", "タクシー運転手は市内のあらゆる通りをよく知っていなければならない。"],
  s646: ["He likes to [_____] while he works.", "彼は仕事をしながら口笛を吹くのが好きだ。"],
  s647: ["The clock [_____]s twelve at midnight.", "時計は真夜中に12時を打つ。"],
  s648: ["Scientists [_____] the stars with telescopes.", "科学者たちは望遠鏡で星を観察する。"],
  s649: ["Reading books is a great way to build your [_____].", "本を読むことは語彙を増やすのにとてもよい方法だ。"],
  s650: ["She was absent from school for a week because of [_____].", "彼女は病気のため1週間学校を休んだ。"],
  s651: ["The thief tried to [_____] when he saw the police.", "泥棒は警察を見て逃げようとした。"],
  s652: ["Some people [_____] peanuts and get sick.", "ピーナッツに反応して具合が悪くなる人もいる。"],
  s653: ["The Amazon [_____] is home to millions of kinds of plants and animals.", "アマゾンの熱帯雨林には何百万種もの動植物がすんでいる。", ["satellite", "psychologist", "contrast"]],
  s654: ["I didn't [_____] to see you here!", "ここであなたに会うとは思わなかった！"],
  s655: ["The [_____] delivers our products to stores across the country.", "卸売業者が私たちの製品を全国の店に届けている。"],
  s656: ["This painting has come to [_____] be his best work.", "この絵は彼の最高傑作だと見なされるようになった。"],
  s657: ["Everyone can help [_____].", "誰でも何らかの形で手伝うことができる。"],
  s658: ["You've made great [_____] in English this year.", "今年、あなたの英語はとても上達した。"],
  s659: ["The [_____] says \"No parking.\"", "標識には「駐車禁止」と書いてある。"],
  s660: ["The entrance [_____] for the museum is 500 yen.", "博物館の入場料は500円だ。"],
  s661: ["These shoes are too [_____]; I need a bigger size.", "この靴はきつすぎる。もっと大きいサイズが必要だ。"],
  s662: ["I tried to [_____] my father to buy a dog, but he said no.", "父に犬を買ってくれるよう説得しようとしたが、だめだと言われた。"],
  s663: ["The weather is [_____] getting warmer.", "だんだん暖かくなってきている。"],
  s664: ["Everyone came [_____] Ken.", "健以外はみんな来た。"],
  s665: ["My father [_____] gets angry; he is very calm.", "父はめったに怒らない。とても穏やかな人だ。"],
  s666: ["This factory uses a very [_____] water.", "その工場は非常に大量の水を使う。"],
  s668: ["There is a stone [_____] of a lion in front of the museum.", "博物館の前にはライオンの石の彫刻がある。"],
  s670: ["Each side of this [_____] is five centimeters long.", "この正方形の各辺は5センチだ。"],
  "s3-48": ["Her joke made everyone [_____] out loud.", "彼女の冗談にみんな声を出して笑った。"],
  "s3-194": ["World [_____] II ended in 1945.", "第二次世界大戦は1945年に終わった。"],
  "s3-353": ["Please [_____] your coat on the hook.", "コートはフックに掛けてください。"],
  "s3-361": ["I want a room of my [_____].", "自分だけの部屋が欲しい。"],
  "s3-373": ["The soldiers followed the captain's [_____]s.", "兵士たちは隊長の命令に従った。"],
  "s3-376": ["Please write your name and [_____] on this form.", "この用紙に名前と住所を書いてください。"],
  "s3-378": ["We will [_____] Osaka at noon.", "私たちは正午に大阪に到着する。"],
  "s3-486": ["You [_____] tired today. Are you OK?", "今日は疲れているみたいだね。大丈夫？"],
  "s3-537": ["Please take one step [_____] when your name is called.", "名前を呼ばれたら1歩前に出てください。", ["socially", "previously", "annually"]],
  "s3-566": ["Snow [_____]ed the whole town.", "雪が町全体を覆った。"],
  "s3-601": ["Prices have risen over the [_____] few years.", "ここ数年で物価が上がった。"],
  a4: ["We need more [_____] for the fire.", "火にくべる木がもっと必要だ。"],
  a19: ["[_____] countries should help poorer countries.", "先進国はより貧しい国々を助けるべきだ。"],
  a20: ["I'm interested in Japanese [_____], especially old temples.", "私は日本の建築、特に古い寺に興味がある。"],
  a22: ["Is your sister married or [_____]?", "お姉さんは結婚しているの、それとも独身？"],
  a26: ["Please [_____] me; I'll show you to your seat.", "ついてきてください。お席にご案内します。"],
  a48: ["You should see a dentist [_____], about twice a year.", "歯医者には定期的に、年に2回ほど行ったほうがいい。"],
  a60: ["The store is open every day [_____] Monday.", "その店は月曜日以外は毎日開いている。"],
  a81: ["He came home later than [_____].", "彼はいつもより遅く帰宅した。"],
  a92: ["Sorry, this beach is [_____]; only hotel guests can use it.", "すみません、この浜辺は私有地で、ホテルの宿泊客しか使えません。"],
  a98: ["English is the [_____] language of many countries.", "英語は多くの国の公用語だ。"],
  a111: ["The man [_____] you met yesterday is my uncle.", "あなたが昨日会った男性は私のおじだ。"],
  a126: ["A bird is sitting on the [_____] of that tree.", "あの木の枝に鳥がとまっている。"],
  a133: ["Dad parks the car in the [_____].", "父は車をガレージに止める。"],
  a135: ["The truck was carrying a heavy [_____] of rocks.", "トラックは岩を山のように積んでいた。"],
  a146: ["The bar [_____] on page 5 shows that sales went up.", "5ページの棒グラフを見ると、売り上げが伸びたことがわかる。"],
  a155: ["We buy fresh fish at the [_____] every morning.", "私たちは毎朝市場で新鮮な魚を買う。"],
  a157: ["This airline has [_____] flights from Tokyo to Paris.", "この航空会社には東京からパリへの直行便がある。"],
  a174: ["I [_____] forgot about it; I'm sorry.", "うっかり忘れていただけなんです。ごめんなさい。"],
  a176: ["She is very [_____]; her desk is always neat and she never forgets anything.", "彼女はとても几帳面で、机はいつも整頓されていて、何も忘れない。"],
  a180: ["My grandfather is [_____]; he stopped working at 65.", "祖父は引退していて、65歳で仕事を辞めた。"],
  a217: ["Be [_____]; the bus will come soon.", "辛抱して。バスはもうすぐ来るから。"],
  a244: ["For your [_____], we are open 24 hours.", "お客様の便宜のため、24時間営業しております。"],
  a256: ["The [_____] of this bridge is 500 meters.", "この橋の長さは500メートルだ。"],
  a257: ["The [_____] of the newspaper decides which stories to print.", "新聞の編集者がどの記事を載せるかを決める。"],
  a289: ["After three hours of waiting, the train [_____] arrived.", "3時間待って、ついに電車が到着した。"],
  a303: ["We followed the bear's [_____]s in the snow.", "私たちは雪の中のクマの足跡をたどった。"],
  a308: ["You look tired. Sit down and [_____] for a while.", "疲れているようだね。座ってしばらく休みなさい。"],
  a321: ["The police [_____]ed the house for the stolen money.", "警察は盗まれたお金を探して家を捜索した。"],
  a347: ["Please ask the [_____] at the front desk.", "受付の係員にお尋ねください。"],
  a379: ["The beautiful sea was the [_____] for her painting.", "その美しい海が彼女の絵のひらめきの元になった。"],
  a404: ["It's too hot in the sun. Let's sit in the [_____] of that tree.", "日なたは暑すぎる。あの木陰に座ろう。"],
  a409: ["Gold and silver are [_____]s.", "金と銀は金属だ。"],
  a418: ["Please speak more [_____]; I can't hear you.", "もっとはっきり話してください。聞こえません。"],
  a439: ["These apples are fresh and [_____].", "このりんごは新鮮でシャキシャキしている。"],
  a477: ["Her [_____] language is Spanish, but she also speaks English.", "彼女の母語はスペイン語だが、英語も話す。"],
  a493: ["The [_____] of the house has three bedrooms.", "その家の上の階には寝室が3つある。"],
  a494: ["The last [_____] of the movie made me cry.", "映画の最後の場面で泣いてしまった。"],
  a526: ["This cookie is in the [_____] of a heart.", "このクッキーはハートの形をしている。"],
  a530: ["Put the plates back in the [_____].", "お皿を食器棚に戻して。"],
  a531: ["My socks are in the top [_____] of the dresser.", "靴下はたんすの一番上の引き出しに入っている。"],
  a541: ["My grandparents live in the [_____], far from the city, surrounded by rice fields.", "祖父母は都会から遠く離れた、田んぼに囲まれた田舎に住んでいる。"],
  a566: ["Harry Potter is a work of [_____]; it isn't a true story.", "ハリー・ポッターは創作で、実話ではない。"],
  a585: ["A river runs through the [_____] between the two mountains.", "2つの山の間の谷を川が流れている。"],
  a622: ["We need to stop and get [_____] for the car.", "止まって車にガソリンを入れる必要がある。"],
  a624: ["What would you do in my [_____]?", "私の立場だったら、あなたはどうしますか。", ["population", "destination", "pollution"]],
  a641: ["She is writing her first [_____].", "彼女は初めての小説を書いている。"],
  a645: ["I'm very [_____] for your help.", "助けていただいて、とても感謝しています。"],
  a649: ["The roof is held up by four stone [_____]s.", "屋根は4本の石の柱で支えられている。"],
  a670: ["Can you [_____] this button back on my shirt?", "このボタンをシャツに縫い付けてもらえますか。"],
  a717: ["The president's [_____] answered the phone.", "社長の秘書が電話に出た。"],
  a756: ["This [_____] of the queen was painted 200 years ago.", "この女王の肖像画は200年前に描かれた。"],
  a836: ["Cherry blossoms [_____] in early April in Tokyo.", "東京では桜は4月上旬に咲く。"],
  a911: ["Picture [_____]s are sold on the second floor.", "額縁は2階で売っています。"],
  a926: ["Tie the box with a piece of [_____].", "ひもで箱を縛りなさい。"],
  a929: ["She baked the cookies in [_____]es of twenty.", "彼女はクッキーを20枚ずつ焼いた。"],
  a979: ["This screw is [_____]; can you tighten it?", "このねじはゆるんでいる。締めてもらえる？"],
  a1036: ["The weather [_____] for tomorrow is sunny.", "明日の天気の予測は晴れだ。"],
  a1067: ["How much do you [_____]?", "あなたの体重はどのくらいですか。"],
  a1116: ["The fire caused damage on a large [_____].", "その火事は大規模な被害をもたらした。"],
  a1140: ["Only the [_____] part of the castle is open to visitors.", "城の内部だけが見学者に公開されている。"],
  a1166: ["The ship will [_____] around the islands for a week.", "その船は1週間かけて島々を巡航する。"],
  a1200: ["The [_____] wore a white dress at the wedding.", "花嫁は結婚式で白いドレスを着た。"],
  a1205: ["This battery will [_____] for ten hours.", "この電池は10時間持つ。"],
  a1266: ["She moved to Paris to [_____] her dream of becoming an artist.", "彼女は画家になる夢を追うためにパリに移った。"],
  a1287: ["The car has run out of [_____].", "車のガソリンがなくなった。"],
  a1300: ["This phone is light and, more [_____], very cheap.", "この電話は軽く、さらに重要なことに、とても安い。"],
  a1302: ["Eating rice cakes at New Year is a Japanese [_____].", "正月に餅を食べるのは日本の伝統だ。"],
  a1371: ["The festival was [_____], with music and dancing everywhere.", "祭りはにぎやかで、あちこちで音楽と踊りがあった。"],
  a1383: ["I left my keys [_____] in the house, but I can't find them.", "家のどこかに鍵を置いたのだが、見つからない。"],
  a1395: ["The car was badly damaged, but [_____], no one was hurt.", "車はひどく壊れたが、幸いにも誰もけがをしなかった。"],
  a1416: ["He paid for the car by [_____].", "彼は車の代金を小切手で払った。"],
  a1476: ["Her [_____] is to become a pilot.", "彼女の夢はパイロットになることだ。"],
  a1481: ["She kissed her baby on the [_____].", "彼女は赤ちゃんの頬にキスをした。"],
  a1502: ["Wood will [_____] on water.", "木は水に浮く。"],
  a1526: ["America declared [_____] from Britain in 1776.", "アメリカは1776年にイギリスからの独立を宣言した。"],
  a1552: ["There were [_____] fifty people at the party.", "パーティーにはおよそ50人がいた。"],
  a1553: ["The white snow made a beautiful [_____] with the blue sky.", "白い雪が青い空と美しい対照をなしていた。"],
  a1630: ["Of tea and coffee, I prefer the [_____].", "紅茶とコーヒーなら、後者のほうが好きだ。"],
  a1679: ["I didn't like the [_____] of his voice; he sounded angry.", "彼の声の調子が気に入らなかった。怒っているように聞こえた。"],
  a1682: ["He made his [_____] selling computers.", "彼はコンピュータを売って財産を築いた。"],
  a1697: ["We [_____]ed around the old town all afternoon.", "私たちは午後ずっと旧市街をぶらぶら歩いた。"],
  a1750: ["The magician refused to [_____] how he did the trick.", "手品師はその手品の種を明かそうとしなかった。"],
  a1752: ["Dogs like to [_____] bones in the garden.", "犬は庭に骨を埋めるのが好きだ。"],
  a1852: ["Our class [_____] will be held ten years after graduation.", "私たちのクラスの同窓会は卒業10年後に開かれる。"],
  a1902: ["After the big dinner, my [_____] was full.", "たくさん夕食を食べて、お腹がいっぱいになった。"],
  a1952: ["Flights were canceled because of thick [_____].", "濃い霧のため、飛行機が欠航になった。"],
  a1981: ["The [_____] spent six months on the space station.", "その宇宙飛行士は宇宙ステーションで6か月を過ごした。", ["community", "continent", "vocabulary"]],
  a2_die: ["My plants [_____]d because I forgot to water them.", "水をやるのを忘れたので、植物が枯れてしまった。"],
  a2_sweat: ["After running, my shirt was wet with [_____].", "走ったあと、シャツが汗でびっしょりだった。"],
  a2_tidy: ["Please put your toys away and keep your room [_____].", "おもちゃを片付けて、部屋をきちんとしておきなさい。"],
};
