import { SentenceRewrites } from "./types";

/**
 * 高校標準の例文の書き直し。キーは単語ID、値は [例文, 和訳, 誤答]。
 * 決まり・使い方は scripts/apply_sentences.ts を参照。
 */
export const senior2: SentenceRewrites = {
  s2_41: ["I [_____] forgot about the meeting.", "会議のことをすっかり忘れていた。"],
  s2_42: ["I [_____] if it will rain tomorrow.", "明日は雨が降るかなあ。"],
  s2_43: ["Our team has won five games [_____].", "私たちのチームは5連勝している。"],
  s2_44: ["This medicine may [_____] reducing pain.", "この薬は痛みを和らげるのに効果的かもしれない。"],
  s2_45: ["The teacher gave a clear [_____] of the rule.", "先生はその規則をわかりやすく説明した。"],
  s2_46: ["I felt [_____] in my jeans at the fancy party.", "高級なパーティーでジーンズ姿の私は場違いな気がした。"],
  s2_47: ["Who [_____]ed the telephone?", "電話を発明したのは誰ですか。"],
  s2_48: ["This magazine prints a weekly news [_____].", "この雑誌は毎週ニュースの要約を載せている。"],
  s2_49: ["Many students [_____] English grammar.", "多くの生徒が英文法に苦戦している。"],
  s2_50: ["Some birds cannot fly. Penguins, for [_____], live on the ground and swim.", "飛べない鳥もいる。たとえばペンギンは地上で暮らし、泳ぐ。"],
  s2_51: ["Don't slip on the banana [_____]!", "バナナの皮で滑らないでね！"],
  s2_52: ["Every [_____] has the right to vote.", "すべての市民に投票する権利がある。"],
  s2_53: ["There is a spider on the [_____].", "天井にクモがいる。"],
  s2_55: ["[_____], I sleep seven hours a night.", "平均すると、私は一晩に7時間眠る。"],
  s2_56: ["Thank you for your kind [_____] during my stay.", "滞在中は温かいおもてなしをありがとうございました。"],
  s2_57: ["The plants died from [_____] of water.", "植物は水不足で枯れた。"],
  s2_58: ["Are you [_____]? You really want to quit your job?", "本気なの？本当に仕事を辞めたいの？"],
  s2_59: ["I need to [_____] my passport before it expires.", "期限が切れる前にパスポートを更新する必要がある。"],
  s2_60: ["[_____], Japanese trains are very punctual.", "一般的に、日本の電車はとても時間に正確だ。"],
  s2_61: ["Taking care of the dog is your [_____].", "犬の世話はあなたの責任だ。"],
  s2_62: ["Call the police if you see anything [_____].", "何か怪しいものを見たら警察に電話してください。"],
  s2_63: ["Keep your phone [_____] in case someone calls.", "誰かから電話があるかもしれないので、携帯は手の届くところに置いておいて。"],
  s2_64: ["Long skirts are [_____] this year.", "今年はロングスカートが流行している。"],
  s2_65: ["My passport is [_____], so I need a new one.", "パスポートの期限が切れているので、新しいものが必要だ。"],
  s2_66: ["This soup [_____]s delicious.", "このスープはおいしそうなにおいがする。"],
  s2_68: ["Winning the contest gave him more [_____] in himself.", "コンテストで優勝して、彼は自分にもっと自信を持った。"],
  s2_69: ["He is receiving [_____] for cancer at the hospital.", "彼は病院でがんの治療を受けている。"],
  s2_70: ["The clown tried to [_____] the children with funny tricks.", "ピエロはおかしな芸で子どもたちを楽しませようとした。"],
  s2_71: ["After the war, Japan saw rapid [_____] growth.", "戦後、日本は急速な経済成長を遂げた。"],
  s2_72: ["Only [_____] mosquitoes bite people.", "人を刺すのは雌の蚊だけだ。"],
  s2_73: ["It took me a month to [_____] living alone.", "一人暮らしに慣れるのに1か月かかった。", ["in exchange", "on the run", "in a row"]],
  s2_74: ["You need a passport to cross the [_____].", "国境を越えるにはパスポートが必要だ。"],
  s2_75: ["I didn't [_____] her at first because she had cut her hair.", "彼女が髪を切っていたので、最初は誰だかわからなかった。"],
  s2_76: ["He tried many times and [_____] passed the exam.", "彼は何度も挑戦して、ついに試験に合格した。"],
  s2_77: ["She got a full [_____] to study at Harvard.", "彼女はハーバードで学ぶための全額奨学金を得た。"],
  s2_78: ["She [_____]d her life to helping poor children.", "彼女は貧しい子どもたちを助けることに一生をささげた。"],
  s2_79: ["What's the [_____]? You look pale.", "どうしたの？顔色が悪いよ。"],
  s2_80: ["This magnet will [_____] the fridge door.", "この磁石は冷蔵庫の扉にくっつく。"],
  s2_82: ["Is three o'clock [_____] for you?", "3時はご都合よろしいですか。"],
  s2_83: ["Please [_____] this form and give it to the nurse.", "この用紙に記入して看護師に渡してください。"],
  s2_84: ["If the bus doesn't come, we have no [_____] but to walk.", "バスが来なければ、歩くしかない。"],
  s2_85: ["This store sells a wide [_____] of shoes.", "この店はさまざまな靴を売っている。"],
  s2_86: ["Public [_____] in Tokyo is very convenient.", "東京の公共交通機関はとても便利だ。"],
  s2_87: ["Be careful with that glass; it's very [_____].", "そのグラスに気をつけて。とても壊れやすいから。"],
  s2_88: ["The bird dropped a white [_____].", "鳥が白い羽を落とした。"],
  s2_89: ["Who is the [_____] prime minister of Japan?", "日本の現在の首相は誰ですか。"],
  s2_90: ["She has a beautiful singing [_____].", "彼女は美しい歌声を持っている。"],
  s2_91: ["Prices have [_____] increased this year.", "今年は物価が大幅に上がった。"],
  s2_92: ["She broke the world [_____] in the 100 meters.", "彼女は100メートルで世界記録を破った。"],
  s2_93: ["It is against the [_____] to drive without a license.", "免許なしで運転するのは法律違反だ。"],
  s2_94: ["My father often travels [_____] for work.", "父は仕事でよく海外に行く。"],
  s2_95: ["[_____] your help, I finished the work on time.", "あなたの助けのおかげで、時間どおりに仕事を終えられた。"],
  s2_96: ["A rainbow [_____]ed in the sky after the rain.", "雨のあと空に虹が現れた。"],
  s2_97: ["Do you have any [_____]s for our trip?", "旅行について何か提案はありますか。"],
  s2_98: ["The old house is [_____] repair.", "その古い家は修理が必要だ。"],
  s2_99: ["He felt [_____] after lying to his mother.", "母にうそをついたあと、彼は恥ずかしく思った。"],
  s2_100: ["Turn off your phone so you can [_____] your studies.", "勉強に集中できるように、携帯の電源を切りなさい。"],
  s2_101: ["I was [_____] for words when I heard the news.", "その知らせを聞いて、私は言葉を失った。"],
  s2_102: ["Don't [_____] to ask if you have any questions.", "質問があれば遠慮なく聞いてください。"],
  s2_103: ["During the Great [_____] of the 1930s, many people lost their jobs.", "1930年代の大恐慌の間、多くの人が職を失った。"],
  s2_104: ["The teacher gives each student [_____] attention.", "先生は生徒一人ひとりに個別に目を配っている。"],
  s2_105: ["Please don't [_____] me while I'm talking.", "私が話している間は口をはさまないでください。"],
  s2_106: ["You should [_____] the dangers of swimming in the sea.", "海で泳ぐことの危険に気づいておくべきだ。"],
  s2_107: ["The doctors seem to [_____] his health.", "医師たちは彼の健康を気にかけているようだ。"],
  s2_108: ["[_____], I will study for an hour every day.", "これからは毎日1時間勉強します。"],
  s2_109: ["Tea or coffee? Do you have any [_____]?", "紅茶とコーヒー、何かお好みはありますか。"],
  s2_110: ["Three students were [_____] from class today.", "今日は3人の生徒が授業を欠席した。"],
  s2_111: ["The food at that restaurant was [_____]; I'll never go there again.", "あのレストランの料理はひどかった。二度と行かない。"],
  s2_112: ["Keep the cookies in an airtight [_____].", "クッキーは密閉容器に入れておきなさい。"],
  s2_113: ["The [_____] is high today, so it feels very hot.", "今日は湿度が高いので、とても暑く感じる。"],
  s2_114: ["This word is [_____] used in everyday conversation, so you should learn it.", "この単語は日常会話でよく使われるので、覚えておくべきだ。"],
  s2_115: ["The test was [_____] easy compared to last year's.", "そのテストは昨年に比べると比較的簡単だった。"],
  s2_117: ["We found a bear's [_____] in the mud.", "泥の中にクマの足跡を見つけた。"],
  s2_118: ["The crew had to [_____] the sinking ship.", "乗組員は沈みかけた船を捨てなければならなかった。"],
  s2_119: ["Take an umbrella [_____] it rains.", "雨が降るといけないから傘を持っていきなさい。"],
  s2_120: ["A sponge [_____]s water.", "スポンジは水を吸収する。"],
  s2_121: ["She won first prize in the piano [_____].", "彼女はピアノコンクールで1位になった。"],
  s2_122: ["The [_____] reason I chose this school is its English program.", "この学校を選んだ主な理由は英語のプログラムだ。"],
  s2_123: ["My mother told me not to talk to [_____]s.", "母は私に知らない人と話してはいけないと言った。"],
  s2_124: ["Your English shows a lot of [_____].", "あなたの英語にはずいぶん進歩が見られる。"],
  s2_125: ["Her performance in the play was [_____]; everyone praised her.", "劇での彼女の演技は素晴らしく、みんなが彼女をほめた。"],
  s2_126: ["Did you read the newspaper [_____] about the new station?", "新しい駅についての新聞記事を読みましたか。"],
  s2_127: ["We use [_____] in the passive to say that someone is deeply interested in something, as in \"He was absorbed in his book.\"", "「彼は本に夢中になっていた」のように、受け身の形で何かに没頭していることを表します。"],
  s2_128: ["The heavy snow brought traffic to a complete [_____].", "大雪で交通は完全に止まった。"],
  s2_129: ["I [_____] to work by train every day.", "私は毎日電車で通勤している。"],
  s2_130: ["Come and see me [_____] you like.", "いつでも好きなときに会いに来てね。"],
  s2_131: ["The unemployment [_____] has gone down.", "失業率が下がった。"],
  s2_132: ["Does anyone have any [_____]s to this plan?", "この計画に反対の人はいますか。"],
  s2_133: ["The book tells of a boy's [_____]s on a desert island.", "その本は無人島での少年の冒険を描いている。"],
  s2_134: ["Is the room [_____] for 30 people?", "その部屋は30人には十分な広さですか。"],
  s2_135: ["I read the Japanese [_____] of this novel.", "私はこの小説の日本語訳を読んだ。"],
  s2_136: ["Can you [_____] that you were at home last night?", "昨夜家にいたことを証明できますか。"],
  s2_137: ["You're doing great! [_____] the good work!", "よくやっているね！その調子で頑張って！"],
  s2_138: ["His loud voice [_____]s me.", "彼の大声にはイライラする。"],
  s2_139: ["Please call me on your [_____] at the airport.", "空港に着いたら電話してください。"],
  s2_140: ["I was very [_____] that I didn't win, but I'll try again next year.", "優勝できなくてとてもがっかりしたが、来年また挑戦する。"],
  s2_141: ["The police are trying to find out the [_____] of the thief.", "警察は泥棒の身元を突き止めようとしている。"],
  s2_142: ["The new law was passed by [_____].", "新しい法律は議会で可決された。"],
  s2_143: ["Learning a language takes a lot of time and [_____].", "言語を学ぶには多くの時間と努力が必要だ。"],
  s2_144: ["The child asked [_____], \"Why is the sky blue?\"", "その子は無邪気に「どうして空は青いの？」と聞いた。"],
  s2_145: ["The ancient Romans believed they had to [_____] the peoples they conquered.", "古代ローマ人は、征服した民族を文明化しなければならないと信じていた。"],
  s2_146: ["Don't be so [_____]! Get up and help me.", "そんなに怠けないで！起きて手伝って。"],
  s2_147: ["Energy [_____] goes up in summer because of air conditioners.", "夏はエアコンのためにエネルギーの消費量が増える。"],
  s2_148: ["Please [_____] the table with this cloth.", "この布でテーブルをふいてください。"],
  s2_149: ["Smoking is [_____] to your health.", "喫煙は健康に有害だ。"],
  s2_150: ["The [_____] owner of this house was a doctor.", "この家の前の持ち主は医者だった。"],
  s2_151: ["How do you [_____] the missing money?", "なくなったお金をどう説明するのですか。"],
  s2_152: ["Don't judge people by their [_____].", "人を見た目で判断してはいけない。"],
  s2_153: ["I could tell from her [_____] that she was angry.", "表情から、彼女が怒っているのがわかった。"],
  s2_154: ["I can [_____] hear you; please speak up.", "ほとんど聞こえません。もっと大きな声で話してください。"],
  s2_155: ["We have [_____] blankets if you get cold.", "寒くなったら予備の毛布がありますよ。"],
  s2_156: ["This new model is [_____] to the old one in every way.", "この新型はあらゆる点で旧型より優れている。"],
  s2_157: ["It costs a lot to [_____] an old house.", "古い家を維持するのはお金がかかる。"],
  s2_158: ["When did the accident [_____]?", "その事故はいつ起こったのですか。"],
  s2_159: ["The cut healed, but it left a small [_____] on my arm.", "切り傷は治ったが、腕に小さな傷跡が残った。"],
  s2_160: ["Please be [_____] in the library.", "図書館では静かにしてください。"],
  s2_161: ["The two [_____] parties argued about taxes.", "2つの政党が税金について議論した。"],
  s2_162: ["[_____] price, this car is the best choice.", "価格の点では、この車が一番よい選択だ。"],
  s2_163: ["He [_____]ed that he was innocent.", "彼は自分は無実だと言い張った。"],
  s2_164: ["Don't [_____] to lock the door.", "ドアの鍵をかけるのを忘れないで。"],
  s2_165: ["We arrived just [_____] for the movie.", "私たちは映画にちょうど間に合った。"],
  s2_166: ["She [_____]d her hair red.", "彼女は髪を赤く染めた。"],
  s2_167: ["Be careful not to [_____] your coffee.", "コーヒーをこぼさないように気をつけて。"],
  s2_168: ["Everyone is welcome to [_____] in the discussion.", "誰でも話し合いに参加できます。"],
  s2_169: ["I [_____]ed my ankle when I fell down the stairs.", "階段から落ちて足首をひねった。"],
  s2_170: ["She studies child [_____] to understand how children think.", "彼女は子どもの考え方を理解するために児童心理学を学んでいる。"],
  s2_171: ["To put it [_____], the food was not very good.", "控えめに言っても、料理はあまりおいしくなかった。"],
  s2_172: ["Meditation helps people grow [_____].", "瞑想は人が精神的に成長するのを助ける。"],
  s2_173: ["Please [_____] the old posters from the wall.", "壁から古いポスターをはがしてください。"],
  s2_174: ["She played the [_____] of Juliet in the school play.", "彼女は学校劇でジュリエットの役を演じた。"],
  s2_175: ["Can I pay by [_____] card?", "クレジットカードで払えますか。"],
  s2_176: ["[_____] is an important industry in Kyoto.", "観光は京都の重要な産業だ。"],
  s2_177: ["Japan [_____]s many cars to other countries.", "日本は多くの車を他国に輸出している。"],
  s2_178: ["I spent the [_____] day cleaning the house.", "私は丸一日かけて家を掃除した。"],
  s2_179: ["Many [_____]s visit Japan to see cherry blossoms.", "多くの外国人が桜を見に日本を訪れる。"],
  s2_180: ["The human brain is very [_____].", "人間の脳はとても複雑だ。"],
  s2_181: ["I heard a loud [_____] from the next room.", "隣の部屋から大きなくしゃみが聞こえた。"],
  s2_182: ["Cheating on a test is not [_____].", "試験でカンニングをすることは許されない。"],
  s2_183: ["Could you [_____] my report before I hand it in?", "提出する前に私のレポートに目を通してもらえますか。"],
  s2_184: ["Let's [_____] our ideas and make one plan.", "みんなの考えをまとめて1つの計画にしよう。"],
  s2_185: ["My [_____] hurts because I ate too much.", "食べすぎてお腹が痛い。"],
  s2_186: ["Don't [_____] your homework until tomorrow.", "宿題を明日まで先延ばしにしてはいけない。"],
  s2_187: ["One dollar is [_____] to about 150 yen.", "1ドルは約150円に相当する。"],
  s2_188: ["The accident victim broke two [_____]s, an arm and a leg.", "事故の被害者は腕と脚を1本ずつ骨折した。"],
  s2_189: ["The police finally [_____]d the thief.", "警察はついに泥棒を捕まえた。"],
  s2_190: ["The United [_____] includes England and Scotland.", "連合王国（イギリス）にはイングランドとスコットランドが含まれる。"],
  s2_191: ["Do you have travel [_____] for your trip?", "旅行には旅行保険に入っていますか。"],
  s2_192: ["I [_____] that we leave early to avoid traffic.", "渋滞を避けるために早めに出発することを提案します。"],
  s2_193: ["Many countries sent [_____] to the earthquake victims.", "多くの国が地震の被災者に援助を送った。"],
  s2_194: ["Our opinions [_____] on this point.", "この点について私たちの意見は異なる。"],
  s2_195: ["The city plans to [_____] a new bridge over the river.", "市は川に新しい橋を建設する予定だ。"],
  s2_196: ["It's [_____] that he survived ten days at sea without food.", "彼が食べ物もなしに10日間も海で生き延びたなんて信じられない。"],
  s2_197: ["He was arrested for [_____].", "彼は殺人の容疑で逮捕された。"],
  s2_198: ["In many birds, the [_____] is more colorful than the female.", "多くの鳥では、雄のほうが雌より色鮮やかだ。"],
  s2_199: ["He [_____]d his speech by thanking everyone.", "彼はみんなに感謝してスピーチを締めくくった。"],
  s2_200: ["[_____] your knees when you lift heavy things.", "重いものを持ち上げるときは膝を曲げなさい。"],
  s2_201: ["The [_____] speed on this road is 60 kilometers an hour.", "この道路の最高速度は時速60キロだ。"],
  s2_202: ["What was your first [_____] of Japan?", "日本の第一印象はどうでしたか。"],
  s2_203: ["Could I have the [_____], please?", "お勘定をお願いします。"],
  s2_204: ["Can you [_____] the man you saw?", "見た男の特徴を説明できますか。"],
  s2_205: ["The bank is on the [_____] side of the street.", "銀行は通りの向こう側にある。"],
  s2_206: ["We use [_____] to give someone a right, often in the passive, as in \"Members are entitled to a discount.\"", "「会員は割引を受ける資格がある」のように、権利や資格を与えることを表します（受け身の形でよく使う）。"],
  s2_207: ["The human body is made of millions of [_____]s.", "人の体は何百万もの細胞でできている。"],
  s2_208: ["Don't [_____] a book by its cover.", "本を表紙で判断してはいけない。"],
  s2_209: ["She [_____]d at her watch.", "彼女はちらりと腕時計を見た。"],
  s2_210: ["Japan is becoming an aging [_____].", "日本は高齢化社会になりつつある。"],
  s2_211: ["We must [_____] the problem instead of running away from it.", "私たちは逃げずにその問題に立ち向かわなければならない。"],
  s2_212: ["The police are working hard to reduce [_____] in the city.", "警察は市内の犯罪を減らそうと懸命に取り組んでいる。"],
  s2_213: ["I [_____] go to bed at eleven, but tonight I'll stay up late.", "普段は11時に寝るが、今夜は夜更かしする。", ["sincerely", "hesitantly", "spiritually"]],
  s2_214: ["Water is [_____] for life.", "水は生命に欠かせない。", ["financial", "industrial", "classical"]],
  s2_215: ["Hurry up; [_____] you'll miss the bus.", "急いで。さもないとバスに乗り遅れるよ。"],
  s2_216: ["The train left at [_____] nine o'clock.", "電車はちょうど9時に出発した。"],
  s2_217: ["The council accepted our [_____] to build a new park.", "議会は新しい公園を造るという私たちの提案を受け入れた。"],
  s2_218: ["Plants give off [_____].", "植物は酸素を出す。"],
  s2_219: ["I want to [_____] on the beach all day.", "一日中浜辺で寝そべっていたい。"],
  s2_220: ["Rainy days are [_____] of June in Japan.", "雨の日は日本の6月によくあることだ。"],
  s2_221: ["Car tires are made of [_____].", "車のタイヤはゴムでできている。"],
  s2_222: ["Our team needs one more win to [_____] for the finals.", "私たちのチームが決勝に進む資格を得るには、あと1勝が必要だ。"],
  s2_223: ["Many parents worry about [_____] in video games.", "多くの親がテレビゲームの中の暴力を心配している。"],
  s2_224: ["Your answer is [_____]; please try again.", "あなたの答えは間違っています。もう一度やってみてください。"],
  s2_225: ["The baby fell [_____] in my arms.", "赤ちゃんは私の腕の中で眠ってしまった。"],
  s2_226: ["After hitting his head, the player was checked for signs of [_____].", "頭を打ったあと、その選手は脳しんとうの兆候がないか検査された。"],
  s2_227: ["One [_____] of living in the country is that there are few buses.", "田舎に住むことの不利な点の1つは、バスが少ないことだ。"],
  s2_228: ["My little brother goes to [_____] while my parents are at work.", "両親が仕事に行っている間、弟は保育園に通っている。"],
  s2_229: ["Please read the instructions on the [_____] side.", "裏面の説明を読んでください。"],
  s2_230: ["Birds build nests for their young. [_____], some fish build nests in the sand.", "鳥はひなのために巣を作る。同様に、砂に巣を作る魚もいる。", ["typically", "terribly", "hesitantly"]],
  s2_231: ["Only [_____] people can afford to live in that area.", "裕福な人しかその地域に住む余裕はない。"],
  s2_232: ["The president will give an official [_____] tomorrow.", "大統領は明日公式声明を出す予定だ。"],
  s2_233: ["My [_____]s came from China hundreds of years ago.", "私の祖先は何百年も前に中国から来た。"],
  s2_234: ["The nurse took some [_____] from my arm.", "看護師は私の腕から採血した。"],
  s2_235: ["I [_____] hope you get well soon.", "一日も早いご回復を心からお祈りしています。"],
  s2_236: ["The telephone was one of the greatest [_____]s in history.", "電話は歴史上最も偉大な発明の一つだった。"],
  s2_237: ["The police are looking into the [_____] that happened last night.", "警察は昨夜起きた事件を調べている。"],
  s2_238: ["Take [_____] you need from the fridge.", "冷蔵庫から必要なものは何でも取っていいよ。"],
  s2_239: ["The police [_____]ed to the public for information about the missing girl.", "警察は行方不明の少女についての情報提供を市民に呼びかけた。"],
  s2_240: ["You should [_____] yourself with the rules before you start.", "始める前に規則をよく知っておくべきだ。"],
  s2_241: ["Osaka is a big [_____] city with many factories.", "大阪は工場の多い大きな工業都市だ。"],
  s2_242: ["His [_____] of the rules caused the trouble.", "彼が規則を知らなかったことがトラブルの原因だった。"],
  s2_243: ["Read the first [_____] on page 10.", "10ページの最初の段落を読みなさい。"],
  s2_244: ["Be [_____] of other people when you use your phone on the train.", "電車で電話を使うときは、周りの人に気を配りなさい。"],
  s2_245: ["Do you have a dinner [_____] for tonight?", "今夜の夕食の予約はしてありますか。"],
  s2_246: ["The teacher will [_____] the test papers.", "先生がテスト用紙を配る。"],
  s2_247: ["My grandparents' [_____] grew up without TV.", "祖父母の世代はテレビなしで育った。"],
  s2_248: ["Parents shouldn't [_____] their own dreams on their children.", "親は自分の夢を子どもに押し付けるべきではない。"],
  s2_249: ["Exercise will [_____] your muscles.", "運動すれば筋肉が強くなる。"],
  s2_250: ["He finally [_____]ed that he had stolen the money.", "彼はついにお金を盗んだことを白状した。"],
  s2_251: ["The wind blew with great [_____].", "風が激しい勢いで吹いた。"],
  s2_252: ["She raised her hand [_____], not sure if her answer was right.", "答えが正しいか自信がなく、彼女はおずおずと手を挙げた。"],
  s2_254: ["English [_____] is difficult for many Japanese students.", "英語の発音は多くの日本人生徒にとって難しい。"],
  s2_255: ["Your question is not [_____] today's topic.", "あなたの質問は今日の話題とは関係がない。"],
  s2_256: ["I don't know [_____] if he will come.", "彼が来るかどうか、はっきりとはわからない。"],
  s2_257: ["A judge must look at the facts [_____].", "裁判官は事実を客観的に見なければならない。"],
  s2_258: ["I can't follow the [_____] of your argument.", "あなたの議論の論理についていけない。"],
  s2_259: ["The audience was [_____] young people.", "聴衆は主に若者だった。"],
  s2_260: ["It's very [_____] today; my clothes feel damp.", "今日はとても蒸し暑く、服が湿っぽく感じる。"],
  s2_261: ["This restaurant has a friendly [_____].", "このレストランは親しみやすい雰囲気だ。"],
  s2_262: ["Noise in the classroom breaks my [_____].", "教室の騒音で集中が途切れる。"],
  s2_263: ["The [_____] clapped loudly at the end of the concert.", "コンサートの最後に観客は大きな拍手をした。"],
  s2_264: ["This medicine tastes [_____].", "この薬はひどい味がする。"],
  s2_265: ["What is the best [_____] for learning new words?", "新しい単語を覚えるのに一番よい方法は何ですか。"],
  s2_266: ["Don't worry; we have [_____] of time.", "心配しないで。時間はたっぷりある。"],
  s2_267: ["The [_____] of the yen went down this year.", "今年は円の価値が下がった。"],
  s2_268: ["My favorite subject is [_____].", "私の好きな教科は理科だ。"],
  s2_269: ["Japan has few natural [_____]s such as oil.", "日本には石油のような天然資源がほとんどない。"],
  s2_270: ["It was just another [_____] day at school.", "学校でのいつもと変わらない一日だった。"],
  s2_271: ["It is becoming [_____] difficult to find a job.", "仕事を見つけるのはますます難しくなっている。"],
  s2_272: ["Freedom and equality are the [_____]s of democracy.", "自由と平等は民主主義の理想だ。"],
  s2_273: ["I saw a dark [_____] standing at the door.", "ドアのところに黒い人影が立っているのが見えた。"],
  s2_274: ["The school's [_____] sports day is held every October.", "学校の毎年恒例の運動会は10月に開かれる。"],
  s2_275: ["Does the price [_____] tax?", "その値段には税金が含まれていますか。"],
  s2_276: ["This rule doesn't [_____] to first-year students.", "この規則は1年生には適用されない。"],
  s2_277: ["He gave a small [_____] to show he agreed.", "彼は同意を示すために小さくうなずいた。"],
  s2_278: ["[_____] it will snow tonight.", "もしかすると今夜は雪が降るかもしれない。"],
  s2_279: ["Chickens [_____] eggs.", "ニワトリは卵を産む。"],
  s2_280: ["The police have the [_____] to stop cars.", "警察には車を止める権限がある。"],
  s2_281: ["Water turns from [_____] to ice when it freezes.", "水は凍ると液体から氷に変わる。"],
  s2_282: ["I [_____] waiting in long lines.", "長い列に並んで待つのは大嫌いだ。"],
  s2_283: ["This [_____] is famous for its apples.", "この地域はりんごで有名だ。"],
  s2_284: ["A high fever is a common [_____] of the flu.", "高熱はインフルエンザのよくある症状だ。"],
  s2_285: ["Come and sit [_____] me.", "こっちに来て、私の隣に座って。"],
  s2_286: ["We live in the [_____] of the internet.", "私たちはインターネットの時代に生きている。"],
  s2_287: ["Milk helps build strong [_____]s.", "牛乳は丈夫な骨を作るのに役立つ。"],
  s2_288: ["There was a long [_____] after she asked the question.", "彼女が質問したあと、長い沈黙があった。"],
  s2_289: ["The bus [_____] is 200 yen.", "バスの運賃は200円だ。"],
  s2_290: ["A friend in need is a friend [_____].", "まさかの時の友こそ真の友。"],
  s2_291: ["The red light [_____]s that the battery is low.", "赤いランプは電池が残り少ないことを示している。"],
  s2_292: ["Don't [_____] at me; I can hear you.", "怒鳴らないで。聞こえているから。"],
  s2_294: ["Many [_____] of animals are in danger of dying out.", "多くの種類の動物が絶滅の危機にある。"],
  s2_295: ["I [_____] tea to coffee.", "私はコーヒーより紅茶のほうが好きだ。"],
  s2_296: ["Students are expected to follow the school's rules of [_____].", "生徒は学校の行動規範に従うことが求められる。"],
  s2_298: ["The pirates buried their [_____] on the island.", "海賊たちは島に宝を埋めた。"],
  s2_299: ["This medicine will [_____] your headache.", "この薬で頭痛が和らぐでしょう。"],
  s2_300: ["Cover your mouth when you [_____].", "せきをするときは口を覆いなさい。"],
  s2_301: ["[_____] rose after many factories closed.", "多くの工場が閉鎖され、失業が増えた。"],
  s2_302: ["Did you [_____] anything strange about him?", "彼について何か変なことに気づきましたか。"],
  s2_303: ["The road is too [_____] for two cars to pass.", "その道は狭すぎて2台の車がすれ違えない。"],
  s2_304: ["Be [_____]; you can't expect to learn a language in one week.", "分別を持ちなさい。1週間で言語を身につけられるはずがない。"],
  s2_305: ["People once believed the earth was [_____].", "かつて人々は地球は平らだと信じていた。"],
  s2_306: ["He climbed the [_____] to fix the roof.", "彼は屋根を直すためにはしごを登った。"],
  s2_307: ["University [_____] in Japan is expensive.", "日本の大学の授業料は高い。"],
  s2_308: ["The plane's [_____] made sure everyone was wearing a seat belt.", "飛行機の乗務員は全員がシートベルトをしているか確かめた。"],
  s2_309: ["This shop sells Japanese [_____]s such as tea and rice crackers.", "この店はお茶やせんべいのような日本の製品を売っている。"],
  s2_310: ["Are you [_____]? It's too cold to swim!", "正気なの？泳ぐには寒すぎるよ！"],
  s2_311: ["Look up the [_____] of this word in the dictionary.", "辞書でこの単語の定義を調べなさい。"],
  s2_312: ["Her [_____] to arrive late annoys her friends.", "彼女は遅れてくる傾向があるので、友人たちは困っている。"],
  s2_313: ["She has a very [_____] voice; you can recognize it right away.", "彼女はとても特徴のある声をしていて、すぐにそれとわかる。"],
  s2_314: ["The noise outside [_____]ed me from my studies.", "外の騒音で勉強に集中できなかった。"],
  s2_315: ["A thin [_____] of dust covered the old books.", "古い本には薄くほこりが積もっていた。"],
  s2_316: ["Japan gets some of its electricity from [_____] power plants.", "日本は電力の一部を原子力発電所から得ている。"],
  s2_317: ["My grandmother is full of [_____].", "祖母は知恵にあふれている。"],
  s2_318: ["Quality is more important than [_____].", "量より質が大切だ。"],
  s2_319: ["The new sports [_____] has a pool and a gym.", "新しいスポーツ施設にはプールとジムがある。"],
  s2_320: ["The report is [_____] next Monday.", "レポートの締め切りは来週の月曜日だ。"],
  s2_321: ["The lake [_____]ed the mountains like a mirror.", "湖は鏡のように山々を映していた。"],
  s2_322: ["Please tell me the [_____].", "本当のことを教えてください。"],
  s2_323: ["You [_____] apologize to her.", "あなたは彼女に謝るべきだ。"],
  s2_324: ["Your skin will burn if it is [_____] to the sun too long.", "肌は日光に長く当たりすぎると日焼けする。"],
  s2_325: ["Copper is a good [_____] of electricity.", "銅は電気の良導体だ。"],
  s2_326: ["The [_____] of the pool is two meters.", "プールの深さは2メートルだ。"],
  s2_327: ["Fish are [_____] in this river.", "この川には魚がたくさんいる。"],
  s2_328: ["The Roman [_____] lasted for hundreds of years.", "ローマ帝国は何百年も続いた。"],
  s2_329: ["Japan has many [_____] mountains, such as Mount Fuji.", "日本には富士山のような火山がたくさんある。"],
  s2_330: ["The museum [_____]s old samurai swords.", "その博物館は昔の侍の刀を展示している。"],
  s2_331: ["The bridge was closed; [_____], we had to take a long way around.", "橋が閉鎖されていた。そのため、遠回りしなければならなかった。"],
  s2_332: ["It's [_____] to finish all this work in one day.", "この仕事を全部1日で終えるのは不可能だ。"],
  s2_335: ["The [_____] of this building can survive a strong earthquake.", "この建物の構造は強い地震にも耐えられる。"],
  s2_336: ["Many people [_____] the color red with danger.", "多くの人は赤い色を危険と結びつけて考える。"],
  s2_337: ["The Spanish [_____] of the Aztec Empire happened in the 1500s.", "スペインによるアステカ帝国の征服は1500年代に起こった。"],
  s2_338: ["This phone plan gives you [_____] data.", "この携帯のプランならデータが使い放題だ。"],
  s2_339: ["Water [_____]s of hydrogen and oxygen.", "水は水素と酸素から成る。"],
  s2_340: ["The [_____] of students walk to school.", "生徒の大多数は歩いて通学している。"],
  s2_341: ["The surface of this rock is [_____].", "この岩の表面はざらざらしている。"],
  s2_342: ["Henry Ford made the [_____] cheap enough for ordinary people.", "ヘンリー・フォードは自動車を普通の人でも買えるほど安くした。"],
  s2_345: ["It's [_____] for him to be late; he is usually on time.", "彼が遅れるのは珍しい。いつもは時間どおりなのに。"],
  s2_346: ["In the end, justice will [_____].", "最後には正義が勝つ。"],
  s2_347: ["Your idea is based on the [_____] that prices will not rise.", "あなたの考えは物価が上がらないという仮定に基づいている。"],
  s2_348: ["She is a member of the parents' [_____] at our school.", "彼女は私たちの学校の保護者会の会員だ。"],
  s2_349: ["Vitamin [_____] can make you feel tired.", "ビタミンが不足すると疲れを感じることがある。"],
  s2_350: ["Because of the water [_____], we can only take short showers.", "水不足のため、短時間しかシャワーを浴びられない。"],
  s2_351: ["Trees are [_____] in the desert.", "砂漠では木がまばらだ。"],
  s2_352: ["Let's [_____] the bill between the three of us.", "3人で勘定を割り勘にしよう。"],
  s2_353: ["Abraham Lincoln worked to free the [_____]s.", "エイブラハム・リンカーンは奴隷の解放に努めた。"],
  s2_354: ["The [_____] produces grapes for wine.", "そのブドウ園はワイン用のブドウを生産している。"],
  s2_355: ["The [_____] fields get water from the river through small canals.", "灌漑された畑は小さな水路を通じて川から水を引いている。"],
  s2_356: ["Gold [_____] was used in Japan in the Edo period.", "江戸時代の日本では金貨が使われていた。"],
  s2_357: ["The twins look [_____]; I can't tell them apart.", "その双子は瓜二つで、見分けがつかない。"],
  s2_358: ["We should [_____] solar energy more.", "私たちは太陽エネルギーをもっと利用すべきだ。"],
  s2_359: ["We will do our [_____] to help you.", "お役に立てるよう最善を尽くします。"],
  s2_360: ["The [_____]s in America fought for independence from Britain.", "アメリカの植民地の人々はイギリスからの独立を求めて戦った。"],
  s2_361: ["The company's [_____] of a smaller rival made it the biggest in Japan.", "小さなライバル社を買収して、その会社は日本最大になった。"],
  s2_362: ["This problem needs [_____] action.", "この問題にはすぐに対処する必要がある。"],
  s2_364: ["Under no [_____]s should you open this door.", "どんな状況でもこのドアを開けてはならない。"],
  s2_365: ["The internet [_____]s us to talk with people around the world.", "インターネットのおかげで、世界中の人と話すことができる。"],
  s2_366: ["Many young people are leaving [_____] areas for big cities.", "多くの若者が農村地域を離れて大都市へ移っている。"],
  s2_367: ["We had a long [_____] about the school trip.", "私たちは修学旅行について長い話し合いをした。"],
  s2_368: ["We saw dolphins and sharks at the [_____].", "水族館でイルカとサメを見た。"],
  s2_369: ["I bought some [_____]s for my family in Kyoto.", "京都で家族にお土産をいくつか買った。"],
  s2_370: ["Who is the [_____] of this book?", "この本の著者は誰ですか。"],
  s2_371: ["The [_____]s found a new way to treat the disease.", "研究者たちはその病気の新しい治療法を見つけた。"],
  s2_372: ["The hotel is in a great [_____], close to the beach.", "そのホテルは浜辺に近い、絶好の場所にある。"],
  s2_373: ["Our school decided to [_____] uniforms.", "私たちの学校は制服を廃止することにした。"],
  s2_374: ["[_____] when you cross the street.", "通りを渡るときは気をつけて。"],
  s2_375: ["Don't [_____] your health just because you are busy.", "忙しいからといって健康をおろそかにしてはいけない。"],
  s2_376: ["Under the new law, all drivers will [_____] wear seat belts.", "新しい法律では、すべての運転者にシートベルトの着用が義務付けられる。"],
  s2_378: ["Thanks to your [_____]s, we were able to build a new library.", "皆さんのご寄付のおかげで、新しい図書館を建てることができました。"],
  s2_379: ["The museum will [_____] paintings by Monet next month.", "その美術館は来月モネの絵を展示する。"],
  s2_380: ["Rice is the [_____] food of Japan.", "米は日本の主要な食べ物だ。"],
  s2_381: ["[_____], we need more money.", "要するに、もっとお金が必要なのだ。"],
  s2_382: ["You should wear [_____] clothes to the wedding.", "結婚式には正装で行くべきだ。"],
  s2_383: ["After a lot of [_____], my father let me go to the concert.", "さんざん説得して、父はやっとコンサートに行かせてくれた。"],
  s2_384: ["Elephants are [_____] animals.", "ゾウは巨大な動物だ。"],
  s2_385: ["Many birds [_____] south for the winter.", "多くの鳥は冬になると南へ渡る。"],
  s2_386: ["Her answer was clear and [_____].", "彼女の答えは明確で論理的だった。"],
  s2_387: ["How do you [_____] this poem?", "この詩をどう解釈しますか。"],
  s2_388: ["The [_____] of this clock is amazing; it loses only one second a year.", "この時計の精度は驚くほどで、1年に1秒しか狂わない。"],
  s2_389: ["She made a great [_____] to science.", "彼女は科学に大きく貢献した。"],
  s2_390: ["We plan to [_____] Mount Fuji this summer.", "この夏、富士山に登る予定だ。"],
  s2_391: ["Please [_____] when your name is called.", "名前を呼ばれたら立ってください。"],
  s2_392: ["Strawberry [_____]s are delicious on toast.", "いちごのジャムはトーストに塗るとおいしい。"],
  s2_393: ["I do the [_____] every Saturday.", "私は毎週土曜日に洗濯をする。"],
  s2_394: ["Many workers [_____] back pain.", "多くの労働者が腰痛を訴えている。"],
  s2_395: ["I'm taking a two-week [_____] English course this summer.", "この夏、2週間の英語の集中講座を受ける。"],
  s2_396: ["Let me [_____] my notes before the test.", "テストの前にノートにひと通り目を通させて。"],
  s2_397: ["We have a small [_____] for the school festival.", "文化祭の予算は少ない。"],
  s2_398: ["The museum has an Egyptian [_____] that is 3,000 years old.", "その博物館には3,000年前のエジプトのミイラがある。"],
  s2_400: ["We [_____] eat out, maybe once a month.", "私たちはたまに外食する。月に1回くらいだ。"],
  s2_401: ["[_____] the flour and sugar in a bowl.", "ボウルで小麦粉と砂糖を混ぜ合わせなさい。"],
  s2_402: ["I didn't mean to [_____] that you were lying.", "あなたがうそをついているとほのめかすつもりはなかった。", ["renew", "worry", "amuse"]],
  s2_404: ["Don't be [_____]! Dogs can't talk.", "ばかなことを言わないで！犬が話せるわけがない。"],
  s2_405: ["He [_____]d me when I said hello.", "あいさつしたのに彼は私を無視した。"],
  s2_406: ["Whales are [_____]s, not fish.", "クジラは魚ではなく哺乳類だ。"],
  s2_407: ["We use [_____] to say who caused something bad, as in \"They blamed the driver for the accident.\"", "「彼らはその事故を運転手のせいにした」のように、悪いことの責任を誰かに負わせるときに使います。"],
  s2_408: ["Scientists found a dinosaur [_____] in the rock.", "科学者たちは岩の中に恐竜の化石を見つけた。"],
  s2_409: ["It was [_____] that he was lying.", "彼がうそをついているのは明らかだった。"],
  s2_410: ["Can you give me the [_____] time? My watch has stopped.", "正確な時刻を教えてもらえますか。私の時計は止まってしまいました。"],
  s2_411: ["We stayed up to [_____] the new year.", "私たちは新年を迎えるために夜更かしした。"],
  s2_412: ["My parents had a big [_____] about money.", "両親はお金のことで大げんかをした。"],
  s2_413: ["The movie is [_____] beautiful, but the story is boring.", "その映画は映像は美しいが、話はつまらない。"],
  s2_414: ["I'm [_____] sorry I'm late.", "遅れて本当に申し訳ありません。"],
  s2_415: ["Don't be afraid to [_____] your dreams.", "恐れずに夢を追いかけなさい。"],
  s2_416: ["She is shy [_____].", "彼女は生まれつき内気だ。"],
  s2_417: ["Which [_____] is the station?", "駅はどちらの方向ですか。"],
  s2_418: ["Customs in Japan [_____] those in America.", "日本の習慣はアメリカのものとは異なる。"],
  s2_419: ["The news will [_____] everyone.", "その知らせにはみんなが驚くだろう。"],
  s2_420: ["[_____] the cake into eight pieces.", "ケーキを8つに切り分けなさい。"],
  s2_421: ["You should sleep [_____] seven hours a night.", "一晩に少なくとも7時間は眠るべきだ。"],
  s2_422: ["Put everything back [_____] after you use it.", "使ったら全部元の場所に戻しなさい。"],
  s2_424: ["A deep [_____] appeared on his face when he heard the news.", "その知らせを聞くと、彼は顔をしかめた。"],
  s2_425: ["I'm interested in Japanese [_____], such as tea ceremony.", "私は茶道のような日本の文化に興味がある。"],
  s2_426: ["She worked hard to [_____] her fear of water.", "彼女は水への恐怖を克服しようと努力した。"],
  s2_427: ["Her story [_____]d me to become a nurse.", "彼女の話に刺激を受けて、私は看護師になろうと思った。"],
  s2_428: ["She won first [_____] in the contest.", "彼女はコンテストで1等賞を取った。"],
  s2_429: ["Finishing the marathon was her greatest [_____].", "マラソンを完走したことが彼女の最大の成果だった。"],
  s2_430: ["We live in a quiet [_____] of Tokyo.", "私たちは東京の静かな郊外に住んでいる。"],
  s2_431: ["He had to [_____] his heavy suitcase up the stairs.", "彼は重いスーツケースを引きずって階段を上がらなければならなかった。"],
  s2_432: ["This water is rich in [_____]s such as calcium.", "この水にはカルシウムなどのミネラルが豊富に含まれている。"],
  s2_433: ["The bird [_____]d from its cage.", "鳥がかごから逃げ出した。"],
  s2_434: ["The stars [_____] at night.", "夜になると星が出る。"],
  s2_435: ["My hands began to [_____] when I stood on the stage.", "舞台に立つと手が震え始めた。"],
  s2_436: ["Don't [_____] too late; you have school tomorrow.", "夜更かししすぎないで。明日は学校があるでしょう。"],
  s2_437: ["Is this bag made of [_____] leather?", "このかばんは本革でできていますか。"],
  s2_438: ["If you [_____] any new words, look them up.", "知らない単語に出くわしたら調べなさい。"],
  s2_439: ["Don't worry [_____]; everything will be fine.", "必要以上に心配しないで。すべてうまくいくから。"],
  s2_440: ["I helped him with math, and [_____] he taught me guitar.", "私は彼に数学を教え、その代わりに彼はギターを教えてくれた。"],
  s2_441: ["Please turn off your phone [_____] the movie.", "映画の上映中は携帯電話の電源を切ってください。"],
  s2_442: ["Japan is made up of many [_____]s.", "日本は多くの島から成り立っている。"],
  s2_443: ["This land is private [_____]; you can't enter.", "この土地は私有地なので入ることはできない。"],
  s2_444: ["He is [_____], so he uses sign language.", "彼は耳が聞こえないので手話を使う。"],
  s2_445: ["The Mona Lisa is Leonardo da Vinci's [_____].", "モナ・リザはレオナルド・ダ・ヴィンチの傑作だ。"],
  s2_446: ["This train is [_____] Osaka.", "この電車は大阪行きだ。"],
  s2_447: ["Sorry, we don't have that size [_____].", "申し訳ありませんが、そのサイズは在庫がありません。"],
  s2_448: ["[_____] to the museum is free on Sundays.", "日曜日はその博物館の入場が無料だ。"],
  s2_449: ["My father will [_____] at 65.", "父は65歳で退職する。"],
  s2_450: ["The mail carrier [_____]s letters every morning.", "郵便配達員は毎朝手紙を配達する。"],
  s2_451: ["Can you [_____] a map to your house?", "あなたの家までの地図を描いてもらえますか。"],
  s2_452: ["My father works at a car [_____].", "父は自動車工場で働いている。"],
  s2_453: ["The artist [_____]d a huge painting of the sea.", "その画家は海を描いた巨大な絵を制作した。"],
  s2_454: ["Climate change is a serious [_____] to many animals.", "気候変動は多くの動物にとって深刻な脅威だ。"],
  s2_455: ["Bananas grow in [_____] countries.", "バナナは熱帯の国々で育つ。"],
  s2_456: ["Acid can [_____] metal and damage it.", "酸は金属に作用して傷めることがある。"],
  s2_457: ["After the accident, she needed physical [_____] to walk again.", "事故のあと、彼女は再び歩けるようになるために理学療法が必要だった。"],
  s2_458: ["Scientists are trying to [_____] why bees are disappearing.", "科学者たちはミツバチが減っている理由を調査しようとしている。"],
  s2_459: ["This is only the first [_____] of my essay.", "これは私の作文の最初の下書きにすぎない。"],
  s2_460: ["The book has many colorful [_____]s.", "その本にはカラフルな挿絵がたくさんある。"],
  s2_461: ["The [_____] of the city gave a speech at the festival.", "市長が祭りでスピーチをした。"],
  s2_462: ["I go to the [_____] twice a year to have my teeth checked.", "私は年に2回、歯の検診のために歯医者に行く。"],
  s2_463: ["As [_____] for being late, he had to clean the classroom.", "遅刻の罰として、彼は教室を掃除しなければならなかった。"],
  s2_464: ["The police officer was [_____], but he still helped the injured man.", "その警察官は非番だったが、それでもけが人を助けた。"],
  s2_465: ["The [_____] of penicillin saved millions of lives.", "ペニシリンの発見は何百万もの命を救った。"],
  s2_466: ["I will love you [_____].", "いつまでもあなたを愛します。"],
  s2_467: ["The sign [_____]s people not to swim here.", "その看板はここで泳がないよう人々に警告している。"],
  s2_468: ["I'll bring some extra money [_____].", "念のため、少し多めにお金を持っていく。"],
  s2_469: ["In my [_____], this is the best restaurant in town.", "私の意見では、ここが町で一番のレストランだ。"],
  s2_471: ["Please [_____] that all the windows are closed.", "窓が全部閉まっていることを必ず確かめてください。"],
  s2_472: ["I was [_____] asking a question; I didn't mean to be rude.", "ただ質問していただけで、失礼なことをするつもりはなかった。"],
  s2_473: ["She screamed in [_____] when she saw the snake.", "彼女はヘビを見て恐怖で悲鳴を上げた。"],
  s2_474: ["Stop it! You're starting to [_____] me.", "やめて！だんだんイライラしてきたよ。", ["unify", "smell", "renew"]],
  s2_475: ["Writing stories helps children develop [_____] thinking.", "物語を書くことは、子どもの創造的な思考を育てるのに役立つ。"],
  s2_476: ["Marriage is a lifelong [_____].", "結婚は一生の約束だ。"],
  s2_477: ["The judges praised her painting for its [_____].", "審査員は彼女の絵の独創性をほめた。"],
  s2_478: ["Go ahead; I'll [_____] you later.", "先に行って。あとで追いつくから。"],
  s2_479: ["The company is in [_____] trouble and may close.", "その会社は財政難で、閉鎖するかもしれない。"],
  s2_480: ["The factory increased its [_____] by 20 percent.", "その工場は生産量を20パーセント増やした。"],
  s2_481: ["Your teacher's [_____] of your work will be sent home.", "先生によるあなたの作品の評価は家に送られます。"],
  s2_482: ["Einstein was a genius in [_____].", "アインシュタインは物理学の天才だった。"],
  s2_483: ["Please don't [_____] in my private life.", "私生活に干渉しないでください。"],
  s2_484: ["I don't know [_____] he will come or not.", "彼が来るかどうかわからない。"],
  s2_485: ["Who is your [_____] singer?", "好きな歌手は誰ですか。"],
  s2_486: ["He borrowed money and is now in [_____].", "彼はお金を借りて、今は借金を抱えている。"],
  s2_487: ["I had a long [_____] with my grandfather last night.", "昨夜、祖父と長い会話をした。"],
  s2_488: ["She was chosen as the class [_____] for the student council.", "彼女は生徒会のクラス代表に選ばれた。"],
  s2_489: ["Is there any [_____] between sleep and memory?", "睡眠と記憶には何か関係がありますか。"],
  s2_490: ["Reading is one of my greatest [_____]s.", "読書は私の最大の楽しみの一つだ。"],
  s2_491: ["Each area has its own [_____] dishes.", "各地域にはそれぞれの郷土料理がある。"],
  s2_492: ["This watch is too [_____] for me to buy.", "この腕時計は高すぎて私には買えない。"],
  s2_493: ["The old books were covered in [_____].", "古い本はほこりをかぶっていた。"],
  s2_494: ["The sun is our main [_____] of energy.", "太陽は私たちの主なエネルギー源だ。"],
  s2_495: ["The campaign aims to raise [_____] of the dangers of smoking.", "その運動は喫煙の危険性に対する意識を高めることを目指している。"],
  s2_496: ["The castle has [_____] gardens with fountains and statues.", "その城には噴水や彫像のある壮大な庭園がある。"],
  s2_497: ["The injured man was taken to the hospital by [_____].", "けがをした男性は救急車で病院に運ばれた。"],
  s2_498: ["Please be [_____]ed; the show is about to begin.", "ご着席ください。まもなくショーが始まります。"],
  s2_499: ["The mother looked at her baby with great [_____].", "母親は深い愛情を込めて赤ちゃんを見つめた。"],
  s2_500: ["I learned the poem [_____].", "私はその詩を暗記した。"],
  s2_501: ["Bad weather will [_____] our problems.", "悪天候で問題はさらに増えるだろう。"],
  s2_502: ["Making paper by hand is a traditional Japanese [_____].", "手で紙をすくのは日本の伝統工芸だ。"],
  s2_503: ["Please write your name, age, and [_____] on the form.", "用紙に氏名、年齢、職業を書いてください。"],
  s2_504: ["It [_____] takes about an hour to get there.", "そこへ行くには普通1時間ほどかかる。"],
  s2_505: ["Law [_____] officers arrested the suspect.", "法執行官が容疑者を逮捕した。"],
  s2_506: ["I couldn't [_____] her to change her mind.", "私は彼女に考えを変えるよう納得させることができなかった。"],
  s2_507: ["The company [_____]ed my application.", "その会社は私の応募を断った。"],
  s2_508: ["Children are [_____] on their parents.", "子どもは親に頼っている。"],
  s2_509: ["Let's [_____] this pizza.", "このピザを分けよう。"],
  s2_510: ["The new law is very [_____]; people are arguing about it.", "新しい法律は物議を醸していて、人々が議論している。"],
  s2_511: ["Police [_____]s searched the room for evidence.", "警察の捜査官が証拠を求めて部屋を捜索した。"],
  s2_512: ["This game is [_____] for our team; if we lose, we're out.", "この試合は私たちのチームにとって重要だ。負ければ敗退だ。"],
  s2_513: ["This problem [_____]s all of us.", "この問題は私たち全員に関係がある。"],
  s2_514: ["We searched for the lost key, but [_____].", "なくした鍵を探したが、無駄だった。"],
  s2_515: ["[_____] to the news, the typhoon is coming.", "ニュースによると、台風が近づいている。"],
  s2_516: ["They are going to [_____] the old stadium and build a new one.", "古いスタジアムを取り壊して新しいものを建てる予定だ。", ["look over", "maintain", "use up"]],
  s2_517: ["He was still [_____] when the ambulance arrived.", "救急車が到着したとき、彼はまだ意識があった。"],
  s2_518: ["I didn't [_____] how late it was.", "もうそんなに遅い時間だとは気づかなかった。"],
  s2_519: ["Women need equal [_____] in parliament.", "女性は議会で平等に代表される必要がある。"],
  s2_520: ["I'm not [_____] ready yet; give me five more minutes.", "まだ完全には準備ができていないんだ。あと5分待って。", ["equally", "hardly", "visually"]],
  s2_521: ["This area is mostly [_____] land with rice fields.", "この地域は田んぼの広がる農地がほとんどだ。"],
  s2_522: ["Teaching small children takes a lot of [_____].", "小さい子どもに教えるにはかなりの忍耐が必要だ。"],
  s2_523: ["I can't [_____] where I put my keys.", "鍵をどこに置いたか思い出せない。"],
  s2_524: ["Many [_____]s were killed in the war, not just soldiers.", "戦争では兵士だけでなく多くの民間人が亡くなった。"],
  s2_525: ["She has a strong [_____] to travel around the world.", "彼女は世界中を旅したいという強い願望を持っている。"],
  s2_526: ["Be [_____] with the baby.", "赤ちゃんには優しく接してね。"],
  s2_527: ["[_____] out the candles on your cake!", "ケーキのろうそくを吹き消して！"],
  s2_528: ["If you don't study, you will [_____] the exam.", "勉強しないと試験に落ちるよ。"],
  s2_529: ["Over 100 people will [_____] the meeting.", "100人以上がその会議に出席する。"],
  s2_530: ["The [_____] will decide on the plan next week.", "委員会が来週その計画について決定する。"],
  s2_531: ["To some [_____], I agree with you.", "ある程度はあなたに賛成だ。"],
  s2_532: ["Her [_____] is paid on the 25th of every month.", "彼女の給料は毎月25日に支払われる。"],
  s2_533: ["Love and freedom are [_____] ideas.", "愛や自由は抽象的な概念だ。"],
  s2_534: ["The [_____] of elderly people in Japan is growing.", "日本の高齢者の割合は増えている。"],
  s2_535: ["This airport is for [_____] flights only.", "この空港は国内線専用だ。"],
  s2_536: ["The government has a huge budget [_____].", "政府は巨額の財政赤字を抱えている。"],
  s2_537: ["Our main [_____] is to win the championship.", "私たちの主な目標は優勝することだ。"],
  s2_538: ["The city has many [_____] restaurants, such as Thai and Indian.", "その町にはタイ料理やインド料理などの民族料理店がたくさんある。"],
  s2_539: ["After ten years in Hokkaido, she seems to [_____] the cold.", "北海道で10年暮らして、彼女は寒さに慣れているようだ。", ["relevant to", "do away with", "in vain"]],
  s2_540: ["The team made [_____] progress this year.", "チームは今年ものすごく進歩した。"],
  s2_541: ["The [_____] shows that it is 30 degrees.", "温度計は30度を示している。"],
  s2_542: ["I need to [_____] my computer's software.", "パソコンのソフトを更新する必要がある。"],
  s2_543: ["My parents [_____] when I come home late.", "私が遅く帰ると両親は心配する。"],
  s2_544: ["The shop sells a wide [_____] goods.", "その店は幅広い種類の商品を売っている。"],
  s2_545: ["Please wait and speak [_____], not all at once.", "一斉にではなく、順番に話してください。"],
  s2_546: ["The [_____] mayor took over while the mayor was sick.", "市長が病気の間、副市長が代わりを務めた。"],
  s2_547: ["This hotel is clean and [_____], only 3,000 yen a night.", "このホテルは清潔で安く、1泊たった3,000円だ。"],
  s2_548: ["The teacher [_____]d her for her hard work.", "先生は彼女の努力をほめた。"],
  s2_549: ["I saw a TV [_____] for the new game.", "新しいゲームのテレビ広告を見た。"],
  s2_550: ["I'd like to speak to the [_____] of this store.", "この店の責任者と話したいのですが。"],
  s2_551: ["Students from far away live in the school [_____].", "遠くから来た生徒は学校の寮に住んでいる。"],
  s2_552: ["People of different cultures live in [_____] in this town.", "この町では異なる文化の人々が仲良く暮らしている。"],
  s2_553: ["She beat her [_____] in the tennis final.", "彼女はテニスの決勝で対戦相手を破った。"],
  s2_554: ["Is he [_____] your brother? You don't look alike at all.", "彼は本当にあなたのお兄さんなの？全然似ていないね。"],
  s2_555: ["Electric cars are quieter than [_____] cars.", "電気自動車は従来の車より静かだ。"],
  s2_556: ["What was her [_____] when you told her the news?", "その知らせを伝えたとき、彼女の反応はどうだった？"],
  s2_557: ["Don't run in the [_____].", "廊下を走ってはいけない。"],
  s2_558: ["He [_____]d to her on the beach.", "彼は浜辺で彼女にプロポーズした。"],
  s2_559: ["Eating to [_____] is bad for your health.", "食べすぎは健康に悪い。"],
  s2_560: ["In [_____] years, more people have started working from home.", "近年、自宅で働き始める人が増えている。"],
  s2_561: ["Our tour [_____] showed us around the old town.", "ツアーガイドが旧市街を案内してくれた。"],
  s2_562: ["Starting a new business is a risky [_____].", "新しく事業を始めるのは危険を伴う冒険だ。"],
  s2_563: ["He was so angry that he wanted to [_____] the letter into pieces.", "彼はとても腹が立って、手紙をびりびりに破りたくなった。"],
  s2_564: ["He is so [_____] that he looks in the mirror all the time.", "彼はうぬぼれが強く、いつも鏡を見ている。"],
  s2_565: ["Can you [_____] between a crow and a raven?", "カラスとワタリガラスを見分けられますか。"],
  s2_567: ["The government sent [_____]s to help after the earthquake.", "政府は地震のあと救援のため部隊を派遣した。"],
  s2_568: ["[_____] the screen twice to open the app.", "アプリを開くには画面を2回軽くたたいてください。"],
  s2_569: ["He couldn't play in the game because of a knee [_____].", "彼は膝のけがのため試合に出られなかった。"],
  s2_570: ["The heat in the desert was [_____].", "砂漠の暑さは強烈だった。"],
  s2_571: ["It's hard to [_____] my feelings in English.", "英語で気持ちを表現するのは難しい。"],
  s2_572: ["I really [_____] your help.", "助けていただいて本当に感謝しています。"],
  s2_573: ["The baby monkey [_____]s to its mother's back.", "子ザルは母親の背中にしがみついている。"],
  s2_574: ["Stress can cause [_____] problems such as depression.", "ストレスはうつ病のような心理的な問題を引き起こすことがある。"],
  s2_575: ["You should reduce your salt [_____].", "塩分の摂取量を減らしたほうがいい。"],
  s2_576: ["The children love to [_____] down the hill on their sleds.", "子どもたちはそりで丘を滑り降りるのが大好きだ。"],
  s2_577: ["My New Year's [_____] is to read one book a month.", "私の新年の決意は、月に1冊本を読むことだ。"],
  s2_579: ["It's no [_____] at all; I'm happy to help.", "全然面倒じゃないよ。喜んで手伝うよ。"],
  s2_580: ["The [_____] of Liberty stands in New York.", "自由の女神像はニューヨークに立っている。"],
  s2_581: ["Please [_____] your report by Friday.", "金曜日までにレポートを提出してください。"],
  s2_582: ["Water is leaking through a small [_____] in the wall.", "壁の小さなひびから水が漏れている。"],
  s2_583: ["The old bridge is [_____] falling down.", "その古い橋は崩れ落ちる危険がある。"],
  s2_584: ["She is very [_____] for her age.", "彼女は年の割にとても大人びている。"],
  s2_585: ["I'm interested in Japanese [_____], especially the Edo period.", "私は日本の歴史、特に江戸時代に興味がある。"],
  s2_586: ["We communicate [_____] language.", "私たちは言葉によって意思を伝え合う。"],
  s2_587: ["All passengers are [_____]d to wear seat belts.", "乗客は全員シートベルトの着用が求められる。"],
  s2_588: ["The nurse [_____]ed the doctor during the operation.", "看護師は手術の間、医師を補助した。"],
  s2_589: ["This coffee tastes [_____].", "このコーヒーは苦い。"],
  s2_590: ["She spoke in a calm [_____].", "彼女は落ち着いた態度で話した。"],
  s2_591: ["Please [_____] the beds before the guests arrive.", "お客さんが来る前にベッドを整えてください。"],
  s2_592: ["Over 200 runners will [_____] in the race.", "200人以上の走者がそのレースで競う。"],
  s2_593: ["It took him a month to [_____] from the flu.", "彼がインフルエンザから回復するのに1か月かかった。"],
  s2_594: ["Lower taxes may [_____] the economy.", "減税は経済を刺激するかもしれない。"],
  s2_595: ["Blood [_____]s carry blood around the body.", "血管は体中に血液を運ぶ。"],
  s2_596: ["I was [_____] because there was nothing to do.", "何もすることがなかったので退屈だった。"],
  s2_597: ["The Red Cross is an international [_____] that helps people in need.", "赤十字は困っている人を助ける国際的な組織だ。"],
  s2_598: ["The rules are [_____]: no phones, no food, and no talking.", "規則は次のとおりだ。携帯電話禁止、飲食禁止、私語禁止。"],
  s2_599: ["Voting is an important part of any [_____] country.", "投票はどの民主主義国家にとっても重要な要素だ。"],
  s2_600: ["Thank you for your [_____].", "ご協力ありがとうございます。"],
  s2_601: ["Good [_____] is important for growing children.", "成長期の子どもには十分な栄養が大切だ。"],
  s2_602: ["Many people came to the city to [_____] work.", "多くの人が仕事を求めて都会に来た。"],
  s2_603: ["After days of [_____] at sea, the sailors were rescued.", "何日も海を漂流したあと、船員たちは救助された。"],
  s2_604: ["The [_____]s of the campfire kept us warm.", "キャンプファイヤーの炎で私たちは暖まった。"],
  s2_605: ["The government [_____]d a state of emergency after the earthquake.", "政府は地震のあと緊急事態を宣言した。"],
  s2_606: ["[_____] is free for orders over 3,000 yen.", "3,000円以上のご注文は配送料無料です。"],
  s2_607: ["My brother is studying law at [_____].", "兄は大学で法律を学んでいる。"],
  s2_608: ["Kindness is one of her many [_____]s.", "優しさは彼女の多くの長所の一つだ。"],
  s2_609: ["He decided to [_____] his money in a new company.", "彼はお金を新しい会社に投資することにした。"],
  s2_610: ["Her brave action is [_____] praise.", "彼女の勇敢な行動は称賛に値する。"],
  s2_611: ["She did well [_____] and also in sports.", "彼女は学業でもスポーツでも好成績を収めた。"],
  s2_612: ["It's not [_____]! He got more cake than me.", "ずるい！彼のほうがケーキを多くもらった。"],
  s2_613: ["Sleep is [_____] for good health.", "睡眠は健康に欠かせない。"],
  s2_614: ["He has visited Kyoto on [_____] occasions.", "彼は何度も京都を訪れている。"],
  s2_615: ["The [_____] said the man was guilty, but the jury did not agree.", "検察側は男が有罪だと主張したが、陪審は同意しなかった。"],
  s2_616: ["I [_____] I'm telling the truth.", "誓って本当のことを言っています。"],
  s2_617: ["[_____]s study the past to understand the present.", "歴史家は現在を理解するために過去を研究する。"],
  s2_618: ["Customer [_____] is our top priority.", "お客様の満足が私たちの最優先事項です。"],
  s2_619: ["I have no [_____] of what you are talking about.", "あなたが何の話をしているのか見当もつかない。"],
  s2_620: ["Without the doctor's quick [_____], the patient would have died.", "医師が素早く処置しなければ、その患者は亡くなっていただろう。"],
  s2_621: ["The meal cost 5,000 yen [_____].", "食事代は全部で5,000円だった。"],
  s2_622: ["Thank you for the [_____] to your party.", "パーティーにご招待いただき、ありがとうございます。"],
  s2_623: ["Please [_____] these papers together.", "これらの書類をクリップで留めてください。"],
  s2_624: ["Curiosity is a common [_____] among scientists.", "好奇心は科学者に共通する特性だ。"],
  s2_625: ["Many young players [_____] him as a hero.", "多くの若い選手が彼を英雄として尊敬している。"],
  s2_626: ["You must go through [_____] when you arrive at the airport.", "空港に着いたら入国審査を通らなければならない。"],
  s2_628: ["The witness gave the police a detailed [_____] of the thief.", "目撃者は警察に泥棒の特徴を詳しく説明した。"],
  s2_629: ["I like listening to [_____] music, especially Mozart.", "私はクラシック音楽、特にモーツァルトを聴くのが好きだ。"],
  s2_630: ["Her memory will [_____] in our hearts.", "彼女の思い出は私たちの心の中で生き続けるだろう。"],
  s2_631: ["Experts will [_____] the damage caused by the storm.", "専門家が嵐による被害を評価する。"],
  s2_632: ["He ate the [_____] cake by himself.", "彼はケーキを丸ごと一人で食べた。"],
  s2_633: ["If you [_____] being late, you will lose your job.", "遅刻し続けると、仕事を失うことになる。"],
  s2_634: ["The king's [_____] was at the top of the tower.", "王の部屋は塔の最上階にあった。"],
  s2_635: ["The child opened the box out of [_____].", "子どもは好奇心から箱を開けた。"],
  s2_636: ["The restaurant plans to [_____] two new cooks.", "そのレストランは新しい料理人を2人雇う予定だ。"],
  s2_637: ["This old map is [_____]; all the roads have changed.", "この古い地図は役に立たない。道路がすっかり変わってしまったから。", ["primary", "obvious", "absent"]],
  s2_639: ["Dogs need to [_____] with other dogs when they are young.", "犬は小さいうちに他の犬と交流する必要がある。"],
  s2_640: ["Drinking tea is a morning [_____] for my grandmother.", "お茶を飲むのは祖母の毎朝の儀式だ。"],
  s2_641: ["Three people were [_____]d in the accident.", "その事故で3人がけがをした。"],
  s2_642: ["Sunglasses [_____] your eyes from the sun.", "サングラスは目を日光から守る。"],
  s2_643: ["Our [_____] goal is to win the world championship.", "私たちの究極の目標は世界選手権で優勝することだ。"],
  s2_644: ["I love spending time in [_____], walking in the forest.", "私は森を歩いたりして自然の中で過ごすのが大好きだ。"],
  s2_645: ["Don't forget to water the [_____]s.", "植物に水をやるのを忘れないで。"],
  s2_646: ["The [_____] slept peacefully in her mother's arms.", "赤ちゃんは母親の腕の中ですやすや眠った。"],
  s2_647: ["I looked up dinosaurs in the [_____].", "百科事典で恐竜について調べた。"],
  s2_648: ["The cat was [_____] to be found.", "猫はどこにも見当たらなかった。"],
  s2_649: ["Don't [_____] all the hot water.", "お湯を全部使い切らないで。"],
  s2_650: ["He [_____]ed to be asleep.", "彼は寝たふりをした。", ["examine", "command", "migrate"]],
  s2_651: ["She received [_____] for her work with poor children.", "彼女は貧しい子どもたちのための活動で認められた。"],
  s2_652: ["The new park will [_____] this empty lot into a beautiful green space.", "新しい公園はこの空き地を美しい緑地に変えるだろう。"],
  s2_653: ["The [_____] of women in society has changed a lot.", "社会における女性の地位は大きく変わった。"],
  s2_654: ["The Titanic began to [_____] after hitting an iceberg.", "タイタニック号は氷山にぶつかったあと沈み始めた。"],
  s2_655: ["There is no [_____] that the weather will improve.", "天気がよくなる兆しはない。", ["location", "occupation", "nutrition"]],
  s2_656: ["I [_____] cold weather.", "私は寒い天気が嫌いだ。"],
  s2_657: ["The students are busy with [_____]s for the school festival.", "生徒たちは文化祭の準備で忙しい。"],
  s2_658: ["We need to [_____] new software on this computer.", "このコンピュータに新しいソフトを入れる必要がある。"],
  s2_659: ["His [_____] said that he was innocent.", "彼の弁護士は彼が無実だと述べた。"],
  s2_660: ["Studying abroad gives students [_____] experience.", "留学は生徒に異文化を体験する機会を与える。"],
  s2_661: ["Don't stand too close to the [_____] of the cliff.", "崖の端に近づきすぎないで。"],
  s2_662: ["Early American [_____]s traveled west in wagons.", "初期のアメリカの開拓者たちは幌馬車で西へ向かった。"],
  s2_663: ["I can't [_____] chocolate.", "チョコレートには目がない。"],
  s2_664: ["The police [_____] that he stole the money.", "警察は彼がお金を盗んだのではないかと疑っている。"],
  s2_665: ["Small countries often [_____] themselves with stronger ones.", "小さな国はしばしばより強い国と同盟を結ぶ。"],
  s2_666: ["Many [_____] songs tell stories about everyday life.", "多くの民謡は日々の暮らしの物語を伝えている。"],
  s2_667: ["I [_____] saying such a mean thing to her.", "彼女にあんなにひどいことを言ったのを後悔している。"],
  s2_668: ["Can you [_____] your fingers?", "指をパチンと鳴らせますか。"],
  s2_669: ["The earthquake caused [_____] damage to the city.", "その地震は町に甚大な被害をもたらした。"],
  s2_670: ["We drove along the [_____] and enjoyed the ocean view.", "私たちは海岸沿いをドライブして海の景色を楽しんだ。"],
  "s3-34": ["How many [_____]s are on the shopping list?", "買い物リストにはいくつの品目がありますか。"],
  "s3-99": ["Can you tell the [_____] between these two pictures?", "この2枚の絵の違いがわかりますか。"],
  "s3-118": ["A fallen tree [_____]ed the road.", "倒れた木が道路をふさいだ。"],
  "s3-132": ["A large [_____] gathered to watch the fireworks.", "花火を見ようと大勢の人が集まった。"],
  "s3-141": ["The river [_____]s into the sea.", "その川は海に流れ込んでいる。"],
  "s3-148": ["The whole [_____] watched the Olympic final on TV.", "国中がオリンピックの決勝をテレビで見た。"],
  "s3-251": ["Sumo is often called Japan's [_____] sport.", "相撲はよく日本の国技と呼ばれる。"],
  "s3-282": ["The castle is a popular tourist [_____].", "その城は人気の観光地だ。"],
  "s3-302": ["Smoking is not allowed in [_____] places.", "公共の場所での喫煙は禁止されている。"],
  "s3-312": ["Children have so much [_____]; they never get tired.", "子どもたちは元気いっぱいで、まったく疲れない。"],
  "s3-365": ["The house was in a terrible [_____] after the storm.", "嵐のあと、家はひどい状態だった。"],
  "s3-440": ["Do you think ghosts really [_____]?", "幽霊は本当に存在すると思いますか。"],
  "s3-459": ["The fire [_____]ed the old temple.", "火事でその古い寺は焼失した。"],
  "s3-495": ["What [_____] of music do you like?", "どんな種類の音楽が好きですか。"],
  "s3-551": ["The Edo [_____] lasted for about 260 years.", "江戸時代は約260年続いた。"],
  "s3-591": ["The price includes [_____].", "その値段には税金が含まれている。"],
  "s3-609": ["I can't [_____] this heat any longer.", "この暑さにはもう我慢できない。"],
  a6: ["The army [_____]d toward the city.", "軍は町に向かって進んだ。"],
  a187: ["There's no age [_____] for this course; anyone can join.", "この講座には年齢制限がないので、誰でも参加できる。"],
  a701: ["My grandfather served in the [_____] during the war.", "祖父は戦争中、陸軍に従軍した。"],
  a1128: ["This box is too heavy for me to [_____].", "この箱は重すぎて私には持ち上げられない。"],
  a1497: ["Scientists saw a strange [_____] flying in the sky.", "科学者たちは空を飛ぶ奇妙な物体を目撃した。"],
  b1_biology: ["In [_____] class, we studied how cells divide.", "生物の授業で、細胞がどのように分裂するかを学んだ。"],
  b1_carriage: ["The queen rode in a golden [_____] pulled by horses.", "女王は馬が引く金色の馬車に乗った。"],
  b1_fashionable: ["That cafe is very [_____] among young people.", "あのカフェは若者の間でとても流行っている。"],
  b1_genetics: ["Thanks to [_____], we know that children get traits from their parents.", "遺伝学のおかげで、子どもが親から特徴を受け継ぐことがわかっている。"],
  b1_mud: ["The children came home covered in [_____].", "子どもたちは泥だらけで帰ってきた。"],
  b1_stylish: ["She always wears [_____] clothes.", "彼女はいつもおしゃれな服を着ている。"],
  b1_tense: ["I felt [_____] before the job interview.", "就職の面接の前は緊張した。"],
  b1_terrific: ["The food was [_____]! I'd love to come back.", "料理は最高だった！また来たい。"],
  b1_wagon: ["The farmer loaded the hay onto his [_____].", "農夫は干し草を荷馬車に積んだ。"],
  b1_wither: ["The flowers will [_____] if you don't water them.", "水をやらないと花はしおれてしまう。"],
};
