import { SentenceRewrites } from "./types";

/**
 * 高校発展の例文の書き直し。キーは単語ID、値は [例文, 和訳, 誤答]。
 * 決まり・使い方は scripts/apply_sentences.ts を参照。
 */
export const senior3: SentenceRewrites = {
  "s3-1": ["This discovery is very [_____] for medical science.", "この発見は医学にとって非常に重要だ。"],
  "s3-2": ["Parents make many [_____]s for their children.", "親は子どものために多くの犠牲を払う。"],
  "s3-3": ["He pulled the [_____] of the gun.", "彼は銃の引き金を引いた。"],
  "s3-4": ["To our [_____], the sun came out on the day of the picnic.", "うれしいことに、ピクニックの日に太陽が出た。"],
  "s3-5": ["The earthquake was the worst natural [_____] in decades.", "その地震は数十年で最悪の自然災害だった。"],
  "s3-6": ["We use [_____] to say that two things are true together, as in \"She plays both the piano and the violin.\"", "「彼女はピアノとバイオリンの両方を弾く」のように、2つのことがどちらも当てはまると言うときに使います。"],
  "s3-7": ["In Greek [_____], Zeus was the king of the gods.", "ギリシャ神話では、ゼウスは神々の王だった。"],
  "s3-8": ["The [_____] spread quickly from person to person.", "そのウイルスは人から人へとすぐに広がった。"],
  "s3-9": ["Millions of people in the world suffer from [_____].", "世界では何百万もの人が飢えに苦しんでいる。"],
  "s3-10": ["Which [_____] are you flying with?", "どの航空会社の便に乗りますか。"],
  "s3-11": ["The soldiers laid down their [_____] and surrendered.", "兵士たちは武器を置いて降伏した。"],
  "s3-13": ["I bought a can of juice from the [_____].", "自動販売機で缶ジュースを買った。"],
  "s3-14": ["[_____]s pray five times a day.", "イスラム教徒は1日に5回祈る。"],
  "s3-15": ["I [_____] eat at home, but sometimes I eat out.", "たいていは家で食べるが、ときどき外食する。"],
  "s3-16": ["The game was delayed because of [_____] problems with the lights.", "照明の技術的な問題で試合が遅れた。"],
  "s3-17": ["He was arrested for [_____] after hitting a man.", "彼は男性を殴ったあと、暴行の容疑で逮捕された。"],
  "s3-18": ["I happened to [_____] my old teacher at the station.", "駅で偶然昔の先生に出くわした。"],
  "s3-19": ["Our school puts great [_____] on English education.", "私たちの学校は英語教育に大きな重点を置いている。"],
  "s3-20": ["The [_____] from high school to college can be difficult.", "高校から大学への移行は難しいことがある。"],
  "s3-21": ["The old [_____] fell after the revolution.", "革命のあと、旧政権は倒れた。"],
  "s3-22": ["She has a cheerful [_____]; everyone likes her.", "彼女は明るい性格で、みんなに好かれている。"],
  "s3-23": ["Don't [_____] the ending of the movie for me!", "映画の結末を言って台無しにしないで！"],
  "s3-24": ["Have you seen her [_____] movie?", "彼女の最新の映画を見ましたか。"],
  "s3-25": ["In Japan, people often eat [_____] fish.", "日本では生の魚をよく食べる。"],
  "s3-26": ["The new president promised [_____] changes to the system.", "新大統領は制度の抜本的な改革を約束した。"],
  "s3-27": ["She passed the driving test on her first [_____].", "彼女は1回目の挑戦で運転免許の試験に合格した。"],
  "s3-28": ["The [_____] of clean water is the government's job.", "きれいな水の供給は政府の仕事だ。"],
  "s3-29": ["Ants and bees are [_____]s.", "アリとハチは昆虫だ。"],
  "s3-30": ["This medicine can [_____] the disease.", "この薬でその病気を治すことができる。"],
  "s3-31": ["Space has always [_____]d me.", "宇宙にはずっと魅了されてきた。"],
  "s3-32": ["He left his [_____] to his children when he died.", "彼は亡くなるとき、財産を子どもたちに遺した。"],
  "s3-33": ["Please [_____] the floor with this broom.", "このほうきで床を掃いてください。"],
  "s3-35": ["Is this job [_____] or only for the summer?", "この仕事は正規のものですか、それとも夏だけですか。"],
  "s3-36": ["How much is the [_____] for this apartment?", "このアパートの家賃はいくらですか。"],
  "s3-37": ["It took me a while to [_____] to the time difference.", "時差に慣れるのにしばらくかかった。"],
  "s3-38": ["It takes [_____] to admit your mistakes.", "自分の間違いを認めるには勇気がいる。"],
  "s3-39": ["Two [_____] men robbed the bank.", "武装した2人の男が銀行を襲った。"],
  "s3-40": ["This museum shows [_____] art by living artists.", "この美術館は存命の画家による現代美術を展示している。"],
  "s3-41": ["Early humans used [_____] tools made of stone.", "初期の人類は石でできた原始的な道具を使っていた。"],
  "s3-42": ["People in Osaka speak a different [_____] from people in Tokyo.", "大阪の人は東京の人とは違う方言を話す。"],
  "s3-43": ["The company spends a lot of money on TV [_____].", "その会社はテレビ広告に多額のお金を使っている。"],
  "s3-44": ["My sister and I are [_____]s, born ten minutes apart.", "姉と私は双子で、10分違いで生まれた。"],
  "s3-45": ["Selling drugs is [_____] in most countries.", "麻薬の販売はほとんどの国で違法だ。"],
  "s3-46": ["Whether we go or not will [_____] on the weather.", "行くかどうかは天気次第だ。"],
  "s3-47": ["Watching movies is my favorite form of [_____].", "映画を見ることが私の一番好きな娯楽だ。"],
  "s3-49": ["The dog wagged its [_____] happily.", "犬はうれしそうにしっぽを振った。"],
  "s3-50": ["According to a recent [_____], most voters support the plan.", "最近の世論調査によると、ほとんどの有権者がその計画を支持している。"],
  "s3-51": ["My father [_____] smoking last year.", "父は去年たばこをやめた。"],
  "s3-52": ["The ring fell to the [_____] of the pool.", "指輪がプールの底に落ちた。"],
  "s3-53": ["Darwin's theory of [_____] explains how species change over time.", "ダーウィンの進化論は、種が時間とともにどう変化するかを説明している。"],
  "s3-54": ["Police are investigating his [_____] in the crime.", "警察は彼の犯罪への関与を捜査している。"],
  "s3-56": ["Many English words [_____] from Latin.", "多くの英単語はラテン語に由来する。"],
  "s3-57": ["I [_____] you can't eat ten hamburgers!", "ハンバーガーを10個も食べられるわけがないよ、賭けてもいい！"],
  "s3-58": ["The [_____] Court is the highest court in the country.", "最高裁判所はその国で最も上位の裁判所だ。"],
  "s3-59": ["Water becomes [_____] when it freezes.", "水は凍ると固体になる。"],
  "s3-60": ["The success of the project was [_____] due to her hard work.", "その計画の成功は主に彼女の努力によるものだった。"],
  "s3-61": ["It is a Japanese [_____] to take off your shoes at home.", "家の中で靴を脱ぐのは日本の習慣だ。"],
  "s3-62": ["There are [_____]s on how much water you can use during the drought.", "干ばつの間は使える水の量に制限がある。"],
  "s3-63": ["[_____], he left the company last month; I just heard about it.", "どうやら彼は先月会社を辞めたらしい。今聞いたところだ。"],
  "s3-64": ["Do you want a small, [_____], or large drink?", "飲み物は小、中、大のどれにしますか。"],
  "s3-65": ["The company [_____]d its new product on TV.", "その会社はテレビで新製品を宣伝した。"],
  "s3-66": ["The government took steps to [_____] the rise in crime.", "政府は犯罪の増加に対抗する手を打った。"],
  "s3-67": ["The police found an important [_____] at the scene.", "警察は現場で重要な手がかりを見つけた。"],
  "s3-68": ["My teacher is [_____] but fair.", "私の先生は厳しいが公平だ。"],
  "s3-69": ["The [_____] noise woke the baby.", "突然の物音で赤ちゃんが目を覚ました。"],
  "s3-70": ["First, write a short [_____] of your essay.", "まず、作文の概要を短く書きなさい。"],
  "s3-71": ["The [_____] at the front desk gave me my room key.", "フロントの係員が部屋の鍵をくれた。"],
  "s3-72": ["The company [_____]ed her as the new manager.", "会社は彼女を新しい部長に任命した。"],
  "s3-73": ["Our homework is to write a 500-word [_____] about our future dreams.", "宿題は将来の夢について500語の作文を書くことだ。"],
  "s3-74": ["Her kind words gave me great [_____].", "彼女の優しい言葉に私は大いに慰められた。"],
  "s3-75": ["Abraham Lincoln was the 16th [_____] of the United States.", "エイブラハム・リンカーンはアメリカの第16代大統領だった。"],
  "s3-76": ["Don't be afraid of [_____]; you can learn from it.", "失敗を恐れてはいけない。失敗から学べるのだから。"],
  "s3-77": ["She is the child's [_____] mother, but she didn't raise him.", "彼女はその子の生みの母だが、育ててはいない。"],
  "s3-78": ["That dog is [_____]; it bites people.", "あの犬は攻撃的で、人にかみつく。"],
  "s3-79": ["We need to [_____] a new way to save energy.", "私たちはエネルギーを節約する新しい方法を考え出す必要がある。"],
  "s3-80": ["The [_____] of this project is to help poor children.", "この計画の目的は貧しい子どもたちを助けることだ。"],
  "s3-81": ["The movie was praised by [_____]s.", "その映画は評論家たちに称賛された。"],
  "s3-82": ["The war caused great [_____] to many people.", "戦争は多くの人に大きな苦しみをもたらした。"],
  "s3-83": ["The hotel is [_____] booked this weekend.", "そのホテルは今週末満室だ。"],
  "s3-84": ["[_____] your phone to the Wi-Fi.", "携帯をWi-Fiにつないで。"],
  "s3-85": ["She has traveled all over the [_____].", "彼女は世界中を旅してきた。"],
  "s3-86": ["His work was [_____], but not excellent.", "彼の仕事はまずまずだったが、素晴らしくはなかった。"],
  "s3-87": ["I hurt my big [_____] when I kicked the table.", "テーブルを蹴って足の親指を痛めた。"],
  "s3-88": ["The [_____] of wealth in the country is very unequal.", "その国の富の分配はとても不平等だ。"],
  "s3-89": ["She has great musical [_____].", "彼女には素晴らしい音楽の才能がある。"],
  "s3-90": ["She made [_____] progress in English.", "彼女の英語は着実に上達した。"],
  "s3-91": ["Is it [_____] acceptable to eat while walking in Japan?", "日本では歩きながら食べることは社会的に許されますか。"],
  "s3-92": ["Can you [_____] me your pen?", "ペンを貸してくれますか。"],
  "s3-93": ["These new shoes are [_____]; they hurt my feet.", "この新しい靴は履き心地が悪く、足が痛くなる。"],
  "s3-94": ["The project is now in its final [_____].", "その計画は最終段階に入っている。"],
  "s3-95": ["[_____] the heavy rain, they went hiking.", "大雨にもかかわらず、彼らはハイキングに出かけた。"],
  "s3-96": ["This store sells TVs, computers, and other [_____] goods.", "この店はテレビやコンピュータなどの電子機器を売っている。"],
  "s3-97": ["I burned my [_____] on the hot soup.", "熱いスープで舌をやけどした。"],
  "s3-98": ["Everyone should be treated with [_____].", "誰もが尊厳をもって扱われるべきだ。"],
  "s3-100": ["She held the small bird in the [_____] of her hand.", "彼女は小鳥を手のひらにのせていた。"],
  "s3-101": ["The number of [_____]s among young people is a serious social problem.", "若者の自殺の多さは深刻な社会問題だ。"],
  "s3-102": ["War is a crime against [_____].", "戦争は人道に対する罪だ。"],
  "s3-103": ["Safety is our top [_____].", "安全が最優先だ。"],
  "s3-104": ["Don't put your [_____]s on the table while eating.", "食事中はテーブルにひじをつかないで。"],
  "s3-105": ["It's not your [_____]; it was an accident.", "あなたのせいではない。事故だったのだから。"],
  "s3-106": ["The family said [_____] goodbyes at the airport.", "家族は空港で涙ながらに別れを告げた。"],
  "s3-107": ["Follow the safety [_____] carefully.", "安全手順に注意深く従いなさい。"],
  "s3-108": ["The two companies will [_____] a new contract.", "2社は新しい契約について交渉する。"],
  "s3-109": ["My grandmother sewed [_____]es on the holes in my jeans.", "祖母はジーンズの穴に当て布を縫い付けてくれた。"],
  "s3-110": ["The report gives [_____] information about each product.", "その報告書はそれぞれの製品について詳しい情報を載せている。"],
  "s3-111": ["The new plan received a lot of [_____] from the public.", "その新しい計画は市民から多くの批判を受けた。"],
  "s3-112": ["Can you [_____] this shelf to the wall?", "この棚を壁に固定してもらえますか。"],
  "s3-113": ["[_____] a few mistakes, your essay is excellent.", "いくつかの間違いを除けば、あなたの作文は素晴らしい。", ["in the past", "both A and B", "out of order"]],
  "s3-114": ["The old town has a special [_____].", "その古い町には独特の魅力がある。"],
  "s3-116": ["My grandmother told me an old fairy [_____].", "祖母は私に昔のおとぎ話をしてくれた。"],
  "s3-117": ["She was [_____] when she heard the bad news.", "悪い知らせを聞いて彼女は動揺した。"],
  "s3-119": ["My sister is [_____] and will have a baby in May.", "姉は妊娠していて、5月に赤ちゃんが生まれる。"],
  "s3-120": ["Her language skills are a great [_____] to the company.", "彼女の語学力は会社にとって大きな財産だ。"],
  "s3-121": ["The country is [_____]ed by a president.", "その国は大統領によって統治されている。"],
  "s3-122": ["Dogs can [_____] sounds that humans cannot hear.", "犬は人間には聞こえない音を感じ取れる。"],
  "s3-123": ["Thank you for your [_____] reply.", "迅速なご返信ありがとうございます。"],
  "s3-124": ["He is the [_____] of a famous computer company.", "彼は有名なコンピュータ会社の創業者だ。"],
  "s3-125": ["He likes to [_____] his new car to his friends.", "彼は新しい車を友だちに見せびらかすのが好きだ。"],
  "s3-126": ["The fire was caused by [_____] problems in the wiring.", "その火事は配線の電気系統の不具合が原因だった。"],
  "s3-127": ["Stay [_____] and don't panic.", "落ち着いて、慌てないで。"],
  "s3-128": ["Eggs are sold by the [_____] in this store.", "この店では卵はダース単位で売られている。"],
  "s3-129": ["The region has [_____] rainfall, so rice grows well.", "その地域は雨量が豊富なので、米がよく育つ。"],
  "s3-130": ["On [_____] the whole class, I'd like to thank you.", "クラス全員を代表して、お礼を申し上げます。"],
  "s3-131": ["[_____] drinking is bad for your health.", "過度の飲酒は健康に悪い。"],
  "s3-133": ["Please [_____] to page 30 for more details.", "詳しくは30ページを参照してください。"],
  "s3-134": ["We need to make a final [_____] by Friday.", "金曜日までに最終的な決定をする必要がある。"],
  "s3-135": ["The long hike [_____]ed me.", "長いハイキングで私はへとへとになった。"],
  "s3-136": ["Farmers [_____] rice in these fields.", "農家はこれらの田んぼで米を栽培している。"],
  "s3-137": ["Your story is not [_____] with what you told me yesterday.", "あなたの話は昨日私に言ったことと食い違っている。"],
  "s3-138": ["I [_____] her courage.", "私は彼女の勇気に感心している。"],
  "s3-139": ["The price of the tour includes flights and [_____].", "ツアーの料金には航空券と宿泊が含まれている。"],
  "s3-140": ["Students should [_____] in club activities.", "生徒は部活動に参加するべきだ。"],
  "s3-142": ["The [_____] age for drinking in Japan is 20.", "日本で飲酒が法律で認められる年齢は20歳だ。"],
  "s3-143": ["Many soldiers died in [_____].", "多くの兵士が戦闘で亡くなった。"],
  "s3-144": ["[_____] warming is causing sea levels to rise.", "地球温暖化で海面が上昇している。"],
  "s3-145": ["I have [_____] in you; I know you can do it.", "あなたを信頼している。きっとできるよ。"],
  "s3-146": ["The fire was started [_____]; someone poured gasoline on the floor.", "その火事は故意に起こされた。誰かが床にガソリンをまいたのだ。"],
  "s3-147": ["Thank you for your [_____] about our products.", "当社の製品についてのお問い合わせありがとうございます。"],
  "s3-149": ["[_____] your arms and legs before you run.", "走る前に腕と脚を伸ばしなさい。"],
  "s3-150": ["The [_____] of Education decides what students learn at school.", "文部科学省は学校で生徒が学ぶ内容を決めている。"],
  "s3-151": ["I felt great [_____] when I found my lost wallet.", "なくした財布が見つかって、ほっとした。"],
  "s3-152": ["Please get on the bus through the [_____] door.", "バスには後ろのドアから乗ってください。"],
  "s3-153": ["The factory [_____]s 500 workers.", "その工場は500人の従業員を雇っている。"],
  "s3-154": ["The cat is sleeping on my [_____].", "猫が私のひざの上で寝ている。"],
  "s3-155": ["Who will win the next presidential [_____]?", "次の大統領選挙で誰が勝つだろうか。"],
  "s3-156": ["The company's [_____] rose by ten percent this year.", "その会社の収益は今年10パーセント増えた。"],
  "s3-157": ["The [_____] of the castle ruled the land around it.", "城の領主は周りの土地を支配していた。"],
  "s3-158": ["She is studying [_____] at university because she wants to work at a bank.", "彼女は銀行で働きたいので、大学で経済学を学んでいる。"],
  "s3-159": ["In [_____] with Tokyo, my town is very quiet.", "東京と比べると、私の町はとても静かだ。"],
  "s3-160": ["Please keep your speech [_____]; we only have five minutes.", "スピーチは手短にお願いします。5分しかありません。"],
  "s3-161": ["We reached the [_____] of the mountain at noon.", "私たちは正午に山頂に着いた。"],
  "s3-162": ["Are you [_____] to help us clean up?", "片付けを手伝ってくれますか。"],
  "s3-163": ["The First [_____] protects freedom of speech in the United States.", "アメリカでは憲法修正第1条が言論の自由を守っている。"],
  "s3-164": ["My broken arm was very [_____].", "折れた腕はとても痛かった。"],
  "s3-165": ["Cost is a key [_____] when choosing a school.", "学校を選ぶとき、費用は重要な要因だ。"],
  "s3-166": ["The train will [_____] from Platform 3.", "電車は3番線から出発します。"],
  "s3-167": ["She [_____]ed with relief when she heard the good news.", "よい知らせを聞いて、彼女はほっとため息をついた。"],
  "s3-168": ["Vegetables are rich in [_____], which is good for your stomach.", "野菜には食物繊維が豊富で、お腹によい。"],
  "s3-169": ["The minimum [_____] in Tokyo is over 1,100 yen an hour.", "東京の最低賃金は時給1,100円を超えている。"],
  "s3-170": ["There is no [_____] evidence that ghosts exist.", "幽霊が存在するという科学的な証拠はない。"],
  "s3-171": ["Climbing the mountain was [_____], but we made it to the top.", "山に登るのは大変だったが、私たちは頂上にたどり着いた。"],
  "s3-172": ["I [_____] forget people's names.", "私は人の名前を忘れがちだ。"],
  "s3-173": ["There was [_____] damage to the car, just a small scratch.", "車には小さな傷がついた程度の、わずかな損傷しかなかった。"],
  "s3-174": ["A gas [_____] destroyed the building.", "ガス爆発で建物が壊れた。"],
  "s3-175": ["I can't [_____] to buy a new car.", "新しい車を買う余裕はない。"],
  "s3-176": ["The new school year, or [_____] year, begins in April in Japan.", "日本では新しい学年、つまり学業年度は4月に始まる。"],
  "s3-177": ["Old people are more [_____] to the flu.", "お年寄りはインフルエンザにかかりやすい。"],
  "s3-178": ["She [_____]d her old clothes to charity.", "彼女は古着を慈善団体に寄付した。"],
  "s3-179": ["The loud thunder [_____]ed the children.", "大きな雷が子どもたちを怖がらせた。"],
  "s3-180": ["We put another [_____] on the fire.", "私たちは火にもう1本丸太をくべた。"],
  "s3-181": ["Anyone can join the club, [_____] age.", "年齢に関係なく、誰でもクラブに入れる。"],
  "s3-182": ["Brushing my teeth is part of my morning [_____].", "歯みがきは私の毎朝の習慣の一部だ。"],
  "s3-183": ["Don't be [_____] of making mistakes.", "間違えることを恐れないで。"],
  "s3-184": ["I took some medicine for my [_____].", "頭痛のために薬を飲んだ。"],
  "s3-185": ["He seems to [_____] help us.", "彼は快く手伝ってくれそうだ。"],
  "s3-186": ["Workers joined the [_____] to fight for higher pay.", "労働者たちは賃上げを求めて組合に加わった。"],
  "s3-187": ["[_____] the lemon and add the juice to the tea.", "レモンを搾って、その汁を紅茶に入れなさい。"],
  "s3-188": ["I love reading [_____] novels with detectives in them.", "私は探偵が出てくる推理小説を読むのが大好きだ。"],
  "s3-189": ["She planted sunflower [_____]s in the garden.", "彼女は庭にヒマワリの種をまいた。"],
  "s3-190": ["She passed the test with [_____].", "彼女は楽々とテストに合格した。"],
  "s3-191": ["There are many American [_____] bases in Okinawa.", "沖縄にはアメリカ軍の基地が多くある。"],
  "s3-192": ["Mount Fuji is [_____] all over the world.", "富士山は世界中でよく知られている。"],
  "s3-193": ["They are [_____] friends who share everything.", "彼らは何でも話し合う親しい友人だ。", ["reusable", "temperate", "vulnerable"]],
  "s3-195": ["You can [_____] on me.", "私を頼っていいよ。"],
  "s3-197": ["There was strong [_____] to the new airport.", "新しい空港には強い反対があった。"],
  "s3-198": ["After long [_____]s, the two countries signed a peace treaty.", "長い交渉の末、2国は平和条約に調印した。"],
  "s3-199": ["Be careful; this knife is very [_____].", "気をつけて。このナイフはとても鋭いから。"],
  "s3-200": ["They [_____]d the argument by talking calmly.", "彼らは冷静に話し合って言い争いを収めた。"],
  "s3-202": ["My phone's [_____] is almost dead.", "携帯の電池がもうすぐ切れる。"],
  "s3-203": ["Japan's [_____] was written in 1946.", "日本国憲法は1946年に作られた。"],
  "s3-205": ["She is a math [_____]; she solved the problem in seconds.", "彼女は数学の天才で、その問題を数秒で解いた。"],
  "s3-206": ["It's your turn to [_____] the ball.", "今度は君がボールを投げる番だ。"],
  "s3-207": ["We are in [_____] on this point.", "この点について私たちは意見が一致している。"],
  "s3-208": ["[_____]s are buying more online these days.", "最近、消費者はネットで買い物をすることが増えている。"],
  "s3-209": ["The game will be [_____] live on TV.", "その試合はテレビで生中継される。"],
  "s3-210": ["I don't want to [_____] my parents.", "両親をがっかりさせたくない。"],
  "s3-211": ["I like coffee, [_____] my wife likes tea.", "私はコーヒーが好きだが、妻は紅茶が好きだ。"],
  "s3-212": ["The [_____] bomb was dropped on Hiroshima in 1945.", "1945年、広島に原子爆弾が落とされた。"],
  "s3-213": ["Let's [_____] for peace.", "平和を祈りましょう。"],
  "s3-214": ["The dog sat by the table to [_____] for food.", "犬は食べ物をねだるためにテーブルのそばに座った。"],
  "s3-215": ["Animals must [_____] to changes in their environment.", "動物は環境の変化に適応しなければならない。"],
  "s3-216": ["After her long illness, she looked pale and [_____].", "長い病気のあと、彼女は青白くやつれて見えた。"],
  "s3-217": ["The electric [_____] was broken, so the lights didn't work.", "電気回路が壊れていたので、明かりがつかなかった。"],
  "s3-218": ["The children ran [_____] the beach.", "子どもたちは浜辺のほうへ走っていった。"],
  "s3-219": ["This book is very [_____]; it has over 1,000 pages.", "この本はとても分厚く、1,000ページ以上ある。"],
  "s3-220": ["Let me explain the rules [_____].", "規則を手短に説明させてください。"],
  "s3-221": ["He lost [_____] after hitting his head.", "彼は頭を打って意識を失った。"],
  "s3-222": ["Smoking can have [_____] effects on the people around you.", "喫煙は周りの人に間接的な影響を与えることがある。"],
  "s3-223": ["Her speech [_____]ed everyone.", "彼女のスピーチはみんなに感銘を与えた。"],
  "s3-224": ["The [_____] of the problem surprised the experts.", "その問題の複雑さに専門家たちは驚いた。"],
  "s3-225": ["The doctor said the [_____] on my knee went well.", "医師は私の膝の手術がうまくいったと言った。"],
  "s3-226": ["The patient is under [_____] in the hospital.", "その患者は病院で経過観察中だ。"],
  "s3-227": ["Bring your own [_____] bag when you go shopping.", "買い物に行くときは繰り返し使える自分の袋を持っていって。"],
  "s3-228": ["This [_____] is used to treat headaches.", "この薬は頭痛の治療に使われる。"],
  "s3-229": ["A safety [_____] checked the elevator.", "安全検査官がエレベーターを点検した。"],
  "s3-230": ["Sales rose in the first [_____] of the year.", "その年の第1四半期に売り上げが伸びた。"],
  "s3-231": ["Please include only [_____] information in your report.", "報告書には関連のある情報だけを入れてください。", ["apparent", "reluctant", "pregnant"]],
  "s3-232": ["The river forms the [_____] between the two towns.", "その川が2つの町の境界になっている。"],
  "s3-233": ["You can't buy [_____]; you have to earn it.", "信頼はお金で買えない。自分で勝ち取るものだ。"],
  "s3-234": ["My grandparents live on a small [_____].", "祖父母はわずかな年金で暮らしている。"],
  "s3-235": ["On New Year's Day, we eat [_____] Japanese food called osechi.", "元日には、おせちと呼ばれる伝統的な日本料理を食べる。"],
  "s3-236": ["We should show [_____] to older people.", "お年寄りには敬意を払うべきだ。"],
  "s3-237": ["The police [_____] spoke to reporters about the case.", "警察本部長が事件について記者に話した。"],
  "s3-238": ["There is a Picasso [_____] at the museum this month.", "今月、美術館でピカソ展が開かれている。"],
  "s3-239": ["Give me [_____], or give me death!", "我に自由を与えよ、しからずんば死を！"],
  "s3-240": ["The city held a public [_____] to discuss the new park.", "市は新しい公園について話し合う公開討論会を開いた。"],
  "s3-241": ["My [_____] is getting worse, so I need glasses.", "視力が落ちてきたので、眼鏡が必要だ。"],
  "s3-242": ["We saw rare plants at the [_____] garden.", "植物園で珍しい植物を見た。"],
  "s3-243": ["I can't [_____] eat all this food.", "この食べ物を全部食べるなんてとても無理だ。"],
  "s3-244": ["Meat, fish, and eggs are good sources of [_____].", "肉、魚、卵はタンパク質のよい供給源だ。"],
  "s3-245": ["A travel [_____] booked our hotel.", "旅行代理店がホテルを予約してくれた。"],
  "s3-246": ["The store is offering a 20 percent price [_____] this week.", "その店は今週20パーセントの値下げをしている。"],
  "s3-247": ["Change to a lower [_____] when you drive up a hill.", "坂を上るときはギアを低くしなさい。"],
  "s3-248": ["He played the guitar with great [_____].", "彼は情熱を込めてギターを弾いた。"],
  "s3-249": ["The new [_____] to our family is a puppy named Pochi.", "私たちの家族に新しく加わったのはポチという子犬だ。"],
  "s3-250": ["The pain stopped the [_____] I took the medicine.", "薬を飲んだ瞬間、痛みが消えた。"],
  "s3-252": ["The patient is in [_____] condition.", "その患者は危篤状態だ。"],
  "s3-253": ["This movie is not [_____] for young children.", "この映画は小さい子どもには向いていない。"],
  "s3-254": ["The photo has a beautiful mountain in the [_____].", "その写真は背景に美しい山が写っている。"],
  "s3-255": ["The American [_____] War lasted from 1861 to 1865.", "アメリカ南北戦争は1861年から1865年まで続いた。"],
  "s3-256": ["We should make a clear [_____] between facts and opinions.", "事実と意見をはっきり区別すべきだ。"],
  "s3-257": ["More and more people live in [_____] areas.", "ますます多くの人が都市部に住んでいる。"],
  "s3-258": ["The bottle is [_____] empty; there's only a drop left.", "瓶はほとんど空で、一滴しか残っていない。"],
  "s3-259": ["Matsuo Basho was a famous Japanese [_____].", "松尾芭蕉は有名な日本の詩人だった。"],
  "s3-260": ["He will [_____] to a school in Osaka next month.", "彼は来月大阪の学校に転校する。"],
  "s3-261": ["Children are [_____] about everything around them.", "子どもは身の回りのあらゆることに好奇心を持っている。"],
  "s3-262": ["Laws on [_____] differ greatly from country to country.", "中絶に関する法律は国によって大きく異なる。"],
  "s3-263": ["Ask your [_____] before taking this medicine.", "この薬を飲む前に医師に相談してください。"],
  "s3-264": ["Toyota is a famous car [_____].", "トヨタは有名な自動車メーカーだ。"],
  "s3-265": ["Eagles have excellent [_____]; they can see a mouse from far away.", "ワシは視力が非常によく、遠くからでもネズミを見つけられる。"],
  "s3-266": ["I'm too tired to walk any [_____].", "疲れてもうこれ以上歩けない。"],
  "s3-267": ["Being rich does not [_____] make you happy.", "お金持ちになっても必ずしも幸せになるとは限らない。"],
  "s3-268": ["The wind [_____]ed the leaves across the yard.", "風が庭中に葉を散らした。"],
  "s3-269": ["The school will [_____] a new rule about phones next month.", "学校は来月、携帯電話に関する新しい規則を実施する。"],
  "s3-270": ["Our friendship is based on [_____] respect.", "私たちの友情は互いへの尊敬に基づいている。"],
  "s3-271": ["In [_____], exercise is good for both body and mind.", "結論として、運動は体にも心にもよい。"],
  "s3-272": ["It is a common [_____] that cats have nine lives.", "猫には9つの命があるというのは、よく信じられている考えだ。"],
  "s3-273": ["The prime [_____] gave a speech on TV.", "首相がテレビで演説した。"],
  "s3-274": ["Please [_____] smoking in this area.", "この場所での喫煙はご遠慮ください。"],
  "s3-275": ["Try to stay [_____], even when things are hard.", "つらいときでも前向きでいるようにしよう。"],
  "s3-276": ["Many [_____] people live in New York.", "ニューヨークには多くのユダヤ人が住んでいる。"],
  "s3-277": ["She takes a vitamin [_____] every morning.", "彼女は毎朝ビタミンのサプリメントを飲んでいる。"],
  "s3-278": ["The [_____] of the dinosaurs happened about 66 million years ago.", "恐竜の絶滅は約6,600万年前に起こった。"],
  "s3-279": ["Let's [_____] behind the tree so he can't find us.", "彼に見つからないように、木の後ろに隠れよう。"],
  "s3-280": ["We eat three [_____]s a day.", "私たちは1日に3回食事をとる。"],
  "s3-281": ["I wasn't [_____] that the store was closed, so I went there for nothing.", "店が閉まっていることを知らなかったので、無駄足を踏んだ。"],
  "s3-283": ["The word is on the [_____] of my tongue.", "その言葉が喉まで出かかっている。"],
  "s3-284": ["She has spent [_____] time and money on her garden.", "彼女は庭にかなりの時間とお金をかけてきた。"],
  "s3-285": ["This dictionary is very [_____] for learning English.", "この辞書は英語の学習にとても役立つ。"],
  "s3-287": ["Email is a fast [_____] of communication.", "電子メールは速い連絡手段だ。"],
  "s3-288": ["There is a strong [_____] between the mother and her baby.", "その母親と赤ちゃんの間には強い絆がある。"],
  "s3-290": ["We flew to London [_____] Dubai.", "私たちはドバイ経由でロンドンへ飛んだ。"],
  "s3-291": ["Please [_____] your speech to five minutes.", "スピーチは5分以内にとどめてください。"],
  "s3-292": ["The teacher has 30 [_____]s in her class.", "その先生のクラスには30人の生徒がいる。"],
  "s3-293": ["Let's eat at one of the [_____] restaurants.", "近くのレストランで食べよう。"],
  "s3-294": ["The Showa [_____] lasted from 1926 to 1989.", "昭和の時代は1926年から1989年まで続いた。"],
  "s3-295": ["It was [_____] of you to save money for the future.", "将来のために貯金したのは賢明だったね。"],
  "s3-296": ["They used rope to [_____] the logs together.", "彼らはロープで丸太を束ねた。"],
  "s3-297": ["Do you know how to [_____] this machine?", "この機械の操作方法を知っていますか。"],
  "s3-298": ["It might rain, but let's go [_____].", "雨が降るかもしれないけど、とにかく行こう。"],
  "s3-299": ["Cars give off [_____] dioxide.", "車は二酸化炭素を出す。"],
  "s3-300": ["Many people [_____] the plan to build a new airport.", "多くの人が新空港建設の計画に反対している。"],
  "s3-301": ["The teacher [_____]d how to use the machine.", "先生はその機械の使い方を実演して見せた。"],
  "s3-303": ["The bill was passed by the [_____].", "その法案は上院で可決された。"],
  "s3-304": ["The horses [_____]ed across the field.", "馬たちは野原を全力で駆けていった。"],
  "s3-305": ["Please reply [_____] three days.", "3日以内に返事をください。"],
  "s3-306": ["She became very [_____] and started to cry.", "彼女はとても感情的になり、泣き出した。"],
  "s3-307": ["The [_____] of the soil here is good for growing grapes.", "ここの土の成分はブドウを育てるのに適している。"],
  "s3-308": ["The desert has [_____] temperatures, very hot by day and cold at night.", "砂漠は気温の差が極端で、昼はとても暑く夜は寒い。"],
  "s3-309": ["Humans are [_____] animals; we can think logically.", "人間は理性的な動物で、論理的に考えることができる。"],
  "s3-310": ["India became [_____] from Britain in 1947.", "インドは1947年にイギリスから独立した。"],
  "s3-311": ["The police don't know the [_____] for the crime.", "警察はその犯行の動機がわかっていない。"],
  "s3-313": ["The government started a new [_____] to help young parents.", "政府は若い親を支援する新しい計画を始めた。"],
  "s3-314": ["He went to the pub with his [_____]s after work.", "彼は仕事のあと仲間とパブに行った。"],
  "s3-315": ["You can [_____] a song on the radio show.", "そのラジオ番組では曲をリクエストできる。"],
  "s3-316": ["Please fill out this [_____] form.", "この申込用紙に記入してください。"],
  "s3-317": ["The workers demanded better pay for their [_____].", "労働者たちは自分たちの労働に対してより良い賃金を求めた。"],
  "s3-318": ["I'm sorry, I'm [_____] to come to the meeting.", "申し訳ありませんが、会議に出席できません。"],
  "s3-319": ["After [_____], she plans to work abroad.", "卒業後、彼女は海外で働く予定だ。"],
  "s3-320": ["I asked for a one-week [_____] on my report.", "レポートの期限を1週間延ばしてもらうよう頼んだ。"],
  "s3-321": ["[_____] makes prices go up every year.", "インフレで物価が毎年上がる。"],
  "s3-322": ["We looked at the moon through the [_____].", "私たちは望遠鏡で月を見た。"],
  "s3-323": ["I feel [_____] about lying to my mother.", "母にうそをついたことに罪悪感を感じている。"],
  "s3-324": ["This is a quiet [_____] with many parks.", "ここは公園の多い静かな地域だ。"],
  "s3-325": ["He received a 10,000-yen [_____] for finding the lost dog.", "彼は迷子の犬を見つけて1万円の謝礼をもらった。"],
  "s3-326": ["Our [_____] of time changes as we get older.", "時間の感じ方は年をとるにつれて変わる。"],
  "s3-327": ["That's my private [_____]; it's none of your business.", "それは私の個人的なことで、あなたには関係ない。"],
  "s3-328": ["With one [_____] of the ax, he split the log in two.", "彼は斧のひと振りで丸太を2つに割った。"],
  "s3-329": ["The game of chess [_____]d in India.", "チェスはインドで始まった。"],
  "s3-330": ["The baby has [_____] hands.", "赤ちゃんの手はとても小さい。"],
  "s3-331": ["He got sick [_____] he came back from his trip.", "彼は旅行から帰ってすぐに病気になった。"],
  "s3-332": ["The two plans are [_____] the same.", "その2つの計画は本質的に同じだ。", ["constantly", "socially", "briefly"]],
  "s3-333": ["This movie is based on [_____] events.", "この映画は歴史上の出来事に基づいている。"],
  "s3-334": ["I prefer [_____] T-shirts without any pictures.", "私は絵柄のない無地のTシャツが好きだ。"],
  "s3-335": ["The wedding cake had [_____] decorations made of sugar.", "ウエディングケーキには砂糖でできた手の込んだ飾りがついていた。", ["affectionate", "inaccurate", "vulnerable"]],
  "s3-336": ["Many doctors [_____] eating less salt.", "多くの医師が塩分を控えることを提唱している。"],
  "s3-337": ["This TV program is both fun and [_____].", "このテレビ番組は楽しくて教育的でもある。"],
  "s3-338": ["Almost every [_____] in Japan has a refrigerator.", "日本のほぼすべての世帯に冷蔵庫がある。"],
  "s3-340": ["It soon became [_____] that he was lying.", "彼がうそをついているのはすぐに明らかになった。"],
  "s3-341": ["We will [_____] your ideas into our plan.", "あなたの考えを私たちの計画に取り入れます。"],
  "s3-344": ["There is a strong [_____] between the two sisters.", "2人の姉妹はとてもよく似ている。"],
  "s3-345": ["He didn't study at all; [_____], he failed the exam.", "彼はまったく勉強しなかった。その結果、試験に落ちた。"],
  "s3-346": ["I went to lunch with my [_____]s from work.", "職場の同僚と昼食に行った。"],
  "s3-347": ["Everyone should [_____] to keeping the park clean.", "公園をきれいに保つことに誰もが貢献すべきだ。"],
  "s3-350": ["This chemical is [_____] dangerous, so handle it carefully.", "この化学物質は危険になりうるので、注意して扱いなさい。"],
  "s3-351": ["It's easy to [_____] others, but hard to do better yourself.", "他人を批判するのは簡単だが、自分がもっとうまくやるのは難しい。"],
  "s3-352": ["The students did experiments in the science [_____].", "生徒たちは理科室で実験をした。"],
  "s3-355": ["India was once a British [_____].", "インドはかつてイギリスの植民地だった。"],
  "s3-356": ["Trees [_____] their leaves in autumn.", "木は秋に葉を落とす。"],
  "s3-357": ["The cause of the fire is still [_____].", "火事の原因はまだわかっていない。"],
  "s3-362": ["What is the [_____] of this word?", "この単語の起源は何ですか。"],
  "s3-363": ["This restaurant has a good [_____] for fresh seafood.", "このレストランは新鮮な魚介類で評判がよい。"],
  "s3-364": ["The movie's [_____] was hard to follow.", "その映画の筋はわかりにくかった。"],
  "s3-366": ["The cat is sleeping [_____] the table.", "猫がテーブルの下で寝ている。"],
  "s3-368": ["The sun's [_____]s can burn your skin.", "太陽の光線で肌が焼けることがある。"],
  "s3-371": ["The [_____] president gave a speech at the event.", "元大統領がそのイベントで演説した。"],
  "s3-372": ["Air is [_____], but we can feel it when the wind blows.", "空気は目に見えないが、風が吹くと感じられる。"],
  "s3-374": ["Doves are often used as [_____]s of peace.", "ハトはしばしば平和の象徴として使われる。"],
  "s3-375": ["Thank you for your [_____] at the meeting today.", "本日は会議にご出席いただき、ありがとうございます。"],
  "s3-379": ["They will finish paying off the [_____] on their house next year.", "彼らは来年、家の住宅ローンを払い終える。"],
  "s3-381": ["Babies are born [_____].", "赤ちゃんは裸で生まれてくる。"],
  "s3-382": ["I lost my map, but I [_____] found my way back to the hotel.", "地図をなくしたが、どうにかホテルまで戻れた。", ["firmly", "shortly", "socially"]],
  "s3-384": ["She spoke with deep [_____] about the need for change.", "彼女は変革の必要性について強い信念をもって語った。"],
  "s3-385": ["The judge asked the [_____] to stand up.", "裁判官は被告人に起立するよう命じた。"],
  "s3-386": ["The boxer's nose was [_____] after the fight.", "試合のあと、ボクサーの鼻は血まみれだった。"],
  "s3-387": ["I [_____] you're right.", "あなたの言うとおりだと思う。"],
  "s3-388": ["We must [_____] all mistakes before we print the report.", "報告書を印刷する前にすべての間違いを取り除かなければならない。"],
  "s3-389": ["The [_____] of Tokyo is chosen by the people.", "東京都知事は都民が選ぶ。"],
  "s3-390": ["[_____] people settle their arguments by talking, not fighting.", "文明人は争うのではなく、話し合いで言い争いを解決する。"],
  "s3-391": ["This phone uses very [_____] technology.", "この電話はとても高度な技術を使っている。"],
  "s3-392": ["The coffee kept me [_____] all night.", "コーヒーのせいで一晩中眠れなかった。"],
  "s3-393": ["The new machines increased the factory's [_____].", "新しい機械で工場の生産性が上がった。"],
  "s3-395": ["The weather was [_____], so we had lunch outside.", "天気がよかったので、外で昼食をとった。"],
  "s3-396": ["Many [_____]s fled the war and came to Europe.", "多くの難民が戦争を逃れてヨーロッパに来た。"],
  "s3-397": ["The [_____] escaped from jail last night.", "昨夜、囚人が刑務所から脱走した。"],
  "s3-398": ["We went [_____] in Kyoto.", "私たちは京都に観光に行った。"],
  "s3-399": ["After moving to a new city, she suffered from [_____].", "新しい町に引っ越したあと、彼女は孤独に苦しんだ。"],
  "s3-400": ["The castle is the main tourist [_____] in this town.", "その城はこの町の一番の観光名所だ。"],
  "s3-401": ["The whole school gathered in the gym for the morning [_____].", "全校生徒が朝礼のために体育館に集まった。"],
  "s3-402": ["We shouted in the cave and heard our [_____].", "洞窟の中で叫ぶと、こだまが聞こえた。"],
  "s3-403": ["The actors read the [_____] before filming.", "俳優たちは撮影前に台本を読んだ。"],
  "s3-404": ["The [_____] of the new park will take two years.", "新しい公園の造成には2年かかる。"],
  "s3-406": ["The country has seen [_____] growth in recent years.", "その国は近年急速な成長を遂げている。", ["tough", "brief", "naked"]],
  "s3-407": ["Smoking damages your [_____]s.", "喫煙は肺を傷つける。"],
  "s3-409": ["He is not interested in [_____]; he never votes.", "彼は政治に興味がなく、投票したことがない。"],
  "s3-411": ["Good lighting can [_____] the beauty of a room.", "よい照明は部屋の美しさを引き立てる。"],
  "s3-412": ["Put the pictures in the correct [_____].", "絵を正しい順序に並べなさい。"],
  "s3-414": ["The [_____] decided that the man was guilty.", "陪審はその男が有罪だと判断した。"],
  "s3-415": ["Out of [_____], she learned to cook for herself.", "必要に迫られて、彼女は自炊を覚えた。"],
  "s3-416": ["We rode the roller coaster at the [_____] park.", "遊園地でジェットコースターに乗った。"],
  "s3-417": ["The [_____] age to get a driver's license in Japan is 18.", "日本で運転免許を取れる最低年齢は18歳だ。"],
  "s3-418": ["The rich family had many [_____]s to cook and clean.", "その裕福な一家には料理や掃除をする使用人がたくさんいた。"],
  "s3-419": ["She was elected [_____] president of the student council.", "彼女は生徒会の副会長に選ばれた。"],
  "s3-420": ["A large [_____] of the money went to charity.", "そのお金の大部分は慈善団体に寄付された。"],
  "s3-421": ["The show is popular with young [_____]s.", "その番組は若い視聴者に人気がある。"],
  "s3-422": ["This mattress is too [_____] for me.", "このマットレスは私には硬すぎる。"],
  "s3-423": ["Don't walk on the hot sand with [_____] feet.", "熱い砂の上を素足で歩いてはいけない。"],
  "s3-424": ["Universities and hospitals are important public [_____]s.", "大学や病院は重要な公共機関だ。"],
  "s3-425": ["The seller and the [_____] agreed on a price of three million yen.", "売り手と買い手は300万円で合意した。"],
  "s3-426": ["The [_____] of the movie took three months.", "映画の撮影には3か月かかった。"],
  "s3-427": ["Hold the rope [_____] so you don't fall.", "落ちないようにロープをしっかり握って。"],
  "s3-428": ["The two companies are working in [_____] to build the new stadium.", "2社は提携して新しいスタジアムを建設している。"],
  "s3-429": ["My uncle is a used car [_____].", "おじは中古車販売業者だ。"],
  "s3-430": ["Canada has ten [_____]s.", "カナダには10の州がある。"],
  "s3-432": ["The children love to [_____] the forest behind their house.", "子どもたちは家の裏の森を探検するのが大好きだ。"],
  "s3-433": ["As a true [_____], he believes everyone should have a vote.", "真の民主主義者として、彼は誰もが投票権を持つべきだと考えている。"],
  "s3-434": ["The second [_____] of school starts in September.", "2学期は9月に始まる。"],
  "s3-435": ["This farm [_____]s a lot of rice every year.", "この農場は毎年たくさんの米がとれる。", ["block", "laugh", "exist"]],
  "s3-436": ["You must [_____] your fears to overcome them.", "恐怖を克服するには、それに立ち向かわなければならない。"],
  "s3-437": ["The police car drove off in [_____] of the thief.", "パトカーは泥棒を追って走り去った。"],
  "s3-438": ["We need [_____] plans, not just ideas.", "アイデアだけでなく、具体的な計画が必要だ。"],
  "s3-439": ["There was a heated [_____] about the new law.", "新しい法律について激しい討論があった。"],
  "s3-441": ["The [_____] between the workers and the company lasted for months.", "労働者と会社の争議は何か月も続いた。"],
  "s3-442": ["She is a senior [_____] at a large company.", "彼女は大企業の上級幹部だ。"],
  "s3-443": ["My father mows the [_____] every Sunday.", "父は毎週日曜日に芝生を刈る。"],
  "s3-444": ["Our school has very [_____] rules about hair color.", "私たちの学校は髪の色について非常に厳しい規則がある。"],
  "s3-445": ["She is [_____] of running a marathon.", "彼女はマラソンを走る力がある。"],
  "s3-446": ["In the Edo period, [_____]s became rich by trading rice.", "江戸時代、商人は米の取引で裕福になった。"],
  "s3-447": ["My [_____] gave me a raise this year.", "今年は雇い主が給料を上げてくれた。"],
  "s3-448": ["The fish smelled [_____], so I didn't eat it.", "その魚は変なにおいがしたので、食べなかった。"],
  "s3-449": ["The main [_____] of the meeting was the budget.", "会議の主な焦点は予算だった。"],
  "s3-450": ["The newspaper [_____]d the politician's lies.", "新聞はその政治家のうそを暴いた。"],
  "s3-451": ["I'm not [_____] to getting up so early.", "私はこんなに早く起きることに慣れていない。"],
  "s3-452": ["The guide gives [_____] information about every hotel in the city.", "そのガイドは市内のすべてのホテルについて網羅的な情報を載せている。"],
  "s3-453": ["The two colors look the same, but there are [_____] differences.", "その2色は同じに見えるが、微妙な違いがある。"],
  "s3-454": ["Rainy days [_____] me.", "雨の日は気が滅入る。"],
  "s3-455": ["Does Friday [_____] you for the meeting?", "会議は金曜日でご都合はよろしいですか。"],
  "s3-456": ["Our team [_____]ed the champions 3 to 1.", "私たちのチームは王者を3対1で破った。"],
  "s3-457": ["[_____] your hands together to warm them.", "両手をこすり合わせて温めなさい。"],
  "s3-458": ["[_____] to what most people think, bats are not blind.", "多くの人が思っているのとは反対に、コウモリは目が見えないわけではない。"],
  "s3-460": ["Take the clock [_____] to see how it works.", "どうなっているか見るために時計を分解してみて。"],
  "s3-461": ["Her [_____] is high enough to buy a house.", "彼女の収入は家を買えるほど多い。"],
  "s3-462": ["The [_____] cost was much higher than we expected.", "実際の費用は予想よりずっと高かった。"],
  "s3-463": ["I bought this dress on [_____].", "このドレスは衝動買いした。"],
  "s3-464": ["We [_____]ed many problems during the project.", "私たちはその計画の間、多くの問題に遭遇した。"],
  "s3-465": ["Many people don't trust [_____]s.", "多くの人は政治家を信用していない。"],
  "s3-466": ["Reading helps children's [_____] growth.", "読書は子どもの知的な成長を助ける。"],
  "s3-467": ["The doctor [_____]d him to stop smoking.", "医師は彼に禁煙するよう強く勧めた。"],
  "s3-468": ["It is a great [_____] to meet you.", "お会いできて大変光栄です。"],
  "s3-469": ["Her performance was very [_____]; everyone stood up and clapped.", "彼女の演技はとても印象的で、全員が立ち上がって拍手した。"],
  "s3-470": ["I [_____] you 1,000 yen for lunch.", "昼食代の1,000円をあなたに借りている。"],
  "s3-471": ["I have a question [_____] the homework.", "宿題について質問があります。"],
  "s3-472": ["Many people lost their jobs during the [_____].", "景気後退の間に多くの人が職を失った。"],
  "s3-473": ["Many people visit temples for [_____] reasons.", "多くの人が精神的な理由で寺を訪れる。"],
  "s3-474": ["The thief was sent to [_____] for two years.", "泥棒は2年間刑務所に入れられた。"],
  "s3-475": ["The train will arrive [_____].", "電車はまもなく到着します。"],
  "s3-476": ["Water will [_____] at zero degrees.", "水は0度で凍る。"],
  "s3-477": ["We cannot [_____] this level of spending for long.", "この支出の水準を長く続けることはできない。"],
  "s3-478": ["Only a small [_____] of students voted against the plan.", "その計画に反対票を投じたのはごく少数の生徒だけだった。"],
  "s3-479": ["Her desk is covered with [_____]s of paper.", "彼女の机は紙の山で覆われている。"],
  "s3-480": ["The two cultures are quite [_____] from each other.", "2つの文化は互いにかなり異なっている。"],
  "s3-481": ["She works in [_____] at a big bank.", "彼女は大手銀行の財務部門で働いている。"],
  "s3-482": ["A rainbow is a natural [_____] caused by sunlight and rain.", "虹は日光と雨によって起こる自然現象だ。"],
  "s3-483": ["He has no [_____] record.", "彼には前科がない。"],
  "s3-485": ["[_____], I prefer tea to coffee.", "個人的には、コーヒーより紅茶のほうが好きだ。"],
  "s3-487": ["Doctors [_____]d the sick patient to stop the disease from spreading.", "医師たちは病気が広がらないように、その患者を隔離した。", ["navigate", "vibrate", "calculate"]],
  "s3-488": ["Please wear [_____] clothes for the interview.", "面接にはふさわしい服装で来てください。"],
  "s3-489": ["Do you believe in the [_____] of ghosts?", "幽霊の存在を信じますか。"],
  "s3-490": ["The pharmacist [_____]ed the medicine for my grandmother.", "薬剤師が祖母の薬を調合した。"],
  "s3-491": ["Rice is the main [_____] in this area.", "米はこの地域の主な作物だ。"],
  "s3-492": ["The company plans to [_____] its business to Asia.", "その会社はアジアへ事業を拡大する予定だ。"],
  "s3-494": ["I'm [_____] to agree with you.", "あなたに賛成したい気持ちだ。"],
  "s3-496": ["The snake [_____]ed the egg whole.", "ヘビは卵を丸のみにした。"],
  "s3-497": ["My little sister is in [_____] school.", "妹は小学校に通っている。"],
  "s3-498": ["Be careful; that dog may [_____].", "気をつけて。あの犬はかむかもしれないよ。"],
  "s3-499": ["There are billions of stars in the [_____].", "宇宙には何十億もの星がある。"],
  "s3-500": ["Children have a rich [_____].", "子どもは想像力が豊かだ。"],
  "s3-501": ["The island has only 200 [_____]s.", "その島の住民はわずか200人だ。"],
  "s3-502": ["The [_____] from the explosion broke windows across the street.", "爆発の爆風で通りの向こうの窓ガラスが割れた。"],
  "s3-503": ["She works in the sales [_____].", "彼女は営業部で働いている。"],
  "s3-504": ["My dog has been my faithful [_____] for ten years.", "犬は10年間、私の忠実な仲間だった。"],
  "s3-505": ["The police [_____]d the stolen goods.", "警察は盗品を押収した。"],
  "s3-506": ["The People's [_____] of China was founded in 1949.", "中華人民共和国は1949年に建国された。"],
  "s3-507": ["It is our [_____] to protect the environment.", "環境を守るのは私たちの務めだ。"],
  "s3-508": ["She cried with [_____] when she heard she had passed.", "合格したと聞いて、彼女はうれし泣きした。"],
  "s3-509": ["The doctor gave me a full medical [_____].", "医師は私に精密な健康診断をしてくれた。"],
  "s3-510": ["Look in the [_____] at the back of the book.", "本の後ろにある索引を見なさい。"],
  "s3-511": ["I had to [_____] the invitation because I was busy.", "忙しかったので招待を断らなければならなかった。"],
  "s3-512": ["In Japan, people [_____] when they greet each other.", "日本では、あいさつするときにお辞儀をする。"],
  "s3-513": ["The fisherman [_____] his net into the sea.", "漁師は海に網を投げた。"],
  "s3-514": ["The view from the top was truly [_____].", "頂上からの眺めは本当に素晴らしかった。"],
  "s3-515": ["Because of the [_____], it took us three hours to get home.", "交通渋滞のせいで、家に帰るのに3時間かかった。"],
  "s3-516": ["There is a lot of [_____] in temperature between day and night.", "昼と夜で気温の変化が大きい。"],
  "s3-517": ["Damage to the [_____]s in his back caused pain in his legs.", "背中の神経が傷ついて、脚に痛みが出た。"],
  "s3-518": ["The earthquake caused great [_____].", "地震は大きな破壊をもたらした。"],
  "s3-519": ["They got [_____] last month and will marry next spring.", "彼らは先月婚約し、来春結婚する。"],
  "s3-520": ["Don't be so [_____]; speak up in class!", "そんなに消極的にならないで。授業で発言しよう！"],
  "s3-521": ["Can you [_____] the total cost?", "合計の費用を計算できますか。"],
  "s3-522": ["Don't make [_____]s about people before you know them.", "人をよく知る前に決めつけてはいけない。"],
  "s3-523": ["Graduating from university was a big [_____] for him.", "大学を卒業したことは彼にとって大きな業績だった。"],
  "s3-524": ["[_____], I didn't like him, but now we're good friends.", "最初は彼が好きではなかったが、今では仲のよい友人だ。"],
  "s3-525": ["It rained without [_____] for three days.", "3日間絶え間なく雨が降った。"],
  "s3-526": ["On [_____] of the school, I welcome you.", "学校を代表して皆さんを歓迎します。"],
  "s3-527": ["Flowers [_____] bees with their bright colors.", "花は鮮やかな色でハチを引きつける。"],
  "s3-528": ["What do you do in your [_____] time?", "余暇には何をしていますか。"],
  "s3-529": ["I have a sore [_____], so I can't sing today.", "のどが痛いので、今日は歌えない。"],
  "s3-530": ["The lost hikers were [_____] for food and water.", "道に迷ったハイカーたちは食べ物と水を必死に求めていた。"],
  "s3-531": ["[_____] the important words with a yellow pen.", "大事な単語を黄色のペンで目立たせなさい。"],
  "s3-532": ["She took the [_____] and organized the event herself.", "彼女は自ら率先してそのイベントを企画した。"],
  "s3-533": ["The [_____] Party controls the government in China.", "中国では共産党が政府を支配している。"],
  "s3-534": ["The job market is very [_____]; many people apply for each job.", "求人市場は競争が激しく、一つの仕事に多くの人が応募する。"],
  "s3-535": ["One team [_____]d the whole game.", "一方のチームが試合を終始支配した。"],
  "s3-536": ["The first European [_____] in America was built in 1607.", "アメリカで最初のヨーロッパ人の入植地は1607年に作られた。"],
  "s3-538": ["Living abroad gave me a new [_____] on my own country.", "海外で暮らして、自分の国を新しい視点から見られるようになった。"],
  "s3-539": ["The war turned the city into a living [_____].", "戦争でその町は生き地獄と化した。"],
  "s3-540": ["It's [_____] that he hasn't called; he usually calls every day.", "彼から電話がないのは変だ。いつもは毎日かけてくるのに。"],
  "s3-542": ["The scientists tested the water in the [_____].", "科学者たちは研究所で水を検査した。"],
  "s3-543": ["The fire spread [_____] through the dry forest.", "火は乾いた森の中を急速に広がった。"],
  "s3-544": ["Oxygen is a chemical [_____].", "酸素は化学元素だ。"],
  "s3-545": ["The company's [_____] is in Tokyo.", "その会社の本社は東京にある。"],
  "s3-546": ["Her parents' [_____] was hard for her.", "両親の離婚は彼女にとってつらかった。"],
  "s3-547": ["The doctors attended an international [_____] in Paris.", "医師たちはパリで開かれた国際会議に出席した。"],
  "s3-548": ["You are under no [_____] to buy anything.", "何かを買う義務はまったくありません。"],
  "s3-549": ["A large [_____] of money was found in the old house.", "その古い家から多額のお金が見つかった。"],
  "s3-550": ["The [_____] of the airport will take five years.", "空港の拡張には5年かかる。"],
  "s3-552": ["She keeps her old toys in a wooden [_____].", "彼女は古いおもちゃを木のたんすにしまっている。"],
  "s3-553": ["The store is open [_____] nine tonight.", "その店は今夜9時まで開いている。"],
  "s3-554": ["The car's [_____] lights turn on when you open the door.", "ドアを開けると車の室内灯がつく。"],
  "s3-555": ["Dolphins are known for their high [_____].", "イルカは知能が高いことで知られている。"],
  "s3-556": ["Nobody knows who sent the [_____] letter.", "誰がその謎の手紙を送ったのか、誰も知らない。"],
  "s3-557": ["Forest [_____] is important to protect wildlife.", "野生動物を守るために森林の保全が重要だ。"],
  "s3-558": ["There was a lot of [_____] about the new rules.", "新しい規則について多くの混乱があった。"],
  "s3-559": ["Don't [_____] against the door; it might open.", "ドアに寄りかからないで。開くかもしれないよ。"],
  "s3-560": ["Please [_____] to Gate 5 for boarding.", "搭乗のため5番ゲートへお進みください。"],
  "s3-561": ["She tried to [_____] a laugh during the serious meeting.", "彼女はまじめな会議の間、笑いをこらえようとした。"],
  "s3-562": ["Words cannot [_____] how grateful I am.", "どれほど感謝しているか、言葉では伝えられない。"],
  "s3-563": ["The rotten eggs had a very [_____] smell, so we threw them away.", "腐った卵はとても嫌なにおいがしたので、捨てた。"],
  "s3-564": ["We walked along a narrow [_____] through the forest.", "私たちは森の中の細い小道を歩いた。"],
  "s3-565": ["I'd like to [_____] a table for two at seven.", "7時に2人で席を予約したいのですが。"],
  "s3-567": ["This question has [_____] correct answers.", "この問題には正解が複数ある。"],
  "s3-568": ["Please read [_____] 3 for homework.", "宿題として第3章を読んでください。"],
  "s3-569": ["The [_____] asked the judge to send the man to prison.", "検察官は裁判官にその男を刑務所に送るよう求めた。"],
  "s3-570": ["Cleaning the whole house was a difficult [_____].", "家全体を掃除するのは大変な仕事だった。"],
  "s3-571": ["Problems may [_____] if we don't plan carefully.", "慎重に計画しないと問題が起こるかもしれない。"],
  "s3-572": ["[_____] the word in your dictionary.", "辞書でその単語を調べなさい。"],
  "s3-573": ["[_____], people traveled by horse.", "昔は人々は馬で移動した。"],
  "s3-574": ["[_____], almost everyone has a smartphone.", "近頃はほとんど誰もがスマートフォンを持っている。"],
  "s3-575": ["In case of [_____], call 119.", "緊急の場合は119番に電話してください。"],
  "s3-576": ["Which ice cream [_____] do you like best?", "どのアイスクリームの味が一番好きですか。"],
  "s3-577": ["We asked a computer [_____] to fix the problem.", "コンピュータの専門家にその問題を直してもらった。"],
  "s3-578": ["It was [_____] of me to forget my own birthday.", "自分の誕生日を忘れるなんて、私もばかだった。"],
  "s3-579": ["[_____] in deeply and hold it for five seconds.", "深く息を吸って、5秒間止めなさい。"],
  "s3-580": ["Put the milk back in the [_____].", "牛乳を冷蔵庫に戻して。"],
  "s3-581": ["We need eggs, milk, bread, [_____].", "卵、牛乳、パンなどが必要だ。"],
  "s3-582": ["Could you [_____] and close the window?", "お願いがあるんだけど、窓を閉めてくれない？"],
  "s3-583": ["She doesn't [_____] her sister; they argue all the time.", "彼女は姉と仲が悪く、いつも言い争っている。"],
  "s3-584": ["Please [_____] that the store closes at eight.", "その店は8時に閉まることを覚えておいてください。"],
  "s3-585": ["I saw a rainbow [_____] school this morning.", "今朝、学校へ行く途中で虹を見た。"],
  "s3-586": ["It takes ten minutes to get to the station [_____].", "駅まで歩いて10分かかる。"],
  "s3-587": ["The elevator is [_____], so please use the stairs.", "エレベーターは故障中なので、階段を使ってください。"],
  "s3-588": ["If you keep practicing, you will succeed [_____].", "練習を続ければ、遅かれ早かれ成功する。"],
  "s3-589": ["Can I [_____] this jacket?", "このジャケットを試着してもいいですか。"],
  "s3-590": ["Why did you [_____] such a good job offer?", "どうしてそんなによい仕事の話を断ったの？"],
  "s3-592": ["You need a lot of [_____] to start a new business.", "新しい事業を始めるには多くの資本が必要だ。"],
  "s3-593": ["What is the [_____] of Mount Fuji?", "富士山の高さはどのくらいですか。"],
  "s3-595": ["Japan [_____]s most of its oil from the Middle East.", "日本は石油のほとんどを中東から輸入している。"],
  "s3-596": ["The neighbors [_____]ed about the noise.", "近所の人たちは騒音に苦情を言った。"],
  "s3-597": ["Don't [_____] people just because they are poor.", "貧しいからといって人を見下してはいけない。"],
  "s3-598": ["Drink [_____] water when it's hot.", "暑いときは水をたくさん飲みなさい。"],
  "s3-599": ["The people will [_____] a new president next year.", "国民は来年新しい大統領を選ぶ。"],
  "s3-603": ["The university gave him a research [_____] of one million yen.", "大学は彼に100万円の研究助成金を与えた。"],
  "s3-604": ["The lawyer met with her [_____] to discuss the case.", "弁護士は事件について話し合うため依頼人と会った。"],
  "s3-605": ["This bridge is made of [_____].", "この橋は鋼鉄でできている。"],
  "s3-606": ["She [_____]s her success to hard work.", "彼女は自分の成功は努力のおかげだと考えている。"],
  "s3-607": ["The police [_____]d him of stealing the car.", "警察は彼を車を盗んだ罪で告発した。"],
  "s3-608": ["This is the [_____] \"smart city\" of the future.", "これがいわゆる未来の「スマートシティ」だ。"],
  "s3-610": ["The school [_____] decided to change the rules.", "学校の運営側が規則を変えることにした。"],
  "s3-611": ["I have no [_____] of quitting my job.", "私には仕事を辞めるつもりはまったくない。"],
  "s3-612": ["We use the basement for [_____].", "私たちは地下室を物置として使っている。"],
  "s3-613": ["Don't [_____] your eyes by reading in the dark.", "暗いところで本を読んで目を酷使しないで。"],
  "s3-615": ["This national park is home to a lot of [_____].", "この国立公園には多くの野生動物がすんでいる。"],
  "s3-616": ["The band [_____]ed the guests all evening.", "バンドは一晩中客を楽しませた。"],
  "s3-617": ["The bus was full of [_____]s.", "バスは乗客でいっぱいだった。"],
  "s3-618": ["How much money do you [_____] a month?", "1か月にいくら稼いでいますか。"],
  "s3-619": ["You need [_____] permission to enter this room.", "この部屋に入るには事前の許可が必要だ。"],
  "s3-620": ["The doctor's [_____] of my health was positive.", "医師による私の健康の評価はよいものだった。"],
  "s3-621": ["The robber [_____]ed to hurt the clerk.", "強盗は店員を傷つけると脅した。"],
  "s3-622": ["Few people understood the [_____] of his discovery at the time.", "当時、彼の発見の重要性を理解した人はほとんどいなかった。"],
  "s3-624": ["Many [_____]s came to America looking for a better life.", "多くの移民がよりよい生活を求めてアメリカに来た。"],
  "s3-625": ["A small [_____] runs behind our house.", "家の裏に小川が流れている。"],
  "s3-626": ["What do you [_____] to do after graduation?", "卒業後は何をするつもりですか。"],
  "s3-627": ["After careful [_____], we decided to buy the house.", "よく考えた末、私たちはその家を買うことにした。"],
  "s3-628": ["The agent takes a ten percent [_____] on every sale.", "代理人は販売ごとに10パーセントの手数料を取る。"],
  "s3-629": ["He gets along well with his [_____] workers.", "彼は同僚とうまくやっている。"],
  "s3-631": ["It rained [_____] the night.", "一晩中雨が降った。"],
  "s3-632": ["Crows are surprisingly [_____] birds.", "カラスは驚くほど賢い鳥だ。"],
  "s3-633": ["The baby cried [_____] all night.", "赤ちゃんは一晩中泣き続けた。"],
  "s3-634": ["The company has 300 [_____]s.", "その会社には300人の従業員がいる。"],
  "s3-635": ["He continues to [_____] that he stole the money.", "彼はお金を盗んだことを否定し続けている。"],
  "s3-636": ["The new building will [_____] the whole block.", "新しい建物はその区画全体を占める。"],
  "s3-638": ["We walked along the [_____] of the lake.", "私たちは湖のほとりを歩いた。"],
  "s3-639": ["The [_____] missed him by a few centimeters.", "弾丸は数センチの差で彼をそれた。"],
  "s3-642": ["He spent ten years in [_____].", "彼は刑務所で10年過ごした。"],
  "s3-643": ["Muscle [_____] is made up of many cells.", "筋肉の組織はたくさんの細胞からできている。"],
  "s3-645": ["We are waiting for the [_____] of the election.", "私たちは選挙の結果を待っている。"],
  "s3-646": ["The [_____] of the company opened the meeting.", "会社の会長が会議を開会した。"],
  "s3-648": ["I took notes during the history [_____].", "歴史の講義の間、ノートを取った。"],
  "s3-649": ["It's [_____] to save some money for emergencies.", "緊急時に備えて貯金しておくのは賢明だ。"],
  "s3-650": ["His [_____]s from the part-time job are about 50,000 yen a month.", "彼のアルバイトの収入は月に約5万円だ。"],
  "s3-651": ["I can't [_____] with all this noise.", "こんなにうるさいと集中できない。"],
  "s3-654": ["The town's water [_____] was cut off after the earthquake.", "地震のあと町の給水が止まった。"],
  "s3-655": ["He [_____]es a large collection of old coins.", "彼は古い硬貨をたくさん所有している。"],
  "s3-656": ["Don't [_____]; we have plenty of time.", "急がないで。時間はたっぷりある。"],
  "s3-657": ["He never lies; it's against his [_____]s.", "彼は決してうそをつかない。それは彼の信条に反するのだ。"],
  "s3-658": ["Please be [_____] with me; did you break the vase?", "正直に言って。花瓶を割ったのはあなた？"],
  "s3-659": ["\"Time is money\" is a famous [_____].", "「時は金なり」は有名なことわざだ。"],
  "s3-660": ["Please [_____] the app to the latest version.", "アプリを最新版に更新してください。"],
  a115: ["We decided to [_____] our stay by two days.", "私たちは滞在を2日延ばすことにした。"],
  a314: ["The road was blocked by snow; [_____], we had to turn back.", "道は雪でふさがれていた。こうして私たちは引き返さなければならなかった。"],
  a587: ["The [_____] of the murder suspect began yesterday.", "殺人事件の容疑者の裁判が昨日始まった。"],
  a658: ["Prices [_____] from shop to shop.", "値段は店によって異なる。"],
  a1338: ["The test was [_____] harder than I expected.", "テストは思っていたより少し難しかった。"],
  a1386: ["I [_____]d you knew about the meeting.", "あなたは会議のことを知っていると思い込んでいた。"],
  a1635: ["The sun [_____]d from behind the clouds.", "太陽が雲の後ろから現れた。"],
  a1694: ["The fish [_____]d to get free from the net.", "魚は網から逃れようともがいた。"],
  a1730: ["His rude [_____] made her angry.", "彼の失礼な発言に彼女は腹を立てた。"],
  a1799: ["It's rude to [_____] at people.", "人をじろじろ見るのは失礼だ。", ["adore", "probe", "assume"]],
  b2_backyard: ["The kids are playing in the [_____].", "子どもたちは裏庭で遊んでいる。"],
  b2_botany: ["She studied [_____] because she loves plants.", "彼女は植物が大好きなので植物学を学んだ。"],
  b2_journalism: ["He studied [_____] and now works for a newspaper.", "彼はジャーナリズムを学び、今は新聞社で働いている。"],
  b2_perspiration: ["After the long run, his face was covered in [_____].", "長距離を走ったあと、彼の顔は汗まみれだった。"],
  b2_programmer: ["My brother works as a computer [_____].", "兄はコンピュータのプログラマーとして働いている。"],
};
